-- Public Budokan Sud Oise data consulted September 2026. See the milestone report.
-- This file is executed only inside SeedBudokan's guarded transaction.
INSERT INTO organizations (name,short_name,description,public_email,public_phone,public_phone_label,website_url,trial_session_description,trial_items_to_bring,trial_equipment_offer,trial_equipment_detail_prompt)
VALUES ('Budokan Sud Oise','BS.O','Une association de sports de combat à Lamorlaye, avec des séances pour enfants, adolescents et adultes. Découvrez le groupe et le créneau qui vous conviennent, puis venez partager une première séance.','budokansud.oise@gmail.com','06 21 03 21 61','Seb Colosse','https://www.budokansudoise.com/','La séance comprend généralement un échauffement, une partie technique puis des combats. Un gradé vous accompagne pour découvrir l’activité et répondre à vos questions.',ARRAY['De l’eau','Une tenue de sport confortable','Des claquettes pour circuler jusqu’au dojo'],'Un kimono peut être prêté selon les disponibilités.','Indiquez votre taille afin que nous puissions prévoir un kimono adapté, selon les disponibilités.');
INSERT INTO organization_public_images (organization_id,placement,src,webp_srcset,alt,width,height)
SELECT id,placement,src,webp_srcset,alt,width,height FROM organizations CROSS JOIN (VALUES
 ('hero','/static/images/budokan/hero/hero-bureau-mascots.png','/static/images/budokan/hero/hero-bureau-mascots-800.webp 800w, /static/images/budokan/hero/hero-bureau-mascots-1600.webp 1600w','Les mascottes du club en tenue de jiu-jitsu brésilien',1774,887),
 ('activity','/static/images/budokan/illustrations/training-jjb.png','/static/images/budokan/illustrations/training-jjb-800.webp 800w, /static/images/budokan/illustrations/training-jjb-1536.webp 1536w','',1536,1024),
 ('community','/static/images/budokan/illustrations/club-spirit.png','/static/images/budokan/illustrations/club-spirit-800.webp 800w, /static/images/budokan/illustrations/club-spirit-1536.webp 1536w','',1536,1024),
 ('schedule','/static/images/budokan/illustrations/schedule-jjb.png','/static/images/budokan/illustrations/schedule-jjb-800.webp 800w, /static/images/budokan/illustrations/schedule-jjb-1536.webp 1536w','',1536,1024),
 ('trial','/static/images/budokan/illustrations/trial-jjb.png','/static/images/budokan/illustrations/trial-jjb-800.webp 800w, /static/images/budokan/illustrations/trial-jjb-1536.webp 1536w','',1536,1024)
) AS media(placement,src,webp_srcset,alt,width,height);
INSERT INTO locations (organization_id,name,address)
SELECT id,'Gymnase La Mardelle','Rue des Marais, 60260 Lamorlaye' FROM organizations;
INSERT INTO organization_links (organization_id,kind,label,url)
SELECT id,'instagram','Instagram','https://www.instagram.com/budokan_sud_oise/' FROM organizations;
-- One Season confirmed for V1; course closures remain a calendar concern.
INSERT INTO seasons (name,starts_at,ends_at) VALUES ('2026/2027','2026-09-01','2027-08-31');
INSERT INTO activities (name) VALUES ('Jiu-Jitsu Brésilien'),('Jiu-Jitsu Traditionnel / Combat'),('Préparation physique');
-- Ages in children's names are pedagogical indications, never eligibility constraints.
INSERT INTO groups (activity_id,name,description) SELECT id,'JJB enfants 7–10 ans',NULL FROM activities WHERE name='Jiu-Jitsu Brésilien';
INSERT INTO groups (activity_id,name,description) SELECT id,'JJB enfants 10–14 ans',NULL FROM activities WHERE name='Jiu-Jitsu Brésilien';
INSERT INTO groups (activity_id,name,description) SELECT id,'JJB Adolescents et Adultes','No-Gi : séance mixte adolescents et adultes. JJB libre : pratique libre surveillée, sans cours structuré. Préparation physique / JJB : environ 45 minutes de renforcement musculaire et cardio, puis JJB.' FROM activities WHERE name='Jiu-Jitsu Brésilien';
INSERT INTO groups (activity_id,name,description) SELECT id,'Jiu-Jitsu Traditionnel / Combat enfants 7–10 ans',NULL FROM activities WHERE name='Jiu-Jitsu Traditionnel / Combat';
INSERT INTO groups (activity_id,name,description) SELECT id,'Jiu-Jitsu Traditionnel / Combat enfants 10–14 ans',NULL FROM activities WHERE name='Jiu-Jitsu Traditionnel / Combat';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,1,'18:15','19:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='Jiu-Jitsu Traditionnel / Combat enfants 7–10 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,1,'19:15','20:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='Jiu-Jitsu Traditionnel / Combat enfants 10–14 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,1,'20:15','22:00',l.id,'Préparation physique / Jiu-Jitsu Brésilien',s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,2,'18:15','19:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB enfants 7–10 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,2,'19:15','20:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB enfants 10–14 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,2,'20:15','22:00',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,3,'18:15','19:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB enfants 7–10 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,3,'19:15','20:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB enfants 10–14 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,3,'20:15','22:00',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,4,'18:15','19:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='Jiu-Jitsu Traditionnel / Combat enfants 7–10 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,4,'19:15','20:15',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='Jiu-Jitsu Traditionnel / Combat enfants 10–14 ans';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,4,'20:15','22:00',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,5,'20:15','22:00',l.id,'Préparation physique / JJB — Adolescents et Adultes',s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,6,'10:00','12:00',l.id,'JJB No-Gi',s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,6,'16:00','18:00',l.id,NULL,s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
INSERT INTO group_slots (group_id,season_id,weekday,start_time,end_time,location_id,practice_label,valid_from,valid_until) SELECT g.id,s.id,7,'16:00','18:00',l.id,'JJB libre',s.starts_at,s.ends_at FROM groups g CROSS JOIN seasons s CROSS JOIN locations l WHERE g.name='JJB Adolescents et Adultes';
-- Names confirmed on /tarifs (2026/2027); the existing model has no price field.
INSERT INTO membership_types (name) VALUES ('Adulte'),('Adolescent'),('Enfant');
-- Demonstration wording, not a transcription or approved legal instrument.
INSERT INTO consent_definitions (code,version,title,description) VALUES
 ('image_rights',1,'Droit à l’image','Démonstration : autoriser ou refuser les photographies et vidéos prises pendant les activités du club pour sa communication. Texte définitif à valider par le bureau.');
