// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_provisioning.sql

package dbsqlc

import (
	"context"
)

const createUserForPersonUsername = `-- name: CreateUserForPersonUsername :one
INSERT INTO users(person_id,username,is_active) VALUES ($1,$2,true)
ON CONFLICT (username) DO NOTHING RETURNING id
`

type CreateUserForPersonUsernameParams struct {
	PersonID int32
	Username string
}

func (q *Queries) CreateUserForPersonUsername(ctx context.Context, arg CreateUserForPersonUsernameParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserForPersonUsername, arg.PersonID, arg.Username)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const lockAccountPerson = `-- name: LockAccountPerson :one
SELECT first_name,last_name FROM persons WHERE id=$1 FOR UPDATE
`

type LockAccountPersonRow struct {
	FirstName string
	LastName  string
}

func (q *Queries) LockAccountPerson(ctx context.Context, id int32) (LockAccountPersonRow, error) {
	row := q.db.QueryRow(ctx, lockAccountPerson, id)
	var i LockAccountPersonRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}
