// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: administration.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const administrativeActivities = `-- name: AdministrativeActivities :many
SELECT id,name FROM activities WHERE is_active ORDER BY name,id
`

type AdministrativeActivitiesRow struct {
	ID   int32
	Name string
}

func (q *Queries) AdministrativeActivities(ctx context.Context) ([]AdministrativeActivitiesRow, error) {
	rows, err := q.db.Query(ctx, administrativeActivities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativeActivitiesRow
	for rows.Next() {
		var i AdministrativeActivitiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administrativeCounts = `-- name: AdministrativeCounts :one
SELECT
 (SELECT count(*) FROM trial_registrations WHERE trial_date=$1::date AND status='registered') AS today_trials,
 (SELECT count(*) FROM trial_registrations WHERE trial_date>$1::date AND status='registered') AS upcoming_trials,
 (SELECT count(*) FROM memberships WHERE status='pending') AS pending_memberships
`

type AdministrativeCountsRow struct {
	TodayTrials        int64
	UpcomingTrials     int64
	PendingMemberships int64
}

func (q *Queries) AdministrativeCounts(ctx context.Context, today pgtype.Date) (AdministrativeCountsRow, error) {
	row := q.db.QueryRow(ctx, administrativeCounts, today)
	var i AdministrativeCountsRow
	err := row.Scan(&i.TodayTrials, &i.UpcomingTrials, &i.PendingMemberships)
	return i, err
}

const administrativeMembershipTypes = `-- name: AdministrativeMembershipTypes :many
SELECT id,name FROM membership_types WHERE is_active ORDER BY name,id
`

type AdministrativeMembershipTypesRow struct {
	ID   int32
	Name string
}

func (q *Queries) AdministrativeMembershipTypes(ctx context.Context) ([]AdministrativeMembershipTypesRow, error) {
	rows, err := q.db.Query(ctx, administrativeMembershipTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativeMembershipTypesRow
	for rows.Next() {
		var i AdministrativeMembershipTypesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administrativeMemberships = `-- name: AdministrativeMemberships :many
SELECT m.id,m.status,s.name AS season_name,t.name AS type_name,
 ARRAY(SELECT g.name FROM membership_groups mg JOIN groups g ON g.id=mg.group_id WHERE mg.membership_id=m.id AND g.is_active AND mg.joined_at<=$1::date AND (mg.left_at IS NULL OR mg.left_at>$1::date) ORDER BY g.name)::text[] AS groups
FROM memberships m JOIN seasons s ON s.id=m.season_id JOIN membership_types t ON t.id=m.membership_type_id
WHERE m.person_id=$2 ORDER BY s.starts_at DESC,m.id DESC
`

type AdministrativeMembershipsParams struct {
	Today    pgtype.Date
	PersonID int32
}

type AdministrativeMembershipsRow struct {
	ID         int32
	Status     string
	SeasonName string
	TypeName   string
	Groups     []string
}

func (q *Queries) AdministrativeMemberships(ctx context.Context, arg AdministrativeMembershipsParams) ([]AdministrativeMembershipsRow, error) {
	rows, err := q.db.Query(ctx, administrativeMemberships, arg.Today, arg.PersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativeMembershipsRow
	for rows.Next() {
		var i AdministrativeMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SeasonName,
			&i.TypeName,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administrativePerson = `-- name: AdministrativePerson :one
SELECT id,first_name,last_name,birth_date,email,phone_number,address,notes,archived_at FROM persons WHERE id=$1
`

type AdministrativePersonRow struct {
	ID          int32
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	Email       pgtype.Text
	PhoneNumber pgtype.Text
	Address     pgtype.Text
	Notes       pgtype.Text
	ArchivedAt  pgtype.Timestamptz
}

func (q *Queries) AdministrativePerson(ctx context.Context, id int32) (AdministrativePersonRow, error) {
	row := q.db.QueryRow(ctx, administrativePerson, id)
	var i AdministrativePersonRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Notes,
		&i.ArchivedAt,
	)
	return i, err
}

const administrativePersonAccount = `-- name: AdministrativePersonAccount :many
SELECT username,is_active,(activated_at IS NOT NULL)::boolean AS activated
FROM users WHERE person_id=$1
`

type AdministrativePersonAccountRow struct {
	Username  string
	IsActive  bool
	Activated bool
}

func (q *Queries) AdministrativePersonAccount(ctx context.Context, personID int32) ([]AdministrativePersonAccountRow, error) {
	rows, err := q.db.Query(ctx, administrativePersonAccount, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativePersonAccountRow
	for rows.Next() {
		var i AdministrativePersonAccountRow
		if err := rows.Scan(&i.Username, &i.IsActive, &i.Activated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administrativeRelations = `-- name: AdministrativeRelations :many
SELECT p.id,p.first_name,p.last_name,r.relationship_type,r.is_primary_contact,
 (r.child_person_id=$1)::boolean AS is_guardian, (p.archived_at IS NOT NULL)::boolean AS archived
FROM person_guardians r JOIN persons p ON p.id=CASE WHEN r.child_person_id=$1 THEN r.guardian_person_id ELSE r.child_person_id END
WHERE r.child_person_id=$1 OR r.guardian_person_id=$1
ORDER BY p.last_name,p.first_name,r.id
`

type AdministrativeRelationsRow struct {
	ID               int32
	FirstName        string
	LastName         string
	RelationshipType string
	IsPrimaryContact bool
	IsGuardian       bool
	Archived         bool
}

func (q *Queries) AdministrativeRelations(ctx context.Context, personID int32) ([]AdministrativeRelationsRow, error) {
	rows, err := q.db.Query(ctx, administrativeRelations, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativeRelationsRow
	for rows.Next() {
		var i AdministrativeRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.RelationshipType,
			&i.IsPrimaryContact,
			&i.IsGuardian,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administrativeSeasons = `-- name: AdministrativeSeasons :many
SELECT id,name FROM seasons WHERE is_active ORDER BY starts_at DESC,id
`

type AdministrativeSeasonsRow struct {
	ID   int32
	Name string
}

func (q *Queries) AdministrativeSeasons(ctx context.Context) ([]AdministrativeSeasonsRow, error) {
	rows, err := q.db.Query(ctx, administrativeSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativeSeasonsRow
	for rows.Next() {
		var i AdministrativeSeasonsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administrativeSlots = `-- name: AdministrativeSlots :many
SELECT gs.id,g.name AS group_name,s.name AS season_name,gs.weekday,to_char(gs.start_time,'HH24:MI')::text AS start_time,
 to_char(gs.end_time,'HH24:MI')::text AS end_time,coalesce(gs.location,'')::text AS location
FROM group_slots gs JOIN groups g ON g.id=gs.group_id JOIN seasons s ON s.id=gs.season_id WHERE gs.is_active AND g.is_active ORDER BY g.name,s.starts_at DESC,gs.weekday,gs.start_time
`

type AdministrativeSlotsRow struct {
	ID         int32
	GroupName  string
	SeasonName string
	Weekday    int16
	StartTime  string
	EndTime    string
	Location   string
}

func (q *Queries) AdministrativeSlots(ctx context.Context) ([]AdministrativeSlotsRow, error) {
	rows, err := q.db.Query(ctx, administrativeSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativeSlotsRow
	for rows.Next() {
		var i AdministrativeSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.SeasonName,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administrativeTrials = `-- name: AdministrativeTrials :many
SELECT t.id,t.person_id,p.first_name,p.last_name,t.activity_id,a.name AS activity_name,t.group_id,coalesce(g.name,'')::text AS group_name,
 t.group_slot_id,coalesce(to_char(gs.start_time,'HH24:MI'),'')::text AS start_time,coalesce(to_char(gs.end_time,'HH24:MI'),'')::text AS end_time,
 coalesce(gs.location,'')::text AS location,t.trial_date,t.status,t.notes,t.revision
FROM trial_registrations t JOIN persons p ON p.id=t.person_id JOIN activities a ON a.id=t.activity_id
LEFT JOIN groups g ON g.id=t.group_id LEFT JOIN group_slots gs ON gs.id=t.group_slot_id
WHERE ($1::integer=0 OR t.person_id=$1)
AND ($2::integer=0 OR t.id=$2)
AND ($3::date IS NULL OR t.trial_date=$3)
AND ($4::date IS NULL OR (t.trial_date>=$4 AND t.status='registered'))
ORDER BY t.trial_date,t.id LIMIT 101
`

type AdministrativeTrialsParams struct {
	PersonID int32
	TrialID  int32
	OnDate   pgtype.Date
	FromDate pgtype.Date
}

type AdministrativeTrialsRow struct {
	ID           int32
	PersonID     int32
	FirstName    string
	LastName     string
	ActivityID   int32
	ActivityName string
	GroupID      pgtype.Int4
	GroupName    string
	GroupSlotID  pgtype.Int4
	StartTime    string
	EndTime      string
	Location     string
	TrialDate    pgtype.Date
	Status       string
	Notes        pgtype.Text
	Revision     int32
}

func (q *Queries) AdministrativeTrials(ctx context.Context, arg AdministrativeTrialsParams) ([]AdministrativeTrialsRow, error) {
	rows, err := q.db.Query(ctx, administrativeTrials,
		arg.PersonID,
		arg.TrialID,
		arg.OnDate,
		arg.FromDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministrativeTrialsRow
	for rows.Next() {
		var i AdministrativeTrialsRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.ActivityID,
			&i.ActivityName,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlotID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.TrialDate,
			&i.Status,
			&i.Notes,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAdministrativeEvent = `-- name: CreateAdministrativeEvent :exec
INSERT INTO administrative_events(actor_user_id,action,resource_type,resource_id) VALUES($1,$2,$3,$4)
`

type CreateAdministrativeEventParams struct {
	ActorUserID  int32
	Action       string
	ResourceType string
	ResourceID   int32
}

func (q *Queries) CreateAdministrativeEvent(ctx context.Context, arg CreateAdministrativeEventParams) error {
	_, err := q.db.Exec(ctx, createAdministrativeEvent,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const lockAdministrativeMembership = `-- name: LockAdministrativeMembership :one
SELECT id, person_id, season_id, membership_type_id, status, joined_at, ended_at, created_at, updated_at, requested_at, approved_at, approved_by_user_id, admin_note FROM memberships WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockAdministrativeMembership(ctx context.Context, id int32) (Membership, error) {
	row := q.db.QueryRow(ctx, lockAdministrativeMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.SeasonID,
		&i.MembershipTypeID,
		&i.Status,
		&i.JoinedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.AdminNote,
	)
	return i, err
}

const lockAdministrativePerson = `-- name: LockAdministrativePerson :one
SELECT id FROM persons WHERE id=$1 AND archived_at IS NULL FOR NO KEY UPDATE
`

func (q *Queries) LockAdministrativePerson(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockAdministrativePerson, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const lockAdministrativeTrial = `-- name: LockAdministrativeTrial :one
SELECT id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id, revision FROM trial_registrations WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockAdministrativeTrial(ctx context.Context, id int32) (TrialRegistration, error) {
	row := q.db.QueryRow(ctx, lockAdministrativeTrial, id)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
		&i.Revision,
	)
	return i, err
}

const recentAdministrativePersons = `-- name: RecentAdministrativePersons :many
SELECT id,first_name,last_name FROM persons WHERE archived_at IS NULL ORDER BY created_at DESC,id DESC LIMIT 8
`

type RecentAdministrativePersonsRow struct {
	ID        int32
	FirstName string
	LastName  string
}

func (q *Queries) RecentAdministrativePersons(ctx context.Context) ([]RecentAdministrativePersonsRow, error) {
	rows, err := q.db.Query(ctx, recentAdministrativePersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentAdministrativePersonsRow
	for rows.Next() {
		var i RecentAdministrativePersonsRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAdministrativePersons = `-- name: SearchAdministrativePersons :many
SELECT id,first_name,last_name,birth_date,email,phone_number,address,created_at
FROM persons WHERE archived_at IS NULL AND
 ($1::text='' OR position(lower($1) in lower(first_name||' '||last_name||' '||coalesce(email,'')||' '||coalesce(phone_number,'')))>0
 OR ($2::text<>'' AND position($2 in regexp_replace(coalesce(phone_number,''),'[^0-9]','','g'))>0))
ORDER BY last_name,first_name,id LIMIT 51 OFFSET $3
`

type SearchAdministrativePersonsParams struct {
	Search     string
	Phone      string
	PageOffset int32
}

type SearchAdministrativePersonsRow struct {
	ID          int32
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	Email       pgtype.Text
	PhoneNumber pgtype.Text
	Address     pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) SearchAdministrativePersons(ctx context.Context, arg SearchAdministrativePersonsParams) ([]SearchAdministrativePersonsRow, error) {
	rows, err := q.db.Query(ctx, searchAdministrativePersons, arg.Search, arg.Phone, arg.PageOffset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAdministrativePersonsRow
	for rows.Next() {
		var i SearchAdministrativePersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Email,
			&i.PhoneNumber,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdministrativeMembershipNotes = `-- name: UpdateAdministrativeMembershipNotes :exec
UPDATE memberships SET admin_note=$2,updated_at=clock_timestamp() WHERE id=$1
`

type UpdateAdministrativeMembershipNotesParams struct {
	ID        int32
	AdminNote pgtype.Text
}

func (q *Queries) UpdateAdministrativeMembershipNotes(ctx context.Context, arg UpdateAdministrativeMembershipNotesParams) error {
	_, err := q.db.Exec(ctx, updateAdministrativeMembershipNotes, arg.ID, arg.AdminNote)
	return err
}

const updateAdministrativePersonNotes = `-- name: UpdateAdministrativePersonNotes :exec
UPDATE persons SET notes=$2,updated_at=clock_timestamp() WHERE id=$1
`

type UpdateAdministrativePersonNotesParams struct {
	ID    int32
	Notes pgtype.Text
}

func (q *Queries) UpdateAdministrativePersonNotes(ctx context.Context, arg UpdateAdministrativePersonNotesParams) error {
	_, err := q.db.Exec(ctx, updateAdministrativePersonNotes, arg.ID, arg.Notes)
	return err
}
