// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: child_registration.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const confirmChildRegistrationGuardian = `-- name: ConfirmChildRegistrationGuardian :exec
UPDATE child_registration_applications SET guardian_confirmed_at=strftime('%Y-%m-%d %H:%M:%f','now'),guardian_confirmed_by_user_id=?1 WHERE application_id=?2 AND guardian_confirmed_at IS NULL
`

type ConfirmChildRegistrationGuardianParams struct {
	GuardianConfirmedByUserID sql.NullInt32
	ApplicationID             int32
}

func (q *Queries) ConfirmChildRegistrationGuardian(ctx context.Context, arg ConfirmChildRegistrationGuardianParams) error {
	_, err := q.db.ExecContext(ctx, confirmChildRegistrationGuardian, arg.GuardianConfirmedByUserID, arg.ApplicationID)
	return err
}

const createChildRegistrationApplication = `-- name: CreateChildRegistrationApplication :exec
INSERT INTO child_registration_applications(application_id,guardian_claim_id,relationship_type,emergency_contact_requested) VALUES(?1,?2,?3,?4)
`

type CreateChildRegistrationApplicationParams struct {
	ApplicationID             int32
	GuardianClaimID           int32
	RelationshipType          string
	EmergencyContactRequested bool
}

func (q *Queries) CreateChildRegistrationApplication(ctx context.Context, arg CreateChildRegistrationApplicationParams) error {
	_, err := q.db.ExecContext(ctx, createChildRegistrationApplication,
		arg.ApplicationID,
		arg.GuardianClaimID,
		arg.RelationshipType,
		arg.EmergencyContactRequested,
	)
	return err
}

const createGuardianIdentityCandidate = `-- name: CreateGuardianIdentityCandidate :exec
INSERT INTO guardian_identity_claim_candidates(guardian_claim_id,person_id,confidence,matched_name,matched_birth_date,matched_email,matched_phone) VALUES(?1,?2,?3,?4,?5,?6,?7)
`

type CreateGuardianIdentityCandidateParams struct {
	GuardianClaimID  int32
	PersonID         int32
	Confidence       string
	MatchedName      bool
	MatchedBirthDate bool
	MatchedEmail     bool
	MatchedPhone     bool
}

func (q *Queries) CreateGuardianIdentityCandidate(ctx context.Context, arg CreateGuardianIdentityCandidateParams) error {
	_, err := q.db.ExecContext(ctx, createGuardianIdentityCandidate,
		arg.GuardianClaimID,
		arg.PersonID,
		arg.Confidence,
		arg.MatchedName,
		arg.MatchedBirthDate,
		arg.MatchedEmail,
		arg.MatchedPhone,
	)
	return err
}

const createGuardianIdentityClaim = `-- name: CreateGuardianIdentityClaim :one
INSERT INTO guardian_identity_claims(first_name,last_name,birth_date,email,phone_number,address) VALUES(?1,?2,?3,?4,?5,?6) RETURNING id, status, first_name, last_name, birth_date, email, phone_number, address, resolved_person_id, resolution_type, resolved_at, resolved_by_user_id, created_at, updated_at
`

type CreateGuardianIdentityClaimParams struct {
	FirstName   string
	LastName    string
	BirthDate   dbtypes.Date
	Email       string
	PhoneNumber sql.NullString
	Address     sql.NullString
}

func (q *Queries) CreateGuardianIdentityClaim(ctx context.Context, arg CreateGuardianIdentityClaimParams) (GuardianIdentityClaim, error) {
	row := q.db.QueryRowContext(ctx, createGuardianIdentityClaim,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Email,
		arg.PhoneNumber,
		arg.Address,
	)
	var i GuardianIdentityClaim
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.ResolvedPersonID,
		&i.ResolutionType,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildRegistrationApplication = `-- name: GetChildRegistrationApplication :one
SELECT application_id, guardian_claim_id, relationship_type, emergency_contact_requested, guardian_confirmed_at, guardian_confirmed_by_user_id, created_at FROM child_registration_applications WHERE application_id=?1
`

func (q *Queries) GetChildRegistrationApplication(ctx context.Context, applicationID int32) (ChildRegistrationApplication, error) {
	row := q.db.QueryRowContext(ctx, getChildRegistrationApplication, applicationID)
	var i ChildRegistrationApplication
	err := row.Scan(
		&i.ApplicationID,
		&i.GuardianClaimID,
		&i.RelationshipType,
		&i.EmergencyContactRequested,
		&i.GuardianConfirmedAt,
		&i.GuardianConfirmedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getGuardianIdentityClaim = `-- name: GetGuardianIdentityClaim :one
SELECT id, status, first_name, last_name, birth_date, email, phone_number, address, resolved_person_id, resolution_type, resolved_at, resolved_by_user_id, created_at, updated_at FROM guardian_identity_claims WHERE id=?1
`

func (q *Queries) GetGuardianIdentityClaim(ctx context.Context, id int32) (GuardianIdentityClaim, error) {
	row := q.db.QueryRowContext(ctx, getGuardianIdentityClaim, id)
	var i GuardianIdentityClaim
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.ResolvedPersonID,
		&i.ResolutionType,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuardianIdentityCandidates = `-- name: ListGuardianIdentityCandidates :many
SELECT c.guardian_claim_id, c.person_id, c.confidence, c.matched_name, c.matched_birth_date, c.matched_email, c.matched_phone, c.detected_at,p.first_name,p.last_name,p.birth_date,p.email,p.phone_number,p.address,p.archived_at
FROM guardian_identity_claim_candidates c JOIN persons p ON p.id=c.person_id WHERE c.guardian_claim_id=?1 ORDER BY p.id
`

type ListGuardianIdentityCandidatesRow struct {
	GuardianClaimID  int32
	PersonID         int32
	Confidence       string
	MatchedName      bool
	MatchedBirthDate bool
	MatchedEmail     bool
	MatchedPhone     bool
	DetectedAt       dbtypes.Timestamp
	FirstName        string
	LastName         string
	BirthDate        dbtypes.Date
	Email            sql.NullString
	PhoneNumber      sql.NullString
	Address          sql.NullString
	ArchivedAt       dbtypes.Timestamp
}

func (q *Queries) ListGuardianIdentityCandidates(ctx context.Context, guardianClaimID int32) ([]ListGuardianIdentityCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuardianIdentityCandidates, guardianClaimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuardianIdentityCandidatesRow
	for rows.Next() {
		var i ListGuardianIdentityCandidatesRow
		if err := rows.Scan(
			&i.GuardianClaimID,
			&i.PersonID,
			&i.Confidence,
			&i.MatchedName,
			&i.MatchedBirthDate,
			&i.MatchedEmail,
			&i.MatchedPhone,
			&i.DetectedAt,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Email,
			&i.PhoneNumber,
			&i.Address,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGuardianIdentityClaim = `-- name: LockGuardianIdentityClaim :one
SELECT id, status, first_name, last_name, birth_date, email, phone_number, address, resolved_person_id, resolution_type, resolved_at, resolved_by_user_id, created_at, updated_at FROM guardian_identity_claims WHERE id=?1
`

func (q *Queries) LockGuardianIdentityClaim(ctx context.Context, id int32) (GuardianIdentityClaim, error) {
	row := q.db.QueryRowContext(ctx, lockGuardianIdentityClaim, id)
	var i GuardianIdentityClaim
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.ResolvedPersonID,
		&i.ResolutionType,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGuardianIdentityReview = `-- name: MarkGuardianIdentityReview :exec
UPDATE guardian_identity_claims SET status='awaiting_review',updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?1 AND status='received'
`

func (q *Queries) MarkGuardianIdentityReview(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markGuardianIdentityReview, id)
	return err
}

const resolveGuardianIdentityClaim = `-- name: ResolveGuardianIdentityClaim :exec
UPDATE guardian_identity_claims SET status='resolved',resolved_person_id=?1,resolution_type=?2,resolved_by_user_id=?3,resolved_at=strftime('%Y-%m-%d %H:%M:%f','now'),updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?4 AND status IN ('received','awaiting_review')
`

type ResolveGuardianIdentityClaimParams struct {
	ResolvedPersonID sql.NullInt32
	ResolutionType   sql.NullString
	ResolvedByUserID sql.NullInt32
	ID               int32
}

func (q *Queries) ResolveGuardianIdentityClaim(ctx context.Context, arg ResolveGuardianIdentityClaimParams) error {
	_, err := q.db.ExecContext(ctx, resolveGuardianIdentityClaim,
		arg.ResolvedPersonID,
		arg.ResolutionType,
		arg.ResolvedByUserID,
		arg.ID,
	)
	return err
}
