// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consent_definitions.sql

package dbsqlc

import (
	"context"
)

const createConsentDefinition = `-- name: CreateConsentDefinition :one
INSERT INTO consent_definitions(code, version, title, description, is_active)
VALUES ($1, $2, $3, $4, $5) RETURNING id, code, version, title, description, is_active, created_at
`

type CreateConsentDefinitionParams struct {
	Code        string
	Version     int32
	Title       string
	Description string
	IsActive    bool
}

func (q *Queries) CreateConsentDefinition(ctx context.Context, arg CreateConsentDefinitionParams) (ConsentDefinition, error) {
	row := q.db.QueryRow(ctx, createConsentDefinition,
		arg.Code,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.IsActive,
	)
	var i ConsentDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateConsentDefinition = `-- name: DeactivateConsentDefinition :one
UPDATE consent_definitions SET is_active = FALSE WHERE id = $1 RETURNING id, code, version, title, description, is_active, created_at
`

func (q *Queries) DeactivateConsentDefinition(ctx context.Context, id int32) (ConsentDefinition, error) {
	row := q.db.QueryRow(ctx, deactivateConsentDefinition, id)
	var i ConsentDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getConsentDefinition = `-- name: GetConsentDefinition :one
SELECT id, code, version, title, description, is_active, created_at FROM consent_definitions WHERE id = $1
`

func (q *Queries) GetConsentDefinition(ctx context.Context, id int32) (ConsentDefinition, error) {
	row := q.db.QueryRow(ctx, getConsentDefinition, id)
	var i ConsentDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveConsentDefinitions = `-- name: ListActiveConsentDefinitions :many
SELECT id, code, version, title, description, is_active, created_at FROM consent_definitions WHERE is_active ORDER BY code, version
`

func (q *Queries) ListActiveConsentDefinitions(ctx context.Context) ([]ConsentDefinition, error) {
	rows, err := q.db.Query(ctx, listActiveConsentDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentDefinition
	for rows.Next() {
		var i ConsentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentDefinitions = `-- name: ListConsentDefinitions :many
SELECT id, code, version, title, description, is_active, created_at FROM consent_definitions ORDER BY code, version
`

func (q *Queries) ListConsentDefinitions(ctx context.Context) ([]ConsentDefinition, error) {
	rows, err := q.db.Query(ctx, listConsentDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentDefinition
	for rows.Next() {
		var i ConsentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
