// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package dbsqlc

import (
	"context"
)

const getDashboardPerson = `-- name: GetDashboardPerson :one
SELECT p.id,p.first_name,p.last_name FROM persons p JOIN users u ON u.person_id=p.id WHERE u.id=$1
`

type GetDashboardPersonRow struct {
	ID        int32
	FirstName string
	LastName  string
}

// Read-only dashboard projections: no administrative dossier or credentials.
func (q *Queries) GetDashboardPerson(ctx context.Context, id int32) (GetDashboardPersonRow, error) {
	row := q.db.QueryRow(ctx, getDashboardPerson, id)
	var i GetDashboardPersonRow
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}

const listDashboardMemberships = `-- name: ListDashboardMemberships :many
SELECT m.id,m.status,s.name AS season_name,t.name AS membership_type_name,
 ARRAY(SELECT a.name FROM activities a JOIN membership_activities ma ON ma.activity_id=a.id WHERE ma.membership_id=m.id ORDER BY a.name)::text[] AS activities
FROM memberships m JOIN seasons s ON s.id=m.season_id JOIN membership_types t ON t.id=m.membership_type_id
WHERE m.person_id=$1 ORDER BY s.starts_at DESC,m.id DESC
`

type ListDashboardMembershipsRow struct {
	ID                 int32
	Status             string
	SeasonName         string
	MembershipTypeName string
	Activities         []string
}

func (q *Queries) ListDashboardMemberships(ctx context.Context, personID int32) ([]ListDashboardMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardMemberships, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardMembershipsRow
	for rows.Next() {
		var i ListDashboardMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SeasonName,
			&i.MembershipTypeName,
			&i.Activities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
