// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_slots.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeGroupSlot = `-- name: CloseGroupSlot :one
UPDATE group_slots SET valid_until = $2::date, updated_at = NOW()
WHERE id = $1 RETURNING id, group_id, season_id, weekday, start_time, end_time, location, valid_from, valid_until, is_active, created_at, updated_at
`

type CloseGroupSlotParams struct {
	ID         int32
	ValidUntil pgtype.Date
}

func (q *Queries) CloseGroupSlot(ctx context.Context, arg CloseGroupSlotParams) (GroupSlot, error) {
	row := q.db.QueryRow(ctx, closeGroupSlot, arg.ID, arg.ValidUntil)
	var i GroupSlot
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupSlot = `-- name: CreateGroupSlot :one
INSERT INTO group_slots (group_id, season_id, weekday, start_time, end_time, location, valid_from, valid_until, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, group_id, season_id, weekday, start_time, end_time, location, valid_from, valid_until, is_active, created_at, updated_at
`

type CreateGroupSlotParams struct {
	GroupID    int32
	SeasonID   int32
	Weekday    int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Location   pgtype.Text
	ValidFrom  pgtype.Date
	ValidUntil pgtype.Date
	IsActive   bool
}

func (q *Queries) CreateGroupSlot(ctx context.Context, arg CreateGroupSlotParams) (GroupSlot, error) {
	row := q.db.QueryRow(ctx, createGroupSlot,
		arg.GroupID,
		arg.SeasonID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.IsActive,
	)
	var i GroupSlot
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateGroupSlot = `-- name: DeactivateGroupSlot :one
UPDATE group_slots SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 RETURNING id, group_id, season_id, weekday, start_time, end_time, location, valid_from, valid_until, is_active, created_at, updated_at
`

func (q *Queries) DeactivateGroupSlot(ctx context.Context, id int32) (GroupSlot, error) {
	row := q.db.QueryRow(ctx, deactivateGroupSlot, id)
	var i GroupSlot
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrentGroupSlots = `-- name: ListCurrentGroupSlots :many
SELECT gs.id, gs.group_id, gs.season_id, gs.weekday, gs.start_time, gs.end_time, gs.location, gs.valid_from, gs.valid_until, gs.is_active, gs.created_at, gs.updated_at, g.name AS group_name, s.name AS season_name
FROM group_slots gs
JOIN groups g ON g.id = gs.group_id
JOIN seasons s ON s.id = gs.season_id
WHERE gs.group_id = $1 AND gs.season_id = $2
  AND gs.is_active AND gs.valid_from <= CURRENT_DATE
  AND (gs.valid_until IS NULL OR gs.valid_until >= CURRENT_DATE)
ORDER BY gs.weekday, gs.start_time, gs.valid_from, gs.id
`

type ListCurrentGroupSlotsParams struct {
	GroupID  int32
	SeasonID int32
}

type ListCurrentGroupSlotsRow struct {
	ID         int32
	GroupID    int32
	SeasonID   int32
	Weekday    int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Location   pgtype.Text
	ValidFrom  pgtype.Date
	ValidUntil pgtype.Date
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	GroupName  string
	SeasonName string
}

func (q *Queries) ListCurrentGroupSlots(ctx context.Context, arg ListCurrentGroupSlotsParams) ([]ListCurrentGroupSlotsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentGroupSlots, arg.GroupID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentGroupSlotsRow
	for rows.Next() {
		var i ListCurrentGroupSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SeasonID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
			&i.SeasonName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSlots = `-- name: ListGroupSlots :many
SELECT gs.id, gs.group_id, gs.season_id, gs.weekday, gs.start_time, gs.end_time, gs.location, gs.valid_from, gs.valid_until, gs.is_active, gs.created_at, gs.updated_at, g.name AS group_name, s.name AS season_name
FROM group_slots gs
JOIN groups g ON g.id = gs.group_id
JOIN seasons s ON s.id = gs.season_id
WHERE gs.group_id = $1
ORDER BY gs.weekday, gs.start_time, gs.valid_from, gs.id
`

type ListGroupSlotsRow struct {
	ID         int32
	GroupID    int32
	SeasonID   int32
	Weekday    int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Location   pgtype.Text
	ValidFrom  pgtype.Date
	ValidUntil pgtype.Date
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	GroupName  string
	SeasonName string
}

func (q *Queries) ListGroupSlots(ctx context.Context, groupID int32) ([]ListGroupSlotsRow, error) {
	rows, err := q.db.Query(ctx, listGroupSlots, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupSlotsRow
	for rows.Next() {
		var i ListGroupSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SeasonID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
			&i.SeasonName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSlotsForSeason = `-- name: ListGroupSlotsForSeason :many
SELECT gs.id, gs.group_id, gs.season_id, gs.weekday, gs.start_time, gs.end_time, gs.location, gs.valid_from, gs.valid_until, gs.is_active, gs.created_at, gs.updated_at, g.name AS group_name, s.name AS season_name
FROM group_slots gs
JOIN groups g ON g.id = gs.group_id
JOIN seasons s ON s.id = gs.season_id
WHERE gs.group_id = $1 AND gs.season_id = $2
ORDER BY gs.weekday, gs.start_time, gs.valid_from, gs.id
`

type ListGroupSlotsForSeasonParams struct {
	GroupID  int32
	SeasonID int32
}

type ListGroupSlotsForSeasonRow struct {
	ID         int32
	GroupID    int32
	SeasonID   int32
	Weekday    int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Location   pgtype.Text
	ValidFrom  pgtype.Date
	ValidUntil pgtype.Date
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	GroupName  string
	SeasonName string
}

func (q *Queries) ListGroupSlotsForSeason(ctx context.Context, arg ListGroupSlotsForSeasonParams) ([]ListGroupSlotsForSeasonRow, error) {
	rows, err := q.db.Query(ctx, listGroupSlotsForSeason, arg.GroupID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupSlotsForSeasonRow
	for rows.Next() {
		var i ListGroupSlotsForSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SeasonID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
			&i.SeasonName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupSlot = `-- name: UpdateGroupSlot :one
UPDATE group_slots
SET weekday = $2, start_time = $3, end_time = $4, location = $5,
    valid_from = $6, valid_until = $7, is_active = $8, updated_at = NOW()
WHERE id = $1 RETURNING id, group_id, season_id, weekday, start_time, end_time, location, valid_from, valid_until, is_active, created_at, updated_at
`

type UpdateGroupSlotParams struct {
	ID         int32
	Weekday    int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	Location   pgtype.Text
	ValidFrom  pgtype.Date
	ValidUntil pgtype.Date
	IsActive   bool
}

func (q *Queries) UpdateGroupSlot(ctx context.Context, arg UpdateGroupSlotParams) (GroupSlot, error) {
	row := q.db.QueryRow(ctx, updateGroupSlot,
		arg.ID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.IsActive,
	)
	var i GroupSlot
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
