// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (activity_id, name, description, is_active)
VALUES ($1, $2, $3, $4) RETURNING id, activity_id, name, description, is_active, created_at, updated_at
`

type CreateGroupParams struct {
	ActivityID  int32
	Name        string
	Description pgtype.Text
	IsActive    bool
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ActivityID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT g.id, g.activity_id, g.name, g.description, g.is_active, g.created_at, g.updated_at, a.name AS activity_name
FROM groups g JOIN activities a ON a.id = g.activity_id
WHERE g.id = $1
`

type GetGroupRow struct {
	ID           int32
	ActivityID   int32
	Name         string
	Description  pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ActivityName string
}

func (q *Queries) GetGroup(ctx context.Context, id int32) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivityName,
	)
	return i, err
}

const listActiveGroups = `-- name: ListActiveGroups :many
SELECT g.id, g.activity_id, g.name, g.description, g.is_active, g.created_at, g.updated_at, a.name AS activity_name
FROM groups g JOIN activities a ON a.id = g.activity_id
WHERE g.is_active
ORDER BY a.name, g.name, g.id
`

type ListActiveGroupsRow struct {
	ID           int32
	ActivityID   int32
	Name         string
	Description  pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ActivityName string
}

func (q *Queries) ListActiveGroups(ctx context.Context) ([]ListActiveGroupsRow, error) {
	rows, err := q.db.Query(ctx, listActiveGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveGroupsRow
	for rows.Next() {
		var i ListActiveGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.activity_id, g.name, g.description, g.is_active, g.created_at, g.updated_at, a.name AS activity_name
FROM groups g JOIN activities a ON a.id = g.activity_id
ORDER BY a.name, g.name, g.id
`

type ListGroupsRow struct {
	ID           int32
	ActivityID   int32
	Name         string
	Description  pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ActivityName string
}

func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET name = $2, description = $3, is_active = $4, updated_at = NOW()
WHERE id = $1 RETURNING id, activity_id, name, description, is_active, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          int32
	Name        string
	Description pgtype.Text
	IsActive    bool
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
