// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_corrections.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const applyIdentityCorrection = `-- name: ApplyIdentityCorrection :execrows
UPDATE persons SET first_name=?1,last_name=?2,birth_date=?3,updated_at=strftime('%Y-%m-%d %H:%M:%f','now')
WHERE id=?4 AND archived_at IS NULL
`

type ApplyIdentityCorrectionParams struct {
	FirstName string
	LastName  string
	BirthDate dbtypes.Date
	ID        int32
}

func (q *Queries) ApplyIdentityCorrection(ctx context.Context, arg ApplyIdentityCorrectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyIdentityCorrection,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPendingIdentityCorrections = `-- name: CountPendingIdentityCorrections :one
SELECT CAST(count(*) AS BIGINT) FROM identity_correction_requests WHERE status='pending'
`

func (q *Queries) CountPendingIdentityCorrections(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingIdentityCorrections)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createIdentityCorrection = `-- name: CreateIdentityCorrection :one
INSERT INTO identity_correction_requests(person_id,requesting_user_id,original_first_name,original_last_name,original_birth_date,proposed_first_name,proposed_last_name,proposed_birth_date)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8) RETURNING id
`

type CreateIdentityCorrectionParams struct {
	PersonID          int32
	RequestingUserID  int32
	OriginalFirstName string
	OriginalLastName  string
	OriginalBirthDate dbtypes.Date
	ProposedFirstName string
	ProposedLastName  string
	ProposedBirthDate dbtypes.Date
}

func (q *Queries) CreateIdentityCorrection(ctx context.Context, arg CreateIdentityCorrectionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createIdentityCorrection,
		arg.PersonID,
		arg.RequestingUserID,
		arg.OriginalFirstName,
		arg.OriginalLastName,
		arg.OriginalBirthDate,
		arg.ProposedFirstName,
		arg.ProposedLastName,
		arg.ProposedBirthDate,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getIdentityCorrection = `-- name: GetIdentityCorrection :one
SELECT c.id, c.person_id, c.requesting_user_id, c.original_first_name, c.original_last_name, c.original_birth_date, c.proposed_first_name, c.proposed_last_name, c.proposed_birth_date, c.status, c.created_at, c.reviewed_at, c.reviewed_by_user_id,p.first_name,p.last_name,p.birth_date,p.archived_at,u.username FROM identity_correction_requests c
JOIN persons p ON p.id=c.person_id JOIN users u ON u.id=c.requesting_user_id WHERE c.id=?1
`

type GetIdentityCorrectionRow struct {
	ID                int32
	PersonID          int32
	RequestingUserID  int32
	OriginalFirstName string
	OriginalLastName  string
	OriginalBirthDate dbtypes.Date
	ProposedFirstName string
	ProposedLastName  string
	ProposedBirthDate dbtypes.Date
	Status            string
	CreatedAt         dbtypes.Timestamp
	ReviewedAt        dbtypes.Timestamp
	ReviewedByUserID  sql.NullInt32
	FirstName         string
	LastName          string
	BirthDate         dbtypes.Date
	ArchivedAt        dbtypes.Timestamp
	Username          string
}

func (q *Queries) GetIdentityCorrection(ctx context.Context, id int32) (GetIdentityCorrectionRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentityCorrection, id)
	var i GetIdentityCorrectionRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.RequestingUserID,
		&i.OriginalFirstName,
		&i.OriginalLastName,
		&i.OriginalBirthDate,
		&i.ProposedFirstName,
		&i.ProposedLastName,
		&i.ProposedBirthDate,
		&i.Status,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedByUserID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.ArchivedAt,
		&i.Username,
	)
	return i, err
}

const listIdentityCorrections = `-- name: ListIdentityCorrections :many
SELECT c.id, c.person_id, c.requesting_user_id, c.original_first_name, c.original_last_name, c.original_birth_date, c.proposed_first_name, c.proposed_last_name, c.proposed_birth_date, c.status, c.created_at, c.reviewed_at, c.reviewed_by_user_id,p.first_name,p.last_name,u.username FROM identity_correction_requests c
JOIN persons p ON p.id=c.person_id JOIN users u ON u.id=c.requesting_user_id
ORDER BY (c.status='pending') DESC,c.created_at DESC,c.id DESC
`

type ListIdentityCorrectionsRow struct {
	ID                int32
	PersonID          int32
	RequestingUserID  int32
	OriginalFirstName string
	OriginalLastName  string
	OriginalBirthDate dbtypes.Date
	ProposedFirstName string
	ProposedLastName  string
	ProposedBirthDate dbtypes.Date
	Status            string
	CreatedAt         dbtypes.Timestamp
	ReviewedAt        dbtypes.Timestamp
	ReviewedByUserID  sql.NullInt32
	FirstName         string
	LastName          string
	Username          string
}

func (q *Queries) ListIdentityCorrections(ctx context.Context) ([]ListIdentityCorrectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIdentityCorrections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityCorrectionsRow
	for rows.Next() {
		var i ListIdentityCorrectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.RequestingUserID,
			&i.OriginalFirstName,
			&i.OriginalLastName,
			&i.OriginalBirthDate,
			&i.ProposedFirstName,
			&i.ProposedLastName,
			&i.ProposedBirthDate,
			&i.Status,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.ReviewedByUserID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewIdentityCorrection = `-- name: ReviewIdentityCorrection :execrows
UPDATE identity_correction_requests SET status=?1,reviewed_at=strftime('%Y-%m-%d %H:%M:%f','now'),reviewed_by_user_id=?2
WHERE id=?3 AND status='pending'
`

type ReviewIdentityCorrectionParams struct {
	Status           string
	ReviewedByUserID sql.NullInt32
	ID               int32
}

func (q *Queries) ReviewIdentityCorrection(ctx context.Context, arg ReviewIdentityCorrectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reviewIdentityCorrection, arg.Status, arg.ReviewedByUserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
