// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership_type_groups.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const listMembershipTypeGroups = `-- name: ListMembershipTypeGroups :many
SELECT membership_type_id,group_id FROM membership_type_groups ORDER BY membership_type_id,group_id
`

func (q *Queries) ListMembershipTypeGroups(ctx context.Context) ([]MembershipTypeGroup, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipTypeGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MembershipTypeGroup
	for rows.Next() {
		var i MembershipTypeGroup
		if err := rows.Scan(&i.MembershipTypeID, &i.GroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipGroupCompatible = `-- name: MembershipGroupCompatible :one
SELECT EXISTS(SELECT 1 FROM memberships m JOIN membership_type_groups c ON c.membership_type_id=m.membership_type_id
WHERE m.id=?1 AND c.group_id=?2)
`

type MembershipGroupCompatibleParams struct {
	MembershipID int32
	GroupID      int32
}

func (q *Queries) MembershipGroupCompatible(ctx context.Context, arg MembershipGroupCompatibleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, membershipGroupCompatible, arg.MembershipID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSelfServiceProfile = `-- name: UpdateSelfServiceProfile :exec
UPDATE persons SET first_name=?1,last_name=?2,
phone_number=?3,address=?4,updated_at=strftime('%Y-%m-%d %H:%M:%f','now')
WHERE id=?5 AND archived_at IS NULL
`

type UpdateSelfServiceProfileParams struct {
	FirstName   string
	LastName    string
	PhoneNumber sql.NullString
	Address     sql.NullString
	ID          int32
}

func (q *Queries) UpdateSelfServiceProfile(ctx context.Context, arg UpdateSelfServiceProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateSelfServiceProfile,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Address,
		arg.ID,
	)
	return err
}
