// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership_groups.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignMembershipGroup = `-- name: AssignMembershipGroup :one
INSERT INTO membership_groups (membership_id, group_id, joined_at)
VALUES ($1, $2, $3) RETURNING id, membership_id, group_id, joined_at, left_at, created_at
`

type AssignMembershipGroupParams struct {
	MembershipID int32
	GroupID      int32
	JoinedAt     pgtype.Date
}

func (q *Queries) AssignMembershipGroup(ctx context.Context, arg AssignMembershipGroupParams) (MembershipGroup, error) {
	row := q.db.QueryRow(ctx, assignMembershipGroup, arg.MembershipID, arg.GroupID, arg.JoinedAt)
	var i MembershipGroup
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.GroupID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const closeMembershipGroup = `-- name: CloseMembershipGroup :one
UPDATE membership_groups SET left_at = $2::date
WHERE id = $1 RETURNING id, membership_id, group_id, joined_at, left_at, created_at
`

type CloseMembershipGroupParams struct {
	ID     int32
	LeftAt pgtype.Date
}

func (q *Queries) CloseMembershipGroup(ctx context.Context, arg CloseMembershipGroupParams) (MembershipGroup, error) {
	row := q.db.QueryRow(ctx, closeMembershipGroup, arg.ID, arg.LeftAt)
	var i MembershipGroup
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.GroupID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentGroupMembers = `-- name: ListCurrentGroupMembers :many
SELECT mg.id AS membership_group_id, m.id AS membership_id, m.season_id,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, mg.joined_at
FROM membership_groups mg
JOIN memberships m ON m.id = mg.membership_id
JOIN persons p ON p.id = m.person_id
WHERE mg.group_id = $1 AND m.season_id = $2
  AND m.status IN ('pending', 'active')
  AND mg.joined_at <= CURRENT_DATE
  AND (mg.left_at IS NULL OR mg.left_at > CURRENT_DATE)
ORDER BY p.last_name, p.first_name, mg.id
`

type ListCurrentGroupMembersParams struct {
	GroupID  int32
	SeasonID int32
}

type ListCurrentGroupMembersRow struct {
	MembershipGroupID int32
	MembershipID      int32
	SeasonID          int32
	PersonID          int32
	FirstName         string
	LastName          string
	BirthDate         pgtype.Date
	JoinedAt          pgtype.Date
}

func (q *Queries) ListCurrentGroupMembers(ctx context.Context, arg ListCurrentGroupMembersParams) ([]ListCurrentGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listCurrentGroupMembers, arg.GroupID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentGroupMembersRow
	for rows.Next() {
		var i ListCurrentGroupMembersRow
		if err := rows.Scan(
			&i.MembershipGroupID,
			&i.MembershipID,
			&i.SeasonID,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentMembershipGroups = `-- name: ListCurrentMembershipGroups :many
SELECT mg.id, mg.membership_id, mg.group_id, mg.joined_at, mg.left_at, mg.created_at, g.name AS group_name, g.is_active AS group_is_active,
       g.activity_id, a.name AS activity_name
FROM membership_groups mg
JOIN groups g ON g.id = mg.group_id
JOIN activities a ON a.id = g.activity_id
WHERE mg.membership_id = $1
  AND mg.joined_at <= CURRENT_DATE
  AND (mg.left_at IS NULL OR mg.left_at > CURRENT_DATE)
ORDER BY g.name, mg.id
`

type ListCurrentMembershipGroupsRow struct {
	ID            int32
	MembershipID  int32
	GroupID       int32
	JoinedAt      pgtype.Date
	LeftAt        pgtype.Date
	CreatedAt     pgtype.Timestamptz
	GroupName     string
	GroupIsActive bool
	ActivityID    int32
	ActivityName  string
}

func (q *Queries) ListCurrentMembershipGroups(ctx context.Context, membershipID int32) ([]ListCurrentMembershipGroupsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentMembershipGroups, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentMembershipGroupsRow
	for rows.Next() {
		var i ListCurrentMembershipGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.GroupID,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.GroupName,
			&i.GroupIsActive,
			&i.ActivityID,
			&i.ActivityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipGroupHistory = `-- name: ListMembershipGroupHistory :many
SELECT mg.id, mg.membership_id, mg.group_id, mg.joined_at, mg.left_at, mg.created_at, g.name AS group_name, g.is_active AS group_is_active,
       g.activity_id, a.name AS activity_name
FROM membership_groups mg
JOIN groups g ON g.id = mg.group_id
JOIN activities a ON a.id = g.activity_id
WHERE mg.membership_id = $1
ORDER BY mg.joined_at, mg.id
`

type ListMembershipGroupHistoryRow struct {
	ID            int32
	MembershipID  int32
	GroupID       int32
	JoinedAt      pgtype.Date
	LeftAt        pgtype.Date
	CreatedAt     pgtype.Timestamptz
	GroupName     string
	GroupIsActive bool
	ActivityID    int32
	ActivityName  string
}

func (q *Queries) ListMembershipGroupHistory(ctx context.Context, membershipID int32) ([]ListMembershipGroupHistoryRow, error) {
	rows, err := q.db.Query(ctx, listMembershipGroupHistory, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipGroupHistoryRow
	for rows.Next() {
		var i ListMembershipGroupHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.GroupID,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.GroupName,
			&i.GroupIsActive,
			&i.ActivityID,
			&i.ActivityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMembershipGroupAssignment = `-- name: LockMembershipGroupAssignment :one
SELECT id, membership_id, group_id, joined_at, left_at, created_at FROM membership_groups WHERE id=$1 AND membership_id=$2 FOR UPDATE
`

type LockMembershipGroupAssignmentParams struct {
	ID           int32
	MembershipID int32
}

func (q *Queries) LockMembershipGroupAssignment(ctx context.Context, arg LockMembershipGroupAssignmentParams) (MembershipGroup, error) {
	row := q.db.QueryRow(ctx, lockMembershipGroupAssignment, arg.ID, arg.MembershipID)
	var i MembershipGroup
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.GroupID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockMembershipGroupTarget = `-- name: LockMembershipGroupTarget :one
SELECT m.status,s.starts_at,s.ends_at FROM memberships m JOIN seasons s ON s.id=m.season_id WHERE m.id=$1 FOR UPDATE OF m
`

type LockMembershipGroupTargetRow struct {
	Status   string
	StartsAt pgtype.Date
	EndsAt   pgtype.Date
}

func (q *Queries) LockMembershipGroupTarget(ctx context.Context, id int32) (LockMembershipGroupTargetRow, error) {
	row := q.db.QueryRow(ctx, lockMembershipGroupTarget, id)
	var i LockMembershipGroupTargetRow
	err := row.Scan(&i.Status, &i.StartsAt, &i.EndsAt)
	return i, err
}

const membershipGroupOverlaps = `-- name: MembershipGroupOverlaps :one
SELECT EXISTS(SELECT 1 FROM membership_groups WHERE membership_id=$1 AND group_id=$2 AND (left_at IS NULL OR left_at>$3::date))::boolean
`

type MembershipGroupOverlapsParams struct {
	MembershipID int32
	GroupID      int32
	JoinedAt     pgtype.Date
}

func (q *Queries) MembershipGroupOverlaps(ctx context.Context, arg MembershipGroupOverlapsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipGroupOverlaps, arg.MembershipID, arg.GroupID, arg.JoinedAt)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const membershipHasGroupActivity = `-- name: MembershipHasGroupActivity :one
SELECT EXISTS(SELECT 1 FROM membership_activities WHERE membership_id=$1 AND activity_id=$2)::boolean
`

type MembershipHasGroupActivityParams struct {
	MembershipID int32
	ActivityID   int32
}

func (q *Queries) MembershipHasGroupActivity(ctx context.Context, arg MembershipHasGroupActivityParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipHasGroupActivity, arg.MembershipID, arg.ActivityID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
