// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMembership = `-- name: GetMembership :one
SELECT id, person_id, season_id, membership_type_id, status, joined_at, ended_at, created_at, updated_at, requested_at, approved_at, approved_by_user_id, admin_note FROM memberships WHERE id = $1
`

func (q *Queries) GetMembership(ctx context.Context, id int32) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.SeasonID,
		&i.MembershipTypeID,
		&i.Status,
		&i.JoinedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.AdminNote,
	)
	return i, err
}

const getMembershipDetails = `-- name: GetMembershipDetails :one
SELECT m.id, m.person_id, m.season_id, m.membership_type_id, m.status, m.joined_at, m.ended_at, m.created_at, m.updated_at, m.requested_at, m.approved_at, m.approved_by_user_id, m.admin_note, p.id, p.first_name, p.last_name, p.birth_date, p.phone_number, p.email, p.address, p.created_at, p.archived_at, p.notes, s.id, s.name, s.starts_at, s.ends_at, s.is_active, s.created_at, t.id, t.name, t.is_active, t.created_at,
       u.id AS user_id, u.username, u.is_active AS user_is_active, u.activated_at,
       approver.username AS approver_username
FROM memberships m
JOIN persons p ON p.id = m.person_id
JOIN seasons s ON s.id = m.season_id
JOIN membership_types t ON t.id = m.membership_type_id
LEFT JOIN users u ON u.person_id = p.id
LEFT JOIN users approver ON approver.id = m.approved_by_user_id
WHERE m.id = $1
`

type GetMembershipDetailsRow struct {
	Membership       Membership
	Person           Person
	Season           Season
	MembershipType   MembershipType
	UserID           pgtype.Int4
	Username         pgtype.Text
	UserIsActive     pgtype.Bool
	ActivatedAt      pgtype.Timestamptz
	ApproverUsername pgtype.Text
}

func (q *Queries) GetMembershipDetails(ctx context.Context, id int32) (GetMembershipDetailsRow, error) {
	row := q.db.QueryRow(ctx, getMembershipDetails, id)
	var i GetMembershipDetailsRow
	err := row.Scan(
		&i.Membership.ID,
		&i.Membership.PersonID,
		&i.Membership.SeasonID,
		&i.Membership.MembershipTypeID,
		&i.Membership.Status,
		&i.Membership.JoinedAt,
		&i.Membership.EndedAt,
		&i.Membership.CreatedAt,
		&i.Membership.UpdatedAt,
		&i.Membership.RequestedAt,
		&i.Membership.ApprovedAt,
		&i.Membership.ApprovedByUserID,
		&i.Membership.AdminNote,
		&i.Person.ID,
		&i.Person.FirstName,
		&i.Person.LastName,
		&i.Person.BirthDate,
		&i.Person.PhoneNumber,
		&i.Person.Email,
		&i.Person.Address,
		&i.Person.CreatedAt,
		&i.Person.ArchivedAt,
		&i.Person.Notes,
		&i.Season.ID,
		&i.Season.Name,
		&i.Season.StartsAt,
		&i.Season.EndsAt,
		&i.Season.IsActive,
		&i.Season.CreatedAt,
		&i.MembershipType.ID,
		&i.MembershipType.Name,
		&i.MembershipType.IsActive,
		&i.MembershipType.CreatedAt,
		&i.UserID,
		&i.Username,
		&i.UserIsActive,
		&i.ActivatedAt,
		&i.ApproverUsername,
	)
	return i, err
}

const getUserByPerson = `-- name: GetUserByPerson :one
SELECT id, person_id, login_email, password_hash, is_active, created_at, username, activated_at FROM users WHERE person_id = $1
`

func (q *Queries) GetUserByPerson(ctx context.Context, personID int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPerson, personID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.LoginEmail,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.Username,
		&i.ActivatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, person_id, login_email, password_hash, is_active, created_at, username, activated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.LoginEmail,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.Username,
		&i.ActivatedAt,
	)
	return i, err
}

const listMembershipActivities = `-- name: ListMembershipActivities :many
SELECT a.id, a.name, a.is_active, a.created_at FROM activities a JOIN membership_activities ma ON ma.activity_id = a.id
WHERE ma.membership_id = $1 ORDER BY a.name, a.id
`

func (q *Queries) ListMembershipActivities(ctx context.Context, membershipID int32) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listMembershipActivities, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipConsentRequirements = `-- name: ListMembershipConsentRequirements :many
SELECT r.presented_at, d.id, d.code, d.version, d.title, d.description, d.is_active, d.created_at, c.decision, c.given_by_person_id, c.recorded_at
FROM membership_consent_requirements r
JOIN consent_definitions d ON d.id = r.consent_definition_id
LEFT JOIN membership_consents c ON c.id = (
 SELECT mc.id FROM membership_consents mc
 WHERE mc.membership_id = r.membership_id AND mc.consent_definition_id = r.consent_definition_id
 ORDER BY mc.recorded_at DESC, mc.id DESC LIMIT 1
)
WHERE r.membership_id = $1 ORDER BY d.code, d.version
`

type ListMembershipConsentRequirementsRow struct {
	PresentedAt     pgtype.Timestamptz
	ID              int32
	Code            string
	Version         int32
	Title           string
	Description     string
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	Decision        pgtype.Text
	GivenByPersonID pgtype.Int4
	RecordedAt      pgtype.Timestamptz
}

func (q *Queries) ListMembershipConsentRequirements(ctx context.Context, membershipID int32) ([]ListMembershipConsentRequirementsRow, error) {
	rows, err := q.db.Query(ctx, listMembershipConsentRequirements, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipConsentRequirementsRow
	for rows.Next() {
		var i ListMembershipConsentRequirementsRow
		if err := rows.Scan(
			&i.PresentedAt,
			&i.ID,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.Decision,
			&i.GivenByPersonID,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
