// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership_consents.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembershipConsent = `-- name: CreateMembershipConsent :one
INSERT INTO membership_consents(membership_id, consent_definition_id, decision, given_by_person_id)
VALUES ($1, $2, $3, $4) RETURNING id, membership_id, consent_definition_id, decision, given_by_person_id, recorded_at
`

type CreateMembershipConsentParams struct {
	MembershipID        int32
	ConsentDefinitionID int32
	Decision            string
	GivenByPersonID     int32
}

// Writes must go through internal/consents.Service for transverse validation.
func (q *Queries) CreateMembershipConsent(ctx context.Context, arg CreateMembershipConsentParams) (MembershipConsent, error) {
	row := q.db.QueryRow(ctx, createMembershipConsent,
		arg.MembershipID,
		arg.ConsentDefinitionID,
		arg.Decision,
		arg.GivenByPersonID,
	)
	var i MembershipConsent
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.ConsentDefinitionID,
		&i.Decision,
		&i.GivenByPersonID,
		&i.RecordedAt,
	)
	return i, err
}

const getCurrentMembershipConsentDecision = `-- name: GetCurrentMembershipConsentDecision :one
SELECT decision FROM membership_consents
WHERE membership_id = $1 AND consent_definition_id = $2
ORDER BY recorded_at DESC, id DESC LIMIT 1
`

type GetCurrentMembershipConsentDecisionParams struct {
	MembershipID        int32
	ConsentDefinitionID int32
}

func (q *Queries) GetCurrentMembershipConsentDecision(ctx context.Context, arg GetCurrentMembershipConsentDecisionParams) (string, error) {
	row := q.db.QueryRow(ctx, getCurrentMembershipConsentDecision, arg.MembershipID, arg.ConsentDefinitionID)
	var decision string
	err := row.Scan(&decision)
	return decision, err
}

const listCurrentMembershipConsents = `-- name: ListCurrentMembershipConsents :many
SELECT m.id AS membership_id, d.id AS consent_definition_id, d.code, d.version,
       d.title, d.description, d.is_active AS definition_is_active,
       c.decision AS current_decision, c.recorded_at AS decision_recorded_at,
       p.id AS given_by_person_id, p.first_name AS given_by_first_name, p.last_name AS given_by_last_name
FROM memberships m CROSS JOIN consent_definitions d
LEFT JOIN membership_consents c ON c.id = (
    SELECT latest.id FROM membership_consents latest
    WHERE latest.membership_id = m.id AND latest.consent_definition_id = d.id
    ORDER BY latest.recorded_at DESC, latest.id DESC LIMIT 1
)
LEFT JOIN persons p ON p.id = c.given_by_person_id
WHERE m.id = $1 AND (d.is_active OR c.id IS NOT NULL)
ORDER BY d.code, d.version
`

type ListCurrentMembershipConsentsRow struct {
	MembershipID        int32
	ConsentDefinitionID int32
	Code                string
	Version             int32
	Title               string
	Description         string
	DefinitionIsActive  bool
	CurrentDecision     pgtype.Text
	DecisionRecordedAt  pgtype.Timestamptz
	GivenByPersonID     pgtype.Int4
	GivenByFirstName    pgtype.Text
	GivenByLastName     pgtype.Text
}

func (q *Queries) ListCurrentMembershipConsents(ctx context.Context, id int32) ([]ListCurrentMembershipConsentsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentMembershipConsents, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentMembershipConsentsRow
	for rows.Next() {
		var i ListCurrentMembershipConsentsRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.ConsentDefinitionID,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.DefinitionIsActive,
			&i.CurrentDecision,
			&i.DecisionRecordedAt,
			&i.GivenByPersonID,
			&i.GivenByFirstName,
			&i.GivenByLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipConsentHistory = `-- name: ListMembershipConsentHistory :many
SELECT c.id, c.membership_id, c.consent_definition_id, c.decision, c.given_by_person_id, c.recorded_at, d.code, d.version, d.title, d.description, d.is_active AS definition_is_active,
       p.first_name AS given_by_first_name, p.last_name AS given_by_last_name
FROM membership_consents c JOIN consent_definitions d ON d.id = c.consent_definition_id
JOIN persons p ON p.id = c.given_by_person_id
WHERE c.membership_id = $1 AND c.consent_definition_id = $2
ORDER BY c.recorded_at, c.id
`

type ListMembershipConsentHistoryParams struct {
	MembershipID        int32
	ConsentDefinitionID int32
}

type ListMembershipConsentHistoryRow struct {
	ID                  int32
	MembershipID        int32
	ConsentDefinitionID int32
	Decision            string
	GivenByPersonID     int32
	RecordedAt          pgtype.Timestamptz
	Code                string
	Version             int32
	Title               string
	Description         string
	DefinitionIsActive  bool
	GivenByFirstName    string
	GivenByLastName     string
}

func (q *Queries) ListMembershipConsentHistory(ctx context.Context, arg ListMembershipConsentHistoryParams) ([]ListMembershipConsentHistoryRow, error) {
	rows, err := q.db.Query(ctx, listMembershipConsentHistory, arg.MembershipID, arg.ConsentDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipConsentHistoryRow
	for rows.Next() {
		var i ListMembershipConsentHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.ConsentDefinitionID,
			&i.Decision,
			&i.GivenByPersonID,
			&i.RecordedAt,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.DefinitionIsActive,
			&i.GivenByFirstName,
			&i.GivenByLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipConsentsHistory = `-- name: ListMembershipConsentsHistory :many
SELECT c.id, c.membership_id, c.consent_definition_id, c.decision, c.given_by_person_id, c.recorded_at, d.code, d.version, d.title, d.description, d.is_active AS definition_is_active,
       p.first_name AS given_by_first_name, p.last_name AS given_by_last_name
FROM membership_consents c JOIN consent_definitions d ON d.id = c.consent_definition_id
JOIN persons p ON p.id = c.given_by_person_id
WHERE c.membership_id = $1 ORDER BY c.recorded_at, c.id
`

type ListMembershipConsentsHistoryRow struct {
	ID                  int32
	MembershipID        int32
	ConsentDefinitionID int32
	Decision            string
	GivenByPersonID     int32
	RecordedAt          pgtype.Timestamptz
	Code                string
	Version             int32
	Title               string
	Description         string
	DefinitionIsActive  bool
	GivenByFirstName    string
	GivenByLastName     string
}

func (q *Queries) ListMembershipConsentsHistory(ctx context.Context, membershipID int32) ([]ListMembershipConsentsHistoryRow, error) {
	rows, err := q.db.Query(ctx, listMembershipConsentsHistory, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipConsentsHistoryRow
	for rows.Next() {
		var i ListMembershipConsentsHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.ConsentDefinitionID,
			&i.Decision,
			&i.GivenByPersonID,
			&i.RecordedAt,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.DefinitionIsActive,
			&i.GivenByFirstName,
			&i.GivenByLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConsentDefinition = `-- name: LockConsentDefinition :one
SELECT is_active FROM consent_definitions WHERE id = $1 FOR SHARE
`

// Prevent activation changes between validation and insertion.
func (q *Queries) LockConsentDefinition(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, lockConsentDefinition, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const lockConsentGuardian = `-- name: LockConsentGuardian :one
SELECT id FROM person_guardians
WHERE child_person_id = $1 AND guardian_person_id = $2 FOR SHARE
`

type LockConsentGuardianParams struct {
	ChildPersonID    int32
	GuardianPersonID int32
}

// Keep the authorizing relationship alive until the decision commits.
func (q *Queries) LockConsentGuardian(ctx context.Context, arg LockConsentGuardianParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockConsentGuardian, arg.ChildPersonID, arg.GuardianPersonID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const lockConsentMembership = `-- name: LockConsentMembership :one
SELECT person_id FROM memberships WHERE id = $1 FOR UPDATE
`

// Serialize decisions for a membership, and prevent its person changing during validation.
func (q *Queries) LockConsentMembership(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockConsentMembership, id)
	var person_id int32
	err := row.Scan(&person_id)
	return person_id, err
}
