// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID        int32
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type Group struct {
	ID          int32
	ActivityID  int32
	Name        string
	Description pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GroupSlot struct {
	ID       int32
	GroupID  int32
	SeasonID int32
	// ISO weekday: 1 = Monday, 7 = Sunday
	Weekday   int16
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Location  pgtype.Text
	ValidFrom pgtype.Date
	// Inclusive last date of validity
	ValidUntil pgtype.Date
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Membership struct {
	ID               int32
	PersonID         int32
	SeasonID         int32
	MembershipTypeID int32
	Status           string
	JoinedAt         pgtype.Date
	EndedAt          pgtype.Date
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type MembershipActivity struct {
	MembershipID int32
	ActivityID   int32
}

type MembershipGroup struct {
	ID           int32
	MembershipID int32
	GroupID      int32
	JoinedAt     pgtype.Date
	// First date no longer assigned; current interval is [joined_at, left_at)
	LeftAt    pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type MembershipType struct {
	ID        int32
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type Person struct {
	ID          int32
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	PhoneNumber pgtype.Text
	Email       pgtype.Text
	Address     pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	Notes       pgtype.Text
}

type PersonGuardian struct {
	ID               int32
	ChildPersonID    int32
	GuardianPersonID int32
	RelationshipType string
	IsPrimaryContact bool
	CreatedAt        pgtype.Timestamptz
}

type Role struct {
	ID   int32
	Name string
}

type Season struct {
	ID        int32
	Name      string
	StartsAt  pgtype.Date
	EndsAt    pgtype.Date
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type TrialRegistration struct {
	ID         int32
	PersonID   int32
	ActivityID int32
	TrialDate  pgtype.Date
	Status     string
	CreatedAt  pgtype.Timestamptz
	Notes      pgtype.Text
}

type User struct {
	ID           int32
	PersonID     int32
	LoginEmail   string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type UserRole struct {
	UserID int32
	RoleID int32
}
