// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"database/sql"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

type AccountSecurityEvent struct {
	ID        int32
	UserID    int32
	PersonID  int32
	Event     string
	CreatedAt dbtypes.Timestamp
}

type Activity struct {
	ID        int32
	Name      string
	IsActive  bool
	CreatedAt dbtypes.Timestamp
}

type AdministrativeEvent struct {
	ID           int32
	ActorUserID  int32
	Action       string
	ResourceType string
	ResourceID   int32
	CreatedAt    dbtypes.Timestamp
	RoleName     sql.NullString
}

type ChildRegistrationApplication struct {
	ApplicationID             int32
	GuardianClaimID           int32
	RelationshipType          string
	EmergencyContactRequested bool
	GuardianConfirmedAt       dbtypes.Timestamp
	GuardianConfirmedByUserID sql.NullInt32
	CreatedAt                 dbtypes.Timestamp
}

type ConsentDefinition struct {
	ID          int32
	Code        string
	Version     int32
	Title       string
	Description string
	IsActive    bool
	CreatedAt   dbtypes.Timestamp
}

type Group struct {
	ID               int32
	ActivityID       int32
	Name             string
	Description      sql.NullString
	IsActive         bool
	CreatedAt        dbtypes.Timestamp
	UpdatedAt        dbtypes.Timestamp
	ShowNamePublicly bool
}

type GroupSlot struct {
	ID            int32
	GroupID       int32
	SeasonID      int32
	Weekday       int16
	StartTime     dbtypes.Time
	EndTime       dbtypes.Time
	Location      sql.NullString
	ValidFrom     dbtypes.Date
	ValidUntil    dbtypes.Date
	IsActive      bool
	CreatedAt     dbtypes.Timestamp
	UpdatedAt     dbtypes.Timestamp
	LocationID    sql.NullInt32
	PracticeLabel sql.NullString
}

type GuardianAccessGrant struct {
	ID               int32
	ChildPersonID    int32
	GuardianPersonID int32
	GrantedAt        dbtypes.Timestamp
	GrantedByUserID  sql.NullInt32
	RevokedAt        dbtypes.Timestamp
	RevokedByUserID  sql.NullInt32
	CreatedAt        dbtypes.Timestamp
}

type GuardianIdentityClaim struct {
	ID               int32
	Status           string
	FirstName        string
	LastName         string
	BirthDate        dbtypes.Date
	Email            string
	PhoneNumber      sql.NullString
	Address          sql.NullString
	ResolvedPersonID sql.NullInt32
	ResolutionType   sql.NullString
	ResolvedAt       dbtypes.Timestamp
	ResolvedByUserID sql.NullInt32
	CreatedAt        dbtypes.Timestamp
	UpdatedAt        dbtypes.Timestamp
}

type GuardianIdentityClaimCandidate struct {
	GuardianClaimID  int32
	PersonID         int32
	Confidence       string
	MatchedName      bool
	MatchedBirthDate bool
	MatchedEmail     bool
	MatchedPhone     bool
	DetectedAt       dbtypes.Timestamp
}

type InstallationSetup struct {
	ID               bool
	InitializedAt    dbtypes.Timestamp
	FirstAdminUserID sql.NullInt32
	SecretHash       []byte
	SecretIssuedAt   dbtypes.Timestamp
	SecretGeneration int32
}

type Location struct {
	ID             int32
	OrganizationID int32
	Name           string
	Address        string
	IsActive       bool
	CreatedAt      dbtypes.Timestamp
	UpdatedAt      dbtypes.Timestamp
}

type Membership struct {
	ID               int32
	PersonID         int32
	SeasonID         int32
	MembershipTypeID int32
	Status           string
	JoinedAt         dbtypes.Date
	EndedAt          dbtypes.Date
	CreatedAt        dbtypes.Timestamp
	UpdatedAt        dbtypes.Timestamp
	RequestedAt      dbtypes.Timestamp
	ApprovedAt       dbtypes.Timestamp
	ApprovedByUserID sql.NullInt32
	AdminNote        sql.NullString
	SourceTrialID    sql.NullInt32
}

type MembershipActivity struct {
	MembershipID int32
	ActivityID   int32
}

type MembershipConsent struct {
	ID                  int32
	MembershipID        int32
	ConsentDefinitionID int32
	Decision            string
	GivenByPersonID     int32
	RecordedAt          dbtypes.Timestamp
}

type MembershipConsentRequirement struct {
	MembershipID        int32
	ConsentDefinitionID int32
	PresentedAt         dbtypes.Timestamp
}

type MembershipGroup struct {
	ID           int32
	MembershipID int32
	GroupID      int32
	JoinedAt     dbtypes.Date
	LeftAt       dbtypes.Date
	CreatedAt    dbtypes.Timestamp
}

type MembershipType struct {
	ID          int32
	Name        string
	IsActive    bool
	CreatedAt   dbtypes.Timestamp
	AmountCents sql.NullInt32
	Currency    string
	PublicNote  sql.NullString
}

type Organization struct {
	ID                          int32
	Name                        string
	ShortName                   sql.NullString
	Description                 sql.NullString
	PublicEmail                 sql.NullString
	PublicPhone                 sql.NullString
	CorrespondenceAddress       sql.NullString
	WebsiteUrl                  sql.NullString
	IsActive                    bool
	CreatedAt                   dbtypes.Timestamp
	UpdatedAt                   dbtypes.Timestamp
	PublicPhoneLabel            sql.NullString
	TrialSessionDescription     sql.NullString
	TrialItemsToBring           dbtypes.Strings
	TrialEquipmentOffer         sql.NullString
	TrialEquipmentDetailPrompt  sql.NullString
	PublicRulesDescription      sql.NullString
	MaxTrialsPerPersonPerSeason sql.NullInt32
}

type OrganizationLink struct {
	ID             int32
	OrganizationID int32
	Kind           string
	Label          string
	Url            string
	Position       int32
	IsActive       bool
	CreatedAt      dbtypes.Timestamp
	UpdatedAt      dbtypes.Timestamp
}

type OrganizationPublicImage struct {
	OrganizationID int32
	Placement      string
	Src            string
	WebpSrcset     string
	Alt            string
	Width          int32
	Height         int32
}

type Person struct {
	ID          int32
	FirstName   string
	LastName    string
	BirthDate   dbtypes.Date
	PhoneNumber sql.NullString
	Email       sql.NullString
	Address     sql.NullString
	CreatedAt   dbtypes.Timestamp
	ArchivedAt  dbtypes.Timestamp
	Notes       sql.NullString
	UpdatedAt   dbtypes.Timestamp
}

type PersonEmergencyContact struct {
	ID                int32
	PersonID          int32
	ContactPersonID   int32
	RelationshipLabel sql.NullString
	Priority          int32
	CreatedAt         dbtypes.Timestamp
	UpdatedAt         dbtypes.Timestamp
}

type PersonGuardian struct {
	ID               int32
	ChildPersonID    int32
	GuardianPersonID int32
	RelationshipType string
	IsPrimaryContact bool
	CreatedAt        dbtypes.Timestamp
}

type RegistrationApplication struct {
	RequiredActivityID int32
	ID                 int32
	SubmissionID       int32
	RequestKey         []byte
	SeasonID           int32
	MembershipTypeID   int32
	Status             string
	MembershipID       sql.NullInt32
	LastErrorCode      sql.NullString
	CreatedAt          dbtypes.Timestamp
	UpdatedAt          dbtypes.Timestamp
	FinalizedAt        dbtypes.Timestamp
}

type RegistrationApplicationActivity struct {
	ApplicationID int32
	ActivityID    int32
}

type RegistrationApplicationConsent struct {
	ApplicationID       int32
	ConsentDefinitionID int32
	Decision            string
	PresentedAt         dbtypes.Timestamp
}

type RegistrationEmailVerification struct {
	ID              int32
	SubmissionID    int32
	PersonID        int32
	PublicReference string
	CodeHash        []byte
	RecipientHash   []byte
	ExpiresAt       dbtypes.Timestamp
	UsedAt          dbtypes.Timestamp
	InvalidatedAt   dbtypes.Timestamp
	CreatedAt       dbtypes.Timestamp
}

type RegistrationSubmission struct {
	ID               int32
	Status           string
	FirstName        string
	LastName         string
	BirthDate        dbtypes.Date
	Email            sql.NullString
	PhoneNumber      sql.NullString
	Address          sql.NullString
	CreatedAt        dbtypes.Timestamp
	UpdatedAt        dbtypes.Timestamp
	ResolvedPersonID sql.NullInt32
	ResolutionType   sql.NullString
	ResolvedAt       dbtypes.Timestamp
	ResolvedByUserID sql.NullInt32
}

type RegistrationSubmissionCandidate struct {
	SubmissionID     int32
	PersonID         int32
	Confidence       string
	MatchedName      bool
	MatchedBirthDate bool
	MatchedEmail     bool
	MatchedPhone     bool
	DetectedAt       dbtypes.Timestamp
}

type RegistrationVerificationOutbox struct {
	ID            int32
	SubmissionID  int32
	Status        string
	AttemptCount  int32
	AvailableAt   dbtypes.Timestamp
	LeaseUntil    dbtypes.Timestamp
	LeaseVersion  int64
	CreatedAt     dbtypes.Timestamp
	UpdatedAt     dbtypes.Timestamp
	SentAt        dbtypes.Timestamp
	FinishedAt    dbtypes.Timestamp
	LastErrorCode sql.NullString
	RecipientHash []byte
}

type Role struct {
	ID   int32
	Name string
}

type Season struct {
	ID        int32
	Name      string
	StartsAt  dbtypes.Date
	EndsAt    dbtypes.Date
	IsActive  bool
	CreatedAt dbtypes.Timestamp
}

type TrialRegistration struct {
	ID          int32
	PersonID    int32
	ActivityID  int32
	TrialDate   dbtypes.Date
	Status      string
	CreatedAt   dbtypes.Timestamp
	Notes       sql.NullString
	GroupID     sql.NullInt32
	GroupSlotID sql.NullInt32
	Revision    int32
}

type User struct {
	ID           int32
	PersonID     int32
	LoginEmail   sql.NullString
	PasswordHash sql.NullString
	IsActive     bool
	CreatedAt    dbtypes.Timestamp
	Username     string
	ActivatedAt  dbtypes.Timestamp
}

type UserActivationCode struct {
	ID            int32
	UserID        int32
	CodeHash      []byte
	ExpiresAt     dbtypes.Timestamp
	UsedAt        dbtypes.Timestamp
	InvalidatedAt dbtypes.Timestamp
	CreatedAt     dbtypes.Timestamp
}

type UserEmailChangeRequest struct {
	ID                 int32
	UserID             int32
	PersonID           int32
	NewEmail           string
	NewEmailNormalized string
	NewEmailHash       []byte
	CodeHash           []byte
	ExpiresAt          dbtypes.Timestamp
	UsedAt             dbtypes.Timestamp
	InvalidatedAt      dbtypes.Timestamp
	CreatedAt          dbtypes.Timestamp
}

type UserRole struct {
	UserID int32
	RoleID int32
}
