// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID        int32
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type ConsentDefinition struct {
	ID          int32
	Code        string
	Version     int32
	Title       string
	Description string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

type Group struct {
	ID          int32
	ActivityID  int32
	Name        string
	Description pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GroupSlot struct {
	ID       int32
	GroupID  int32
	SeasonID int32
	// ISO weekday: 1 = Monday, 7 = Sunday
	Weekday   int16
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Location  pgtype.Text
	ValidFrom pgtype.Date
	// Inclusive last date of validity
	ValidUntil pgtype.Date
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Membership struct {
	ID               int32
	PersonID         int32
	SeasonID         int32
	MembershipTypeID int32
	Status           string
	JoinedAt         pgtype.Date
	EndedAt          pgtype.Date
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RequestedAt      pgtype.Timestamptz
	ApprovedAt       pgtype.Timestamptz
	ApprovedByUserID pgtype.Int4
	AdminNote        pgtype.Text
}

type MembershipActivity struct {
	MembershipID int32
	ActivityID   int32
}

type MembershipConsent struct {
	ID                  int32
	MembershipID        int32
	ConsentDefinitionID int32
	Decision            string
	GivenByPersonID     int32
	RecordedAt          pgtype.Timestamptz
}

type MembershipConsentRequirement struct {
	MembershipID        int32
	ConsentDefinitionID int32
	PresentedAt         pgtype.Timestamptz
}

type MembershipGroup struct {
	ID           int32
	MembershipID int32
	GroupID      int32
	JoinedAt     pgtype.Date
	// First date no longer assigned; current interval is [joined_at, left_at)
	LeftAt    pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type MembershipType struct {
	ID        int32
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type Person struct {
	ID          int32
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	PhoneNumber pgtype.Text
	Email       pgtype.Text
	Address     pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	Notes       pgtype.Text
}

type PersonEmergencyContact struct {
	ID                int32
	PersonID          int32
	ContactPersonID   int32
	RelationshipLabel pgtype.Text
	Priority          int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PersonGuardian struct {
	ID               int32
	ChildPersonID    int32
	GuardianPersonID int32
	RelationshipType string
	IsPrimaryContact bool
	CreatedAt        pgtype.Timestamptz
}

type RegistrationEmailVerification struct {
	ID              int64
	SubmissionID    int32
	PersonID        int32
	PublicReference string
	CodeHash        []byte
	RecipientHash   []byte
	ExpiresAt       pgtype.Timestamptz
	UsedAt          pgtype.Timestamptz
	InvalidatedAt   pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type RegistrationSubmission struct {
	ID               int32
	Status           string
	FirstName        string
	LastName         string
	BirthDate        pgtype.Date
	Email            pgtype.Text
	PhoneNumber      pgtype.Text
	Address          pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ResolvedPersonID pgtype.Int4
	ResolutionType   pgtype.Text
	ResolvedAt       pgtype.Timestamptz
	ResolvedByUserID pgtype.Int4
}

type RegistrationSubmissionCandidate struct {
	SubmissionID     int32
	PersonID         int32
	Confidence       string
	MatchedName      bool
	MatchedBirthDate bool
	MatchedEmail     bool
	MatchedPhone     bool
	DetectedAt       pgtype.Timestamptz
}

type RegistrationVerificationOutbox struct {
	ID            int64
	SubmissionID  int32
	Status        string
	AttemptCount  int32
	AvailableAt   pgtype.Timestamptz
	LeaseUntil    pgtype.Timestamptz
	LeaseVersion  int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	LastErrorCode pgtype.Text
	RecipientHash []byte
}

type Role struct {
	ID   int32
	Name string
}

type Season struct {
	ID        int32
	Name      string
	StartsAt  pgtype.Date
	EndsAt    pgtype.Date
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type TrialRegistration struct {
	ID          int32
	PersonID    int32
	ActivityID  int32
	TrialDate   pgtype.Date
	Status      string
	CreatedAt   pgtype.Timestamptz
	Notes       pgtype.Text
	GroupID     pgtype.Int4
	GroupSlotID pgtype.Int4
}

type User struct {
	ID           int32
	PersonID     int32
	LoginEmail   pgtype.Text
	PasswordHash pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	Username     string
	ActivatedAt  pgtype.Timestamptz
}

type UserActivationCode struct {
	ID            int64
	UserID        int32
	CodeHash      []byte
	ExpiresAt     pgtype.Timestamptz
	UsedAt        pgtype.Timestamptz
	InvalidatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type UserRole struct {
	UserID int32
	RoleID int32
}
