// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_data.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (organization_id,name,address) VALUES ($1,$2,$3) RETURNING id, organization_id, name, address, is_active, created_at, updated_at
`

type CreateLocationParams struct {
	OrganizationID int32
	Name           string
	Address        string
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.OrganizationID, arg.Name, arg.Address)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name,short_name,description,public_email,public_phone,correspondence_address,website_url)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, name, short_name, description, public_email, public_phone, correspondence_address, website_url, is_active, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name                  string
	ShortName             pgtype.Text
	Description           pgtype.Text
	PublicEmail           pgtype.Text
	PublicPhone           pgtype.Text
	CorrespondenceAddress pgtype.Text
	WebsiteUrl            pgtype.Text
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.PublicEmail,
		arg.PublicPhone,
		arg.CorrespondenceAddress,
		arg.WebsiteUrl,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.PublicEmail,
		&i.PublicPhone,
		&i.CorrespondenceAddress,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationLink = `-- name: CreateOrganizationLink :one
INSERT INTO organization_links (organization_id,kind,label,url,position) VALUES ($1,$2,$3,$4,$5) RETURNING id, organization_id, kind, label, url, position, is_active, created_at, updated_at
`

type CreateOrganizationLinkParams struct {
	OrganizationID int32
	Kind           string
	Label          string
	Url            string
	Position       int32
}

func (q *Queries) CreateOrganizationLink(ctx context.Context, arg CreateOrganizationLinkParams) (OrganizationLink, error) {
	row := q.db.QueryRow(ctx, createOrganizationLink,
		arg.OrganizationID,
		arg.Kind,
		arg.Label,
		arg.Url,
		arg.Position,
	)
	var i OrganizationLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Label,
		&i.Url,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveOrganization = `-- name: GetActiveOrganization :one
SELECT id, name, short_name, description, public_email, public_phone, correspondence_address, website_url, is_active, created_at, updated_at FROM organizations WHERE is_active
`

func (q *Queries) GetActiveOrganization(ctx context.Context) (Organization, error) {
	row := q.db.QueryRow(ctx, getActiveOrganization)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.PublicEmail,
		&i.PublicPhone,
		&i.CorrespondenceAddress,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferenceSeason = `-- name: GetReferenceSeason :one
SELECT id, name, starts_at, ends_at, is_active, created_at FROM seasons WHERE name=$1
`

func (q *Queries) GetReferenceSeason(ctx context.Context, name string) (Season, error) {
	row := q.db.QueryRow(ctx, getReferenceSeason, name)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizationLinks = `-- name: ListOrganizationLinks :many
SELECT id, organization_id, kind, label, url, position, is_active, created_at, updated_at FROM organization_links WHERE organization_id=$1 ORDER BY position,id
`

func (q *Queries) ListOrganizationLinks(ctx context.Context, organizationID int32) ([]OrganizationLink, error) {
	rows, err := q.db.Query(ctx, listOrganizationLinks, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationLink
	for rows.Next() {
		var i OrganizationLink
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Kind,
			&i.Label,
			&i.Url,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationLocations = `-- name: ListOrganizationLocations :many
SELECT id, organization_id, name, address, is_active, created_at, updated_at FROM locations WHERE organization_id=$1 ORDER BY name,id
`

func (q *Queries) ListOrganizationLocations(ctx context.Context, organizationID int32) ([]Location, error) {
	rows, err := q.db.Query(ctx, listOrganizationLocations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceSchedule = `-- name: ListReferenceSchedule :many
SELECT gs.id,gs.group_id,gs.season_id,g.name AS group_name,a.name AS activity_name,
 gs.weekday,to_char(gs.start_time,'HH24:MI')::text AS start_time,to_char(gs.end_time,'HH24:MI')::text AS end_time,
 gs.practice_label,gs.location_id,coalesce(l.name,gs.location,'')::text AS location_name,
 coalesce(l.address,'')::text AS location_address,gs.valid_from,gs.valid_until
FROM group_slots gs JOIN groups g ON g.id=gs.group_id JOIN activities a ON a.id=g.activity_id
JOIN seasons s ON s.id=gs.season_id LEFT JOIN locations l ON l.id=gs.location_id
WHERE s.id=$1 AND s.is_active AND gs.is_active AND g.is_active AND a.is_active
 AND (gs.location_id IS NULL OR l.is_active)
ORDER BY gs.weekday,gs.start_time,gs.id
`

type ListReferenceScheduleRow struct {
	ID              int32
	GroupID         int32
	SeasonID        int32
	GroupName       string
	ActivityName    string
	Weekday         int16
	StartTime       string
	EndTime         string
	PracticeLabel   pgtype.Text
	LocationID      pgtype.Int4
	LocationName    string
	LocationAddress string
	ValidFrom       pgtype.Date
	ValidUntil      pgtype.Date
}

func (q *Queries) ListReferenceSchedule(ctx context.Context, id int32) ([]ListReferenceScheduleRow, error) {
	rows, err := q.db.Query(ctx, listReferenceSchedule, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferenceScheduleRow
	for rows.Next() {
		var i ListReferenceScheduleRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SeasonID,
			&i.GroupName,
			&i.ActivityName,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.PracticeLabel,
			&i.LocationID,
			&i.LocationName,
			&i.LocationAddress,
			&i.ValidFrom,
			&i.ValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupSlotLocation = `-- name: SetGroupSlotLocation :one
UPDATE group_slots SET location_id=$2,location=NULL,updated_at=NOW() WHERE id=$1 RETURNING id, group_id, season_id, weekday, start_time, end_time, location, valid_from, valid_until, is_active, created_at, updated_at, location_id, practice_label
`

type SetGroupSlotLocationParams struct {
	ID         int32
	LocationID pgtype.Int4
}

func (q *Queries) SetGroupSlotLocation(ctx context.Context, arg SetGroupSlotLocationParams) (GroupSlot, error) {
	row := q.db.QueryRow(ctx, setGroupSlotLocation, arg.ID, arg.LocationID)
	var i GroupSlot
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
		&i.PracticeLabel,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET name=$2,address=$3,is_active=$4,updated_at=NOW() WHERE id=$1 RETURNING id, organization_id, name, address, is_active, created_at, updated_at
`

type UpdateLocationParams struct {
	ID       int32
	Name     string
	Address  string
	IsActive bool
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.IsActive,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET name=$2,short_name=$3,description=$4,public_email=$5,public_phone=$6,
 correspondence_address=$7,website_url=$8,is_active=$9,updated_at=NOW() WHERE id=$1 RETURNING id, name, short_name, description, public_email, public_phone, correspondence_address, website_url, is_active, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID                    int32
	Name                  string
	ShortName             pgtype.Text
	Description           pgtype.Text
	PublicEmail           pgtype.Text
	PublicPhone           pgtype.Text
	CorrespondenceAddress pgtype.Text
	WebsiteUrl            pgtype.Text
	IsActive              bool
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.PublicEmail,
		arg.PublicPhone,
		arg.CorrespondenceAddress,
		arg.WebsiteUrl,
		arg.IsActive,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.PublicEmail,
		&i.PublicPhone,
		&i.CorrespondenceAddress,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationLink = `-- name: UpdateOrganizationLink :one
UPDATE organization_links SET kind=$2,label=$3,url=$4,position=$5,is_active=$6,updated_at=NOW() WHERE id=$1 RETURNING id, organization_id, kind, label, url, position, is_active, created_at, updated_at
`

type UpdateOrganizationLinkParams struct {
	ID       int32
	Kind     string
	Label    string
	Url      string
	Position int32
	IsActive bool
}

func (q *Queries) UpdateOrganizationLink(ctx context.Context, arg UpdateOrganizationLinkParams) (OrganizationLink, error) {
	row := q.db.QueryRow(ctx, updateOrganizationLink,
		arg.ID,
		arg.Kind,
		arg.Label,
		arg.Url,
		arg.Position,
		arg.IsActive,
	)
	var i OrganizationLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Label,
		&i.Url,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
