// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_data.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (organization_id,name,address) VALUES (?1,?2,?3) RETURNING id, organization_id, name, address, is_active, created_at, updated_at
`

type CreateLocationParams struct {
	OrganizationID int32
	Name           string
	Address        string
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation, arg.OrganizationID, arg.Name, arg.Address)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name,short_name,description,public_email,public_phone,correspondence_address,website_url)
VALUES (?1,?2,?3,?4,?5,?6,?7) RETURNING id, name, short_name, description, public_email, public_phone, correspondence_address, website_url, is_active, created_at, updated_at, public_phone_label, trial_session_description, trial_items_to_bring, trial_equipment_offer, trial_equipment_detail_prompt, public_rules_description, max_trials_per_person_per_season
`

type CreateOrganizationParams struct {
	Name                  string
	ShortName             sql.NullString
	Description           sql.NullString
	PublicEmail           sql.NullString
	PublicPhone           sql.NullString
	CorrespondenceAddress sql.NullString
	WebsiteUrl            sql.NullString
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.PublicEmail,
		arg.PublicPhone,
		arg.CorrespondenceAddress,
		arg.WebsiteUrl,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.PublicEmail,
		&i.PublicPhone,
		&i.CorrespondenceAddress,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPhoneLabel,
		&i.TrialSessionDescription,
		&i.TrialItemsToBring,
		&i.TrialEquipmentOffer,
		&i.TrialEquipmentDetailPrompt,
		&i.PublicRulesDescription,
		&i.MaxTrialsPerPersonPerSeason,
	)
	return i, err
}

const createOrganizationLink = `-- name: CreateOrganizationLink :one
INSERT INTO organization_links (organization_id,kind,label,url,position) VALUES (?1,?2,?3,?4,?5) RETURNING id, organization_id, kind, label, url, position, is_active, created_at, updated_at
`

type CreateOrganizationLinkParams struct {
	OrganizationID int32
	Kind           string
	Label          string
	Url            string
	Position       int32
}

func (q *Queries) CreateOrganizationLink(ctx context.Context, arg CreateOrganizationLinkParams) (OrganizationLink, error) {
	row := q.db.QueryRowContext(ctx, createOrganizationLink,
		arg.OrganizationID,
		arg.Kind,
		arg.Label,
		arg.Url,
		arg.Position,
	)
	var i OrganizationLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Label,
		&i.Url,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveOrganization = `-- name: GetActiveOrganization :one
SELECT id, name, short_name, description, public_email, public_phone, correspondence_address, website_url, is_active, created_at, updated_at, public_phone_label, trial_session_description, trial_items_to_bring, trial_equipment_offer, trial_equipment_detail_prompt, public_rules_description, max_trials_per_person_per_season FROM organizations WHERE is_active
`

func (q *Queries) GetActiveOrganization(ctx context.Context) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getActiveOrganization)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.PublicEmail,
		&i.PublicPhone,
		&i.CorrespondenceAddress,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPhoneLabel,
		&i.TrialSessionDescription,
		&i.TrialItemsToBring,
		&i.TrialEquipmentOffer,
		&i.TrialEquipmentDetailPrompt,
		&i.PublicRulesDescription,
		&i.MaxTrialsPerPersonPerSeason,
	)
	return i, err
}

const getReferenceSeason = `-- name: GetReferenceSeason :one
SELECT id, name, starts_at, ends_at, is_active, created_at FROM seasons WHERE name=?1
`

func (q *Queries) GetReferenceSeason(ctx context.Context, name string) (Season, error) {
	row := q.db.QueryRowContext(ctx, getReferenceSeason, name)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizationLinks = `-- name: ListOrganizationLinks :many
SELECT id, organization_id, kind, label, url, position, is_active, created_at, updated_at FROM organization_links WHERE organization_id=?1 ORDER BY position,id
`

func (q *Queries) ListOrganizationLinks(ctx context.Context, organizationID int32) ([]OrganizationLink, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationLinks, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationLink
	for rows.Next() {
		var i OrganizationLink
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Kind,
			&i.Label,
			&i.Url,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationLocations = `-- name: ListOrganizationLocations :many
SELECT id, organization_id, name, address, is_active, created_at, updated_at FROM locations WHERE organization_id=?1 ORDER BY name,id
`

func (q *Queries) ListOrganizationLocations(ctx context.Context, organizationID int32) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationLocations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationPublicImages = `-- name: ListOrganizationPublicImages :many
SELECT organization_id, placement, src, webp_srcset, alt, width, height FROM organization_public_images WHERE organization_id=?1 ORDER BY placement
`

func (q *Queries) ListOrganizationPublicImages(ctx context.Context, organizationID int32) ([]OrganizationPublicImage, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationPublicImages, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationPublicImage
	for rows.Next() {
		var i OrganizationPublicImage
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Placement,
			&i.Src,
			&i.WebpSrcset,
			&i.Alt,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceSchedule = `-- name: ListReferenceSchedule :many
SELECT gs.id,gs.group_id,gs.season_id,g.name AS group_name,a.name AS activity_name,
 gs.weekday,CAST(substr(gs.start_time,1,5) AS TEXT) AS start_time,CAST(substr(gs.end_time,1,5) AS TEXT) AS end_time,
 gs.practice_label,gs.location_id,coalesce(l.name,gs.location,'') AS location_name, CAST(coalesce(l.address,'') AS TEXT) AS location_address,gs.valid_from,gs.valid_until
FROM group_slots gs JOIN groups g ON g.id=gs.group_id JOIN activities a ON a.id=g.activity_id
JOIN seasons s ON s.id=gs.season_id LEFT JOIN locations l ON l.id=gs.location_id
WHERE s.id=?1 AND s.is_active AND gs.is_active AND g.is_active AND a.is_active
 AND (gs.location_id IS NULL OR l.is_active)
ORDER BY gs.weekday,gs.start_time,gs.id
`

type ListReferenceScheduleRow struct {
	ID              int32
	GroupID         int32
	SeasonID        int32
	GroupName       string
	ActivityName    string
	Weekday         int16
	StartTime       string
	EndTime         string
	PracticeLabel   sql.NullString
	LocationID      sql.NullInt32
	LocationName    string
	LocationAddress string
	ValidFrom       dbtypes.Date
	ValidUntil      dbtypes.Date
}

func (q *Queries) ListReferenceSchedule(ctx context.Context, id int32) ([]ListReferenceScheduleRow, error) {
	rows, err := q.db.QueryContext(ctx, listReferenceSchedule, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferenceScheduleRow
	for rows.Next() {
		var i ListReferenceScheduleRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SeasonID,
			&i.GroupName,
			&i.ActivityName,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.PracticeLabel,
			&i.LocationID,
			&i.LocationName,
			&i.LocationAddress,
			&i.ValidFrom,
			&i.ValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupSlotLocation = `-- name: SetGroupSlotLocation :one
UPDATE group_slots SET location_id=?1,location=NULL,updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?2 RETURNING id, group_id, season_id, weekday, start_time, end_time, location, valid_from, valid_until, is_active, created_at, updated_at, location_id, practice_label
`

type SetGroupSlotLocationParams struct {
	LocationID sql.NullInt32
	ID         int32
}

func (q *Queries) SetGroupSlotLocation(ctx context.Context, arg SetGroupSlotLocationParams) (GroupSlot, error) {
	row := q.db.QueryRowContext(ctx, setGroupSlotLocation, arg.LocationID, arg.ID)
	var i GroupSlot
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
		&i.PracticeLabel,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET name=?1,address=?2,is_active=?3,updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?4 RETURNING id, organization_id, name, address, is_active, created_at, updated_at
`

type UpdateLocationParams struct {
	Name     string
	Address  string
	IsActive bool
	ID       int32
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocation,
		arg.Name,
		arg.Address,
		arg.IsActive,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET name=?1,short_name=?2,description=?3,public_email=?4,public_phone=?5,
 correspondence_address=?6,website_url=?7,is_active=?8,updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?9 RETURNING id, name, short_name, description, public_email, public_phone, correspondence_address, website_url, is_active, created_at, updated_at, public_phone_label, trial_session_description, trial_items_to_bring, trial_equipment_offer, trial_equipment_detail_prompt, public_rules_description, max_trials_per_person_per_season
`

type UpdateOrganizationParams struct {
	Name                  string
	ShortName             sql.NullString
	Description           sql.NullString
	PublicEmail           sql.NullString
	PublicPhone           sql.NullString
	CorrespondenceAddress sql.NullString
	WebsiteUrl            sql.NullString
	IsActive              bool
	ID                    int32
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, updateOrganization,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.PublicEmail,
		arg.PublicPhone,
		arg.CorrespondenceAddress,
		arg.WebsiteUrl,
		arg.IsActive,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.PublicEmail,
		&i.PublicPhone,
		&i.CorrespondenceAddress,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPhoneLabel,
		&i.TrialSessionDescription,
		&i.TrialItemsToBring,
		&i.TrialEquipmentOffer,
		&i.TrialEquipmentDetailPrompt,
		&i.PublicRulesDescription,
		&i.MaxTrialsPerPersonPerSeason,
	)
	return i, err
}

const updateOrganizationLink = `-- name: UpdateOrganizationLink :one
UPDATE organization_links SET kind=?1,label=?2,url=?3,position=?4,is_active=?5,updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?6 RETURNING id, organization_id, kind, label, url, position, is_active, created_at, updated_at
`

type UpdateOrganizationLinkParams struct {
	Kind     string
	Label    string
	Url      string
	Position int32
	IsActive bool
	ID       int32
}

func (q *Queries) UpdateOrganizationLink(ctx context.Context, arg UpdateOrganizationLinkParams) (OrganizationLink, error) {
	row := q.db.QueryRowContext(ctx, updateOrganizationLink,
		arg.Kind,
		arg.Label,
		arg.Url,
		arg.Position,
		arg.IsActive,
		arg.ID,
	)
	var i OrganizationLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Label,
		&i.Url,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
