// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const activePasswordReset = `-- name: ActivePasswordReset :one
SELECT r.id,r.user_id,u.person_id,u.username FROM user_password_reset_requests r
JOIN users u ON u.id=r.user_id
WHERE r.token_hash=?1 AND r.used_at IS NULL AND r.invalidated_at IS NULL
 AND r.expires_at>strftime('%Y-%m-%d %H:%M:%f','now')
 AND u.is_active AND u.activated_at IS NOT NULL AND u.password_hash IS NOT NULL AND length(u.password_hash)>0
`

type ActivePasswordResetRow struct {
	ID       int32
	UserID   int32
	PersonID int32
	Username string
}

func (q *Queries) ActivePasswordReset(ctx context.Context, tokenHash []byte) (ActivePasswordResetRow, error) {
	row := q.db.QueryRowContext(ctx, activePasswordReset, tokenHash)
	var i ActivePasswordResetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.Username,
	)
	return i, err
}

const consumePasswordReset = `-- name: ConsumePasswordReset :execrows
UPDATE user_password_reset_requests SET used_at=strftime('%Y-%m-%d %H:%M:%f','now')
WHERE id=?1 AND used_at IS NULL AND invalidated_at IS NULL
 AND expires_at>strftime('%Y-%m-%d %H:%M:%f','now')
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumePasswordReset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countRecentPasswordResets = `-- name: CountRecentPasswordResets :one
SELECT CAST(count(*) AS BIGINT) FROM user_password_reset_requests
WHERE user_id=?1 AND created_at>strftime('%Y-%m-%d %H:%M:%f','now','-1 hour')
`

func (q *Queries) CountRecentPasswordResets(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentPasswordResets, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO user_password_reset_requests(user_id,requested_by_user_id,token_hash,expires_at)
VALUES(?1,?2,?3,
 strftime('%Y-%m-%d %H:%M:%f','now',(?4+0.0)||' seconds')) RETURNING id
`

type CreatePasswordResetParams struct {
	UserID            int32
	RequestedByUserID sql.NullInt32
	TokenHash         []byte
	TtlSeconds        interface{}
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createPasswordReset,
		arg.UserID,
		arg.RequestedByUserID,
		arg.TokenHash,
		arg.TtlSeconds,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const invalidateFailedPasswordReset = `-- name: InvalidateFailedPasswordReset :exec
UPDATE user_password_reset_requests SET invalidated_at=strftime('%Y-%m-%d %H:%M:%f','now')
WHERE id=?1 AND used_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) InvalidateFailedPasswordReset(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, invalidateFailedPasswordReset, id)
	return err
}

const invalidatePasswordResets = `-- name: InvalidatePasswordResets :exec
UPDATE user_password_reset_requests SET invalidated_at=strftime('%Y-%m-%d %H:%M:%f','now')
WHERE user_id=?1 AND used_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) InvalidatePasswordResets(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, invalidatePasswordResets, userID)
	return err
}

const passwordResetUser = `-- name: PasswordResetUser :one
SELECT id,person_id,username FROM users
WHERE id=?1 AND is_active AND activated_at IS NOT NULL
 AND password_hash IS NOT NULL AND length(password_hash)>0
`

type PasswordResetUserRow struct {
	ID       int32
	PersonID int32
	Username string
}

func (q *Queries) PasswordResetUser(ctx context.Context, id int32) (PasswordResetUserRow, error) {
	row := q.db.QueryRowContext(ctx, passwordResetUser, id)
	var i PasswordResetUserRow
	err := row.Scan(&i.ID, &i.PersonID, &i.Username)
	return i, err
}

const passwordResetUserForPerson = `-- name: PasswordResetUserForPerson :one
SELECT id FROM users WHERE person_id=?1
`

func (q *Queries) PasswordResetUserForPerson(ctx context.Context, personID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, passwordResetUserForPerson, personID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
