// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_space.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const getPersonalAccount = `-- name: GetPersonalAccount :one
SELECT p.id AS person_id, p.first_name, p.last_name, p.email, p.phone_number, p.address, p.birth_date, u.username
FROM users u JOIN persons p ON p.id=u.person_id
WHERE u.id=?1 AND u.is_active AND u.activated_at IS NOT NULL
 AND u.password_hash IS NOT NULL AND p.archived_at IS NULL
`

type GetPersonalAccountRow struct {
	PersonID    int32
	FirstName   string
	LastName    string
	Email       sql.NullString
	PhoneNumber sql.NullString
	Address     sql.NullString
	BirthDate   dbtypes.Date
	Username    string
}

// Safe read projections only. Resource ownership is supplied by personalspace
// after deriving the caller's Person or checking GuardianAccess.
func (q *Queries) GetPersonalAccount(ctx context.Context, id int32) (GetPersonalAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonalAccount, id)
	var i GetPersonalAccountRow
	err := row.Scan(
		&i.PersonID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.BirthDate,
		&i.Username,
	)
	return i, err
}

const getPersonalChild = `-- name: GetPersonalChild :one
SELECT p.first_name,p.last_name,p.birth_date,
 EXISTS(SELECT 1 FROM person_emergency_contacts e WHERE e.person_id=p.id) AS has_emergency,
 EXISTS(SELECT 1 FROM person_emergency_contacts e WHERE e.person_id=p.id
 AND e.contact_person_id=?1) AS viewer_is_emergency
FROM persons p WHERE p.id=?2 AND p.archived_at IS NULL
`

type GetPersonalChildParams struct {
	ViewerPersonID int32
	ChildPersonID  int32
}

type GetPersonalChildRow struct {
	FirstName         string
	LastName          string
	BirthDate         dbtypes.Date
	HasEmergency      bool
	ViewerIsEmergency bool
}

func (q *Queries) GetPersonalChild(ctx context.Context, arg GetPersonalChildParams) (GetPersonalChildRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonalChild, arg.ViewerPersonID, arg.ChildPersonID)
	var i GetPersonalChildRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.HasEmergency,
		&i.ViewerIsEmergency,
	)
	return i, err
}

const getPersonalMembership = `-- name: GetPersonalMembership :one
SELECT m.id,m.status,m.requested_at,m.joined_at,s.name AS season_name,t.name AS membership_type_name,
 CAST((SELECT json_group_array(value) FROM (SELECT a.name AS value FROM activities a JOIN membership_activities ma ON ma.activity_id=a.id
 WHERE ma.membership_id=m.id ORDER BY a.name,a.id)) AS JSON_TEXT_STRINGS) AS activities
FROM memberships m JOIN seasons s ON s.id=m.season_id JOIN membership_types t ON t.id=m.membership_type_id
WHERE m.id=?1 AND m.person_id=?2
`

type GetPersonalMembershipParams struct {
	MembershipID int32
	PersonID     int32
}

type GetPersonalMembershipRow struct {
	ID                 int32
	Status             string
	RequestedAt        dbtypes.Timestamp
	JoinedAt           dbtypes.Date
	SeasonName         string
	MembershipTypeName string
	Activities         dbtypes.Strings
}

func (q *Queries) GetPersonalMembership(ctx context.Context, arg GetPersonalMembershipParams) (GetPersonalMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonalMembership, arg.MembershipID, arg.PersonID)
	var i GetPersonalMembershipRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestedAt,
		&i.JoinedAt,
		&i.SeasonName,
		&i.MembershipTypeName,
		&i.Activities,
	)
	return i, err
}

const hasOwnPersonalContext = `-- name: HasOwnPersonalContext :one
SELECT EXISTS(SELECT 1 FROM memberships WHERE person_id=p.id)
 OR EXISTS(SELECT 1 FROM registration_applications a
 JOIN registration_submissions s ON s.id=a.submission_id
 JOIN child_registration_applications c ON c.application_id=a.id
 JOIN guardian_identity_claims g ON g.id=c.guardian_claim_id
 WHERE g.resolved_by_user_id=u.id AND g.resolved_person_id=p.id
 AND a.status IN ('awaiting_identity','needs_review')) AS has_context
FROM users u JOIN persons p ON p.id=u.person_id
WHERE u.id=?1 AND u.is_active AND u.activated_at IS NOT NULL AND u.password_hash IS NOT NULL AND p.archived_at IS NULL
`

func (q *Queries) HasOwnPersonalContext(ctx context.Context, id int32) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, hasOwnPersonalContext, id)
	var has_context sql.NullBool
	err := row.Scan(&has_context)
	return has_context, err
}

const listPendingFamilyRequests = `-- name: ListPendingFamilyRequests :many
SELECT s.first_name,s.last_name,s.created_at
FROM registration_applications a
JOIN registration_submissions s ON s.id=a.submission_id
JOIN child_registration_applications c ON c.application_id=a.id
JOIN guardian_identity_claims g ON g.id=c.guardian_claim_id
WHERE g.resolved_by_user_id=?1
 AND g.resolved_person_id=?2
 AND a.status IN ('awaiting_identity','needs_review')
 AND (s.resolved_person_id IS NULL OR NOT(s.resolved_person_id IN (/*SLICE:managed_children*/?)))
ORDER BY s.created_at DESC,s.id DESC
`

type ListPendingFamilyRequestsParams struct {
	ViewerUserID    sql.NullInt32
	ViewerPersonID  sql.NullInt32
	ManagedChildren []sql.NullInt32
}

type ListPendingFamilyRequestsRow struct {
	FirstName string
	LastName  string
	CreatedAt dbtypes.Timestamp
}

// Only authenticated family submissions made by this account. Declared child
// data stays in staging; matching and resolved identities are never projected.
func (q *Queries) ListPendingFamilyRequests(ctx context.Context, arg ListPendingFamilyRequestsParams) ([]ListPendingFamilyRequestsRow, error) {
	query := listPendingFamilyRequests
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ViewerUserID)
	queryParams = append(queryParams, arg.ViewerPersonID)
	if len(arg.ManagedChildren) > 0 {
		for _, v := range arg.ManagedChildren {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:managed_children*/?", strings.Repeat(",?", len(arg.ManagedChildren))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:managed_children*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingFamilyRequestsRow
	for rows.Next() {
		var i ListPendingFamilyRequestsRow
		if err := rows.Scan(&i.FirstName, &i.LastName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalConsents = `-- name: ListPersonalConsents :many
SELECT d.id,d.is_active,d.title,d.version,d.description,c.decision,c.recorded_at, CAST(COALESCE(c.given_by_person_id=?1,false) AS BOOLEAN) AS given_by_viewer
FROM membership_consent_requirements r JOIN consent_definitions d ON d.id=r.consent_definition_id
LEFT JOIN membership_consents c ON c.id=(SELECT mc.id FROM membership_consents mc
 WHERE mc.membership_id=r.membership_id AND mc.consent_definition_id=r.consent_definition_id
 ORDER BY mc.recorded_at DESC,mc.id DESC LIMIT 1)
WHERE r.membership_id=?2 ORDER BY d.code,d.version
`

type ListPersonalConsentsParams struct {
	ViewerPersonID int32
	MembershipID   int32
}

type ListPersonalConsentsRow struct {
	ID            int32
	IsActive      bool
	Title         string
	Version       int32
	Description   string
	Decision      sql.NullString
	RecordedAt    dbtypes.Timestamp
	GivenByViewer bool
}

func (q *Queries) ListPersonalConsents(ctx context.Context, arg ListPersonalConsentsParams) ([]ListPersonalConsentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalConsents, arg.ViewerPersonID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalConsentsRow
	for rows.Next() {
		var i ListPersonalConsentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IsActive,
			&i.Title,
			&i.Version,
			&i.Description,
			&i.Decision,
			&i.RecordedAt,
			&i.GivenByViewer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalEmergencyContacts = `-- name: ListPersonalEmergencyContacts :many
SELECT e.person_id,e.priority,e.relationship_label,p.first_name,p.last_name,p.phone_number
FROM person_emergency_contacts e JOIN persons p ON p.id=e.contact_person_id
WHERE e.person_id IN (/*SLICE:ids*/?) ORDER BY e.person_id,e.priority
`

type ListPersonalEmergencyContactsRow struct {
	PersonID          int32
	Priority          int32
	RelationshipLabel sql.NullString
	FirstName         string
	LastName          string
	PhoneNumber       sql.NullString
}

func (q *Queries) ListPersonalEmergencyContacts(ctx context.Context, ids []int32) ([]ListPersonalEmergencyContactsRow, error) {
	query := listPersonalEmergencyContacts
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalEmergencyContactsRow
	for rows.Next() {
		var i ListPersonalEmergencyContactsRow
		if err := rows.Scan(
			&i.PersonID,
			&i.Priority,
			&i.RelationshipLabel,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalGroups = `-- name: ListPersonalGroups :many
SELECT g.name AS group_name,a.name AS activity_name,gs.weekday,
 CAST(COALESCE(CAST(substr(gs.start_time,1,5) AS TEXT),'') AS TEXT) AS start_time,
 CAST(COALESCE(CAST(substr(gs.end_time,1,5) AS TEXT),'') AS TEXT) AS end_time,COALESCE((SELECT l.name FROM locations l WHERE l.id=gs.location_id),gs.location) AS location
FROM membership_groups mg JOIN memberships m ON m.id=mg.membership_id
JOIN groups g ON g.id=mg.group_id AND g.is_active
JOIN activities a ON a.id=g.activity_id
LEFT JOIN group_slots gs ON gs.group_id=g.id AND gs.season_id=m.season_id
 AND gs.is_active AND gs.valid_from<=?1
 AND (gs.valid_until IS NULL OR gs.valid_until>=?1)
WHERE mg.membership_id=?2 AND mg.joined_at<=?1
 AND (mg.left_at IS NULL OR mg.left_at>?1)
ORDER BY g.name,g.id,gs.weekday,gs.start_time,gs.id
`

type ListPersonalGroupsParams struct {
	Today        dbtypes.Date
	MembershipID int32
}

type ListPersonalGroupsRow struct {
	GroupName    string
	ActivityName string
	Weekday      sql.NullInt16
	StartTime    string
	EndTime      string
	Location     sql.NullString
}

// Current assignment [joined_at,left_at); current slot validity is inclusive.
func (q *Queries) ListPersonalGroups(ctx context.Context, arg ListPersonalGroupsParams) ([]ListPersonalGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalGroups, arg.Today, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalGroupsRow
	for rows.Next() {
		var i ListPersonalGroupsRow
		if err := rows.Scan(
			&i.GroupName,
			&i.ActivityName,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalMembershipSummaries = `-- name: ListPersonalMembershipSummaries :many
SELECT m.id,m.person_id,m.season_id,m.status,m.requested_at,
 CAST((SELECT json_group_array(value) FROM (SELECT g.name AS value FROM membership_groups mg JOIN groups g ON g.id=mg.group_id
 WHERE mg.membership_id=m.id AND g.is_active AND mg.joined_at<=?1 AND (mg.left_at IS NULL OR mg.left_at>?1) ORDER BY g.name,g.id)) AS JSON_TEXT_STRINGS) AS group_names,
 CAST((s.starts_at<=?1 AND s.ends_at>=?1) AS BOOLEAN) AS is_current,
 s.name AS season_name,t.name AS membership_type_name,
 CAST((SELECT json_group_array(value) FROM (SELECT a.name AS value FROM activities a JOIN membership_activities ma ON ma.activity_id=a.id
 WHERE ma.membership_id=m.id ORDER BY a.name,a.id)) AS JSON_TEXT_STRINGS) AS activities
FROM memberships m JOIN seasons s ON s.id=m.season_id JOIN membership_types t ON t.id=m.membership_type_id
WHERE m.person_id IN (/*SLICE:ids*/?) ORDER BY is_current DESC,s.starts_at DESC,m.id DESC
`

type ListPersonalMembershipSummariesParams struct {
	Today dbtypes.Date
	Ids   []int32
}

type ListPersonalMembershipSummariesRow struct {
	ID                 int32
	PersonID           int32
	SeasonID           int32
	Status             string
	RequestedAt        dbtypes.Timestamp
	GroupNames         dbtypes.Strings
	IsCurrent          bool
	SeasonName         string
	MembershipTypeName string
	Activities         dbtypes.Strings
}

func (q *Queries) ListPersonalMembershipSummaries(ctx context.Context, arg ListPersonalMembershipSummariesParams) ([]ListPersonalMembershipSummariesRow, error) {
	query := listPersonalMembershipSummaries
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Today)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalMembershipSummariesRow
	for rows.Next() {
		var i ListPersonalMembershipSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.SeasonID,
			&i.Status,
			&i.RequestedAt,
			&i.GroupNames,
			&i.IsCurrent,
			&i.SeasonName,
			&i.MembershipTypeName,
			&i.Activities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
