// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_space.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPersonalAccount = `-- name: GetPersonalAccount :one
SELECT p.id AS person_id, p.first_name, p.last_name, p.email, p.phone_number, u.username
FROM users u JOIN persons p ON p.id=u.person_id
WHERE u.id=$1 AND u.is_active AND u.activated_at IS NOT NULL
 AND u.password_hash IS NOT NULL AND p.archived_at IS NULL
`

type GetPersonalAccountRow struct {
	PersonID    int32
	FirstName   string
	LastName    string
	Email       pgtype.Text
	PhoneNumber pgtype.Text
	Username    string
}

// Safe read projections only. Resource ownership is supplied by personalspace
// after deriving the caller's Person or checking GuardianAccess.
func (q *Queries) GetPersonalAccount(ctx context.Context, id int32) (GetPersonalAccountRow, error) {
	row := q.db.QueryRow(ctx, getPersonalAccount, id)
	var i GetPersonalAccountRow
	err := row.Scan(
		&i.PersonID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
	)
	return i, err
}

const getPersonalChild = `-- name: GetPersonalChild :one
SELECT p.first_name,p.last_name,p.birth_date,
 EXISTS(SELECT 1 FROM person_emergency_contacts e WHERE e.person_id=p.id) AS has_emergency,
 EXISTS(SELECT 1 FROM person_emergency_contacts e WHERE e.person_id=p.id
 AND e.contact_person_id=$1) AS viewer_is_emergency
FROM persons p WHERE p.id=$2 AND p.archived_at IS NULL
`

type GetPersonalChildParams struct {
	ViewerPersonID int32
	ChildPersonID  int32
}

type GetPersonalChildRow struct {
	FirstName         string
	LastName          string
	BirthDate         pgtype.Date
	HasEmergency      bool
	ViewerIsEmergency bool
}

func (q *Queries) GetPersonalChild(ctx context.Context, arg GetPersonalChildParams) (GetPersonalChildRow, error) {
	row := q.db.QueryRow(ctx, getPersonalChild, arg.ViewerPersonID, arg.ChildPersonID)
	var i GetPersonalChildRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.HasEmergency,
		&i.ViewerIsEmergency,
	)
	return i, err
}

const getPersonalMembership = `-- name: GetPersonalMembership :one
SELECT m.id,m.status,m.requested_at,m.joined_at,s.name AS season_name,t.name AS membership_type_name,
 ARRAY(SELECT a.name FROM activities a JOIN membership_activities ma ON ma.activity_id=a.id
 WHERE ma.membership_id=m.id ORDER BY a.name,a.id)::text[] AS activities
FROM memberships m JOIN seasons s ON s.id=m.season_id JOIN membership_types t ON t.id=m.membership_type_id
WHERE m.id=$1 AND m.person_id=$2
`

type GetPersonalMembershipParams struct {
	MembershipID int32
	PersonID     int32
}

type GetPersonalMembershipRow struct {
	ID                 int32
	Status             string
	RequestedAt        pgtype.Timestamptz
	JoinedAt           pgtype.Date
	SeasonName         string
	MembershipTypeName string
	Activities         []string
}

func (q *Queries) GetPersonalMembership(ctx context.Context, arg GetPersonalMembershipParams) (GetPersonalMembershipRow, error) {
	row := q.db.QueryRow(ctx, getPersonalMembership, arg.MembershipID, arg.PersonID)
	var i GetPersonalMembershipRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestedAt,
		&i.JoinedAt,
		&i.SeasonName,
		&i.MembershipTypeName,
		&i.Activities,
	)
	return i, err
}

const listPersonalConsents = `-- name: ListPersonalConsents :many
SELECT d.title,d.version,d.description,c.decision,c.recorded_at,
 COALESCE(c.given_by_person_id=$1,false)::boolean AS given_by_viewer
FROM membership_consent_requirements r JOIN consent_definitions d ON d.id=r.consent_definition_id
LEFT JOIN membership_consents c ON c.id=(SELECT mc.id FROM membership_consents mc
 WHERE mc.membership_id=r.membership_id AND mc.consent_definition_id=r.consent_definition_id
 ORDER BY mc.recorded_at DESC,mc.id DESC LIMIT 1)
WHERE r.membership_id=$2 ORDER BY d.code,d.version
`

type ListPersonalConsentsParams struct {
	ViewerPersonID int32
	MembershipID   int32
}

type ListPersonalConsentsRow struct {
	Title         string
	Version       int32
	Description   string
	Decision      pgtype.Text
	RecordedAt    pgtype.Timestamptz
	GivenByViewer bool
}

func (q *Queries) ListPersonalConsents(ctx context.Context, arg ListPersonalConsentsParams) ([]ListPersonalConsentsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalConsents, arg.ViewerPersonID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalConsentsRow
	for rows.Next() {
		var i ListPersonalConsentsRow
		if err := rows.Scan(
			&i.Title,
			&i.Version,
			&i.Description,
			&i.Decision,
			&i.RecordedAt,
			&i.GivenByViewer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalGroups = `-- name: ListPersonalGroups :many
SELECT g.name AS group_name,a.name AS activity_name,gs.weekday,
 COALESCE(to_char(gs.start_time,'HH24:MI'),'')::text AS start_time,
 COALESCE(to_char(gs.end_time,'HH24:MI'),'')::text AS end_time,gs.location
FROM membership_groups mg JOIN memberships m ON m.id=mg.membership_id
JOIN groups g ON g.id=mg.group_id AND g.is_active
JOIN activities a ON a.id=g.activity_id
LEFT JOIN group_slots gs ON gs.group_id=g.id AND gs.season_id=m.season_id
 AND gs.is_active AND gs.valid_from<=$1::date
 AND (gs.valid_until IS NULL OR gs.valid_until>=$1::date)
WHERE mg.membership_id=$2 AND mg.joined_at<=$1::date
 AND (mg.left_at IS NULL OR mg.left_at>$1::date)
ORDER BY g.name,g.id,gs.weekday,gs.start_time,gs.id
`

type ListPersonalGroupsParams struct {
	Today        pgtype.Date
	MembershipID int32
}

type ListPersonalGroupsRow struct {
	GroupName    string
	ActivityName string
	Weekday      pgtype.Int2
	StartTime    string
	EndTime      string
	Location     pgtype.Text
}

// Current assignment [joined_at,left_at); current slot validity is inclusive.
func (q *Queries) ListPersonalGroups(ctx context.Context, arg ListPersonalGroupsParams) ([]ListPersonalGroupsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalGroups, arg.Today, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalGroupsRow
	for rows.Next() {
		var i ListPersonalGroupsRow
		if err := rows.Scan(
			&i.GroupName,
			&i.ActivityName,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalMembershipSummaries = `-- name: ListPersonalMembershipSummaries :many
SELECT m.id,m.person_id,m.status,s.name AS season_name,t.name AS membership_type_name,
 ARRAY(SELECT a.name FROM activities a JOIN membership_activities ma ON ma.activity_id=a.id
 WHERE ma.membership_id=m.id ORDER BY a.name,a.id)::text[] AS activities
FROM memberships m JOIN seasons s ON s.id=m.season_id JOIN membership_types t ON t.id=m.membership_type_id
WHERE m.person_id=ANY($1::integer[]) ORDER BY s.starts_at DESC,m.id DESC
`

type ListPersonalMembershipSummariesRow struct {
	ID                 int32
	PersonID           int32
	Status             string
	SeasonName         string
	MembershipTypeName string
	Activities         []string
}

func (q *Queries) ListPersonalMembershipSummaries(ctx context.Context, dollar_1 []int32) ([]ListPersonalMembershipSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPersonalMembershipSummaries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalMembershipSummariesRow
	for rows.Next() {
		var i ListPersonalMembershipSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Status,
			&i.SeasonName,
			&i.MembershipTypeName,
			&i.Activities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
