// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const archivePerson = `-- name: ArchivePerson :exec
UPDATE persons
SET archived_at = strftime('%Y-%m-%d %H:%M:%f','now')
WHERE id = ?1
`

func (q *Queries) ArchivePerson(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, archivePerson, id)
	return err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (
    first_name,
    last_name,
    birth_date,
    phone_number,
    email,
    address,
    notes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
RETURNING id, first_name, last_name, birth_date, phone_number, email, address, created_at, archived_at, notes, updated_at
`

type CreatePersonParams struct {
	FirstName   string
	LastName    string
	BirthDate   dbtypes.Date
	PhoneNumber sql.NullString
	Email       sql.NullString
	Address     sql.NullString
	Notes       sql.NullString
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.PhoneNumber,
		arg.Email,
		arg.Address,
		arg.Notes,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, first_name, last_name, birth_date, phone_number, email, address, created_at, archived_at, notes, updated_at
FROM persons
WHERE id = ?1
`

func (q *Queries) GetPersonByID(ctx context.Context, id int32) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const listArchivedPersons = `-- name: ListArchivedPersons :many
SELECT id, first_name, last_name, birth_date, phone_number, email, address, created_at, archived_at, notes, updated_at
FROM persons
WHERE archived_at IS NOT NULL
ORDER BY last_name, first_name
`

func (q *Queries) ListArchivedPersons(ctx context.Context) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.Email,
			&i.Address,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.Notes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersons = `-- name: ListPersons :many
SELECT id, first_name, last_name, birth_date, phone_number, email, address, created_at, archived_at, notes, updated_at
FROM persons
WHERE archived_at IS NULL
ORDER BY last_name, first_name
`

func (q *Queries) ListPersons(ctx context.Context) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.Email,
			&i.Address,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.Notes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePerson = `-- name: RestorePerson :exec
UPDATE persons
SET archived_at = NULL
WHERE id = ?1
`

func (q *Queries) RestorePerson(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, restorePerson, id)
	return err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET 
    first_name = ?1,
    last_name = ?2,
    birth_date = ?3,
    phone_number = ?4,
    email = ?5,
    address = ?6,
    -- Existing callers preserve notes unless explicitly requested (NULL clears them).
    notes = CASE WHEN CAST(?7 AS BOOLEAN) THEN ?8 ELSE notes END
WHERE id = ?9
RETURNING id, first_name, last_name, birth_date, phone_number, email, address, created_at, archived_at, notes, updated_at
`

type UpdatePersonParams struct {
	FirstName   string
	LastName    string
	BirthDate   dbtypes.Date
	PhoneNumber sql.NullString
	Email       sql.NullString
	Address     sql.NullString
	UpdateNotes bool
	Notes       sql.NullString
	ID          int32
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, updatePerson,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.PhoneNumber,
		arg.Email,
		arg.Address,
		arg.UpdateNotes,
		arg.Notes,
		arg.ID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}
