// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: person_guardians.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonGuardian = `-- name: CreatePersonGuardian :one
INSERT INTO person_guardians (child_person_id, guardian_person_id, relationship_type, is_primary_contact)
VALUES ($1, $2, $3, $4)
RETURNING id, child_person_id, guardian_person_id, relationship_type, is_primary_contact, created_at
`

type CreatePersonGuardianParams struct {
	ChildPersonID    int32
	GuardianPersonID int32
	RelationshipType string
	IsPrimaryContact bool
}

func (q *Queries) CreatePersonGuardian(ctx context.Context, arg CreatePersonGuardianParams) (PersonGuardian, error) {
	row := q.db.QueryRow(ctx, createPersonGuardian,
		arg.ChildPersonID,
		arg.GuardianPersonID,
		arg.RelationshipType,
		arg.IsPrimaryContact,
	)
	var i PersonGuardian
	err := row.Scan(
		&i.ID,
		&i.ChildPersonID,
		&i.GuardianPersonID,
		&i.RelationshipType,
		&i.IsPrimaryContact,
		&i.CreatedAt,
	)
	return i, err
}

const deletePersonGuardian = `-- name: DeletePersonGuardian :exec
DELETE FROM person_guardians WHERE id = $1
`

func (q *Queries) DeletePersonGuardian(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePersonGuardian, id)
	return err
}

const listGuardianChildren = `-- name: ListGuardianChildren :many
SELECT pg.id, pg.child_person_id, pg.guardian_person_id, pg.relationship_type, pg.is_primary_contact, pg.created_at, p.first_name, p.last_name
FROM person_guardians pg
JOIN persons p ON p.id = pg.child_person_id
WHERE pg.guardian_person_id = $1
ORDER BY pg.id
`

type ListGuardianChildrenRow struct {
	ID               int32
	ChildPersonID    int32
	GuardianPersonID int32
	RelationshipType string
	IsPrimaryContact bool
	CreatedAt        pgtype.Timestamptz
	FirstName        string
	LastName         string
}

func (q *Queries) ListGuardianChildren(ctx context.Context, guardianPersonID int32) ([]ListGuardianChildrenRow, error) {
	rows, err := q.db.Query(ctx, listGuardianChildren, guardianPersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuardianChildrenRow
	for rows.Next() {
		var i ListGuardianChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildPersonID,
			&i.GuardianPersonID,
			&i.RelationshipType,
			&i.IsPrimaryContact,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonGuardians = `-- name: ListPersonGuardians :many
SELECT pg.id, pg.child_person_id, pg.guardian_person_id, pg.relationship_type, pg.is_primary_contact, pg.created_at, p.first_name, p.last_name, p.phone_number, p.email
FROM person_guardians pg
JOIN persons p ON p.id = pg.guardian_person_id
WHERE pg.child_person_id = $1
ORDER BY pg.id
`

type ListPersonGuardiansRow struct {
	ID               int32
	ChildPersonID    int32
	GuardianPersonID int32
	RelationshipType string
	IsPrimaryContact bool
	CreatedAt        pgtype.Timestamptz
	FirstName        string
	LastName         string
	PhoneNumber      pgtype.Text
	Email            pgtype.Text
}

func (q *Queries) ListPersonGuardians(ctx context.Context, childPersonID int32) ([]ListPersonGuardiansRow, error) {
	rows, err := q.db.Query(ctx, listPersonGuardians, childPersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonGuardiansRow
	for rows.Next() {
		var i ListPersonGuardiansRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildPersonID,
			&i.GuardianPersonID,
			&i.RelationshipType,
			&i.IsPrimaryContact,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonGuardian = `-- name: UpdatePersonGuardian :one
UPDATE person_guardians
SET relationship_type = $2, is_primary_contact = $3
WHERE id = $1
RETURNING id, child_person_id, guardian_person_id, relationship_type, is_primary_contact, created_at
`

type UpdatePersonGuardianParams struct {
	ID               int32
	RelationshipType string
	IsPrimaryContact bool
}

func (q *Queries) UpdatePersonGuardian(ctx context.Context, arg UpdatePersonGuardianParams) (PersonGuardian, error) {
	row := q.db.QueryRow(ctx, updatePersonGuardian, arg.ID, arg.RelationshipType, arg.IsPrimaryContact)
	var i PersonGuardian
	err := row.Scan(
		&i.ID,
		&i.ChildPersonID,
		&i.GuardianPersonID,
		&i.RelationshipType,
		&i.IsPrimaryContact,
		&i.CreatedAt,
	)
	return i, err
}
