// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: person_emergency_contacts.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonEmergencyContact = `-- name: CreatePersonEmergencyContact :one
INSERT INTO person_emergency_contacts(person_id, contact_person_id, relationship_label, priority)
VALUES ($1, $2, $3, $4) RETURNING id, person_id, contact_person_id, relationship_label, priority, created_at, updated_at
`

type CreatePersonEmergencyContactParams struct {
	PersonID          int32
	ContactPersonID   int32
	RelationshipLabel pgtype.Text
	Priority          int32
}

func (q *Queries) CreatePersonEmergencyContact(ctx context.Context, arg CreatePersonEmergencyContactParams) (PersonEmergencyContact, error) {
	row := q.db.QueryRow(ctx, createPersonEmergencyContact,
		arg.PersonID,
		arg.ContactPersonID,
		arg.RelationshipLabel,
		arg.Priority,
	)
	var i PersonEmergencyContact
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ContactPersonID,
		&i.RelationshipLabel,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePersonEmergencyContact = `-- name: DeletePersonEmergencyContact :exec
DELETE FROM person_emergency_contacts WHERE id = $1
`

func (q *Queries) DeletePersonEmergencyContact(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePersonEmergencyContact, id)
	return err
}

const listEmergencyContactForPersons = `-- name: ListEmergencyContactForPersons :many
SELECT e.id AS emergency_contact_id, e.person_id, e.contact_person_id, p.first_name, p.last_name,
       p.phone_number, p.email, e.relationship_label, e.priority
FROM person_emergency_contacts e JOIN persons p ON p.id = e.person_id
WHERE e.contact_person_id = $1 ORDER BY e.person_id
`

type ListEmergencyContactForPersonsRow struct {
	EmergencyContactID int32
	PersonID           int32
	ContactPersonID    int32
	FirstName          string
	LastName           string
	PhoneNumber        pgtype.Text
	Email              pgtype.Text
	RelationshipLabel  pgtype.Text
	Priority           int32
}

func (q *Queries) ListEmergencyContactForPersons(ctx context.Context, contactPersonID int32) ([]ListEmergencyContactForPersonsRow, error) {
	rows, err := q.db.Query(ctx, listEmergencyContactForPersons, contactPersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmergencyContactForPersonsRow
	for rows.Next() {
		var i ListEmergencyContactForPersonsRow
		if err := rows.Scan(
			&i.EmergencyContactID,
			&i.PersonID,
			&i.ContactPersonID,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Email,
			&i.RelationshipLabel,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonEmergencyContacts = `-- name: ListPersonEmergencyContacts :many
SELECT e.id AS emergency_contact_id, e.contact_person_id, p.first_name, p.last_name,
       p.phone_number, p.email, e.relationship_label, e.priority
FROM person_emergency_contacts e JOIN persons p ON p.id = e.contact_person_id
WHERE e.person_id = $1 ORDER BY e.priority
`

type ListPersonEmergencyContactsRow struct {
	EmergencyContactID int32
	ContactPersonID    int32
	FirstName          string
	LastName           string
	PhoneNumber        pgtype.Text
	Email              pgtype.Text
	RelationshipLabel  pgtype.Text
	Priority           int32
}

func (q *Queries) ListPersonEmergencyContacts(ctx context.Context, personID int32) ([]ListPersonEmergencyContactsRow, error) {
	rows, err := q.db.Query(ctx, listPersonEmergencyContacts, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonEmergencyContactsRow
	for rows.Next() {
		var i ListPersonEmergencyContactsRow
		if err := rows.Scan(
			&i.EmergencyContactID,
			&i.ContactPersonID,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Email,
			&i.RelationshipLabel,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonEmergencyContact = `-- name: UpdatePersonEmergencyContact :one
UPDATE person_emergency_contacts
SET relationship_label = $2, priority = $3, updated_at = clock_timestamp()
WHERE id = $1 RETURNING id, person_id, contact_person_id, relationship_label, priority, created_at, updated_at
`

type UpdatePersonEmergencyContactParams struct {
	ID                int32
	RelationshipLabel pgtype.Text
	Priority          int32
}

func (q *Queries) UpdatePersonEmergencyContact(ctx context.Context, arg UpdatePersonEmergencyContactParams) (PersonEmergencyContact, error) {
	row := q.db.QueryRow(ctx, updatePersonEmergencyContact, arg.ID, arg.RelationshipLabel, arg.Priority)
	var i PersonEmergencyContact
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ContactPersonID,
		&i.RelationshipLabel,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
