// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_organization.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCurrentPublicSeasons = `-- name: ListCurrentPublicSeasons :many
SELECT id,name FROM seasons WHERE is_active AND $1::date BETWEEN starts_at AND ends_at
ORDER BY starts_at,id
`

type ListCurrentPublicSeasonsRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListCurrentPublicSeasons(ctx context.Context, today pgtype.Date) ([]ListCurrentPublicSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentPublicSeasons, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentPublicSeasonsRow
	for rows.Next() {
		var i ListCurrentPublicSeasonsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicSchedule = `-- name: ListPublicSchedule :many
SELECT gs.weekday,to_char(gs.start_time,'HH24:MI')::text AS start_time,
 to_char(gs.end_time,'HH24:MI')::text AS end_time,a.name AS activity_name,
 CASE WHEN g.show_name_publicly THEN g.name ELSE '' END::text AS group_name,
 coalesce(gs.practice_label,'')::text AS practice_label,
 coalesce(l.name,gs.location,'')::text AS location_name,coalesce(l.address,'')::text AS location_address
FROM group_slots gs JOIN groups g ON g.id=gs.group_id JOIN activities a ON a.id=g.activity_id
JOIN seasons s ON s.id=gs.season_id LEFT JOIN locations l ON l.id=gs.location_id
WHERE gs.season_id=$1 AND s.is_active AND g.is_active AND a.is_active AND gs.is_active
 AND gs.valid_from<=$2::date AND (gs.valid_until IS NULL OR gs.valid_until>=$2::date)
 AND (gs.location_id IS NULL OR (l.is_active AND l.organization_id=$3))
ORDER BY gs.weekday,gs.start_time,gs.id
`

type ListPublicScheduleParams struct {
	SeasonID       int32
	Today          pgtype.Date
	OrganizationID int32
}

type ListPublicScheduleRow struct {
	Weekday         int16
	StartTime       string
	EndTime         string
	ActivityName    string
	GroupName       string
	PracticeLabel   string
	LocationName    string
	LocationAddress string
}

func (q *Queries) ListPublicSchedule(ctx context.Context, arg ListPublicScheduleParams) ([]ListPublicScheduleRow, error) {
	rows, err := q.db.Query(ctx, listPublicSchedule, arg.SeasonID, arg.Today, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicScheduleRow
	for rows.Next() {
		var i ListPublicScheduleRow
		if err := rows.Scan(
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.ActivityName,
			&i.GroupName,
			&i.PracticeLabel,
			&i.LocationName,
			&i.LocationAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
