// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_submissions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenRegistrationReviews = `-- name: CountOpenRegistrationReviews :one
SELECT count(*) FROM registration_submissions s WHERE status IN ('received','awaiting_identity_review') OR EXISTS(SELECT 1 FROM registration_applications a WHERE a.submission_id=s.id AND a.status='needs_review')
`

func (q *Queries) CountOpenRegistrationReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenRegistrationReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistrationCandidate = `-- name: CreateRegistrationCandidate :exec
INSERT INTO registration_submission_candidates(submission_id,person_id,confidence,matched_name,matched_birth_date,matched_email,matched_phone)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type CreateRegistrationCandidateParams struct {
	SubmissionID     int32
	PersonID         int32
	Confidence       string
	MatchedName      bool
	MatchedBirthDate bool
	MatchedEmail     bool
	MatchedPhone     bool
}

func (q *Queries) CreateRegistrationCandidate(ctx context.Context, arg CreateRegistrationCandidateParams) error {
	_, err := q.db.Exec(ctx, createRegistrationCandidate,
		arg.SubmissionID,
		arg.PersonID,
		arg.Confidence,
		arg.MatchedName,
		arg.MatchedBirthDate,
		arg.MatchedEmail,
		arg.MatchedPhone,
	)
	return err
}

const createRegistrationSubmission = `-- name: CreateRegistrationSubmission :one
INSERT INTO registration_submissions(first_name,last_name,birth_date,email,phone_number,address)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, status, first_name, last_name, birth_date, email, phone_number, address, created_at, updated_at, resolved_person_id, resolution_type, resolved_at, resolved_by_user_id
`

type CreateRegistrationSubmissionParams struct {
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	Email       pgtype.Text
	PhoneNumber pgtype.Text
	Address     pgtype.Text
}

func (q *Queries) CreateRegistrationSubmission(ctx context.Context, arg CreateRegistrationSubmissionParams) (RegistrationSubmission, error) {
	row := q.db.QueryRow(ctx, createRegistrationSubmission,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Email,
		arg.PhoneNumber,
		arg.Address,
	)
	var i RegistrationSubmission
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedPersonID,
		&i.ResolutionType,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
	)
	return i, err
}

const getRegistrationCandidate = `-- name: GetRegistrationCandidate :one
SELECT submission_id, person_id, confidence, matched_name, matched_birth_date, matched_email, matched_phone, detected_at FROM registration_submission_candidates WHERE submission_id=$1 AND person_id=$2
`

type GetRegistrationCandidateParams struct {
	SubmissionID int32
	PersonID     int32
}

func (q *Queries) GetRegistrationCandidate(ctx context.Context, arg GetRegistrationCandidateParams) (RegistrationSubmissionCandidate, error) {
	row := q.db.QueryRow(ctx, getRegistrationCandidate, arg.SubmissionID, arg.PersonID)
	var i RegistrationSubmissionCandidate
	err := row.Scan(
		&i.SubmissionID,
		&i.PersonID,
		&i.Confidence,
		&i.MatchedName,
		&i.MatchedBirthDate,
		&i.MatchedEmail,
		&i.MatchedPhone,
		&i.DetectedAt,
	)
	return i, err
}

const getRegistrationSubmission = `-- name: GetRegistrationSubmission :one
SELECT s.id, s.status, s.first_name, s.last_name, s.birth_date, s.email, s.phone_number, s.address, s.created_at, s.updated_at, s.resolved_person_id, s.resolution_type, s.resolved_at, s.resolved_by_user_id, u.username AS resolver_username,
 EXISTS(SELECT 1 FROM registration_email_verifications v WHERE v.submission_id=s.id AND v.person_id=s.resolved_person_id AND v.used_at IS NOT NULL) AS email_verified
FROM registration_submissions s LEFT JOIN users u ON u.id=s.resolved_by_user_id
WHERE s.id=$1
`

type GetRegistrationSubmissionRow struct {
	ID               int32
	Status           string
	FirstName        string
	LastName         string
	BirthDate        pgtype.Date
	Email            pgtype.Text
	PhoneNumber      pgtype.Text
	Address          pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ResolvedPersonID pgtype.Int4
	ResolutionType   pgtype.Text
	ResolvedAt       pgtype.Timestamptz
	ResolvedByUserID pgtype.Int4
	ResolverUsername pgtype.Text
	EmailVerified    bool
}

func (q *Queries) GetRegistrationSubmission(ctx context.Context, id int32) (GetRegistrationSubmissionRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationSubmission, id)
	var i GetRegistrationSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedPersonID,
		&i.ResolutionType,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.ResolverUsername,
		&i.EmailVerified,
	)
	return i, err
}

const listIdentityMatchingPersons = `-- name: ListIdentityMatchingPersons :many
SELECT id,first_name,last_name,birth_date,email,phone_number FROM persons ORDER BY id
`

type ListIdentityMatchingPersonsRow struct {
	ID          int32
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	Email       pgtype.Text
	PhoneNumber pgtype.Text
}

// Matching includes archived Persons: archiving does not erase a durable identity.
func (q *Queries) ListIdentityMatchingPersons(ctx context.Context) ([]ListIdentityMatchingPersonsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityMatchingPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityMatchingPersonsRow
	for rows.Next() {
		var i ListIdentityMatchingPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Email,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationCandidates = `-- name: ListRegistrationCandidates :many
SELECT c.submission_id, c.person_id, c.confidence, c.matched_name, c.matched_birth_date, c.matched_email, c.matched_phone, c.detected_at,p.first_name,p.last_name,p.birth_date,p.email,p.phone_number,p.address,p.archived_at,
 u.id AS user_id,u.is_active AS user_is_active,u.activated_at
FROM registration_submission_candidates c JOIN persons p ON p.id=c.person_id
LEFT JOIN users u ON u.person_id=p.id
WHERE c.submission_id=$1
ORDER BY CASE c.confidence WHEN 'strong' THEN 0 WHEN 'possible' THEN 1 ELSE 2 END,p.id
`

type ListRegistrationCandidatesRow struct {
	SubmissionID     int32
	PersonID         int32
	Confidence       string
	MatchedName      bool
	MatchedBirthDate bool
	MatchedEmail     bool
	MatchedPhone     bool
	DetectedAt       pgtype.Timestamptz
	FirstName        string
	LastName         string
	BirthDate        pgtype.Date
	Email            pgtype.Text
	PhoneNumber      pgtype.Text
	Address          pgtype.Text
	ArchivedAt       pgtype.Timestamptz
	UserID           pgtype.Int4
	UserIsActive     pgtype.Bool
	ActivatedAt      pgtype.Timestamptz
}

// Only fields needed by authorized reviewers; no credentials or activation secrets.
func (q *Queries) ListRegistrationCandidates(ctx context.Context, submissionID int32) ([]ListRegistrationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationCandidates, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationCandidatesRow
	for rows.Next() {
		var i ListRegistrationCandidatesRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.PersonID,
			&i.Confidence,
			&i.MatchedName,
			&i.MatchedBirthDate,
			&i.MatchedEmail,
			&i.MatchedPhone,
			&i.DetectedAt,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Email,
			&i.PhoneNumber,
			&i.Address,
			&i.ArchivedAt,
			&i.UserID,
			&i.UserIsActive,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationReviews = `-- name: ListRegistrationReviews :many
SELECT s.id,s.status,s.first_name,s.last_name,s.birth_date,s.created_at,
 EXISTS(SELECT 1 FROM registration_applications a WHERE a.submission_id=s.id AND a.status='needs_review') AS application_needs_review,
 count(c.person_id)::integer AS candidate_count,
 COALESCE(CASE max(CASE c.confidence WHEN 'strong' THEN 3 WHEN 'possible' THEN 2 WHEN 'weak' THEN 1 END)
 WHEN 3 THEN 'strong' WHEN 2 THEN 'possible' WHEN 1 THEN 'weak' END,'none')::text AS best_confidence
FROM registration_submissions s LEFT JOIN registration_submission_candidates c ON c.submission_id=s.id
GROUP BY s.id
ORDER BY CASE WHEN EXISTS(SELECT 1 FROM registration_applications a WHERE a.submission_id=s.id AND a.status='needs_review') THEN 0 ELSE 1 END,
 CASE s.status WHEN 'awaiting_identity_review' THEN 0 WHEN 'received' THEN 1 WHEN 'awaiting_email_verification' THEN 2 ELSE 3 END,
 CASE WHEN s.status IN ('received','awaiting_identity_review') THEN s.created_at END,
 CASE WHEN s.status NOT IN ('received','awaiting_identity_review') THEN s.updated_at END DESC,s.id
`

type ListRegistrationReviewsRow struct {
	ID                     int32
	Status                 string
	FirstName              string
	LastName               string
	BirthDate              pgtype.Date
	CreatedAt              pgtype.Timestamptz
	ApplicationNeedsReview bool
	CandidateCount         int32
	BestConfidence         string
}

func (q *Queries) ListRegistrationReviews(ctx context.Context) ([]ListRegistrationReviewsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationReviewsRow
	for rows.Next() {
		var i ListRegistrationReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.CreatedAt,
			&i.ApplicationNeedsReview,
			&i.CandidateCount,
			&i.BestConfidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRegistrationPerson = `-- name: LockRegistrationPerson :one
SELECT id FROM persons WHERE id=$1 FOR KEY SHARE
`

func (q *Queries) LockRegistrationPerson(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockRegistrationPerson, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const lockRegistrationSubmission = `-- name: LockRegistrationSubmission :one
SELECT id, status, first_name, last_name, birth_date, email, phone_number, address, created_at, updated_at, resolved_person_id, resolution_type, resolved_at, resolved_by_user_id FROM registration_submissions WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockRegistrationSubmission(ctx context.Context, id int32) (RegistrationSubmission, error) {
	row := q.db.QueryRow(ctx, lockRegistrationSubmission, id)
	var i RegistrationSubmission
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedPersonID,
		&i.ResolutionType,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
	)
	return i, err
}

const markRegistrationForReview = `-- name: MarkRegistrationForReview :exec
UPDATE registration_submissions SET status='awaiting_identity_review',updated_at=clock_timestamp()
WHERE id=$1 AND status='received'
`

func (q *Queries) MarkRegistrationForReview(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markRegistrationForReview, id)
	return err
}

const resolveRegistrationSubmission = `-- name: ResolveRegistrationSubmission :one
UPDATE registration_submissions
SET status='resolved',resolved_person_id=$2,resolution_type=$3,resolved_by_user_id=$4,
 resolved_at=clock_timestamp(),updated_at=clock_timestamp()
WHERE id=$1 AND status IN ('received','awaiting_identity_review','awaiting_email_verification')
RETURNING id, status, first_name, last_name, birth_date, email, phone_number, address, created_at, updated_at, resolved_person_id, resolution_type, resolved_at, resolved_by_user_id
`

type ResolveRegistrationSubmissionParams struct {
	ID               int32
	ResolvedPersonID pgtype.Int4
	ResolutionType   pgtype.Text
	ResolvedByUserID pgtype.Int4
}

func (q *Queries) ResolveRegistrationSubmission(ctx context.Context, arg ResolveRegistrationSubmissionParams) (RegistrationSubmission, error) {
	row := q.db.QueryRow(ctx, resolveRegistrationSubmission,
		arg.ID,
		arg.ResolvedPersonID,
		arg.ResolutionType,
		arg.ResolvedByUserID,
	)
	var i RegistrationSubmission
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedPersonID,
		&i.ResolutionType,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
	)
	return i, err
}
