// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_verification_outbox.sql

package dbsqlc

import (
	"context"
)

const claimRegistrationVerificationJob = `-- name: ClaimRegistrationVerificationJob :one
WITH candidate AS (
 SELECT id FROM registration_verification_outbox
 WHERE (status='pending' AND available_at<=clock_timestamp())
    OR (status='processing' AND lease_until<=clock_timestamp())
 ORDER BY available_at,id FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE registration_verification_outbox o SET status='processing',
 lease_until=clock_timestamp()+make_interval(secs=>$1::double precision),
 lease_version=lease_version+1,updated_at=clock_timestamp()
FROM candidate WHERE o.id=candidate.id RETURNING o.id, o.submission_id, o.status, o.attempt_count, o.available_at, o.lease_until, o.lease_version, o.created_at, o.updated_at, o.sent_at, o.finished_at, o.last_error_code, o.recipient_hash
`

func (q *Queries) ClaimRegistrationVerificationJob(ctx context.Context, leaseSeconds float64) (RegistrationVerificationOutbox, error) {
	row := q.db.QueryRow(ctx, claimRegistrationVerificationJob, leaseSeconds)
	var i RegistrationVerificationOutbox
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.LeaseVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.RecipientHash,
	)
	return i, err
}

const countRegistrationVerificationJobs = `-- name: CountRegistrationVerificationJobs :many
SELECT status,count(*)::bigint AS job_count FROM registration_verification_outbox GROUP BY status ORDER BY status
`

type CountRegistrationVerificationJobsRow struct {
	Status   string
	JobCount int64
}

func (q *Queries) CountRegistrationVerificationJobs(ctx context.Context) ([]CountRegistrationVerificationJobsRow, error) {
	rows, err := q.db.Query(ctx, countRegistrationVerificationJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRegistrationVerificationJobsRow
	for rows.Next() {
		var i CountRegistrationVerificationJobsRow
		if err := rows.Scan(&i.Status, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
