// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_verification_outbox.sql

package dbsqlc

import (
	"context"
)

const claimRegistrationVerificationJob = `-- name: ClaimRegistrationVerificationJob :one
UPDATE registration_verification_outbox SET status='processing',
 lease_until=strftime('%Y-%m-%d %H:%M:%f','now',(?1 + 0.0) || ' seconds'),
 lease_version=lease_version+1,updated_at=strftime('%Y-%m-%d %H:%M:%f','now')
WHERE id=(SELECT id FROM registration_verification_outbox WHERE (status='pending' AND available_at<=strftime('%Y-%m-%d %H:%M:%f','now')) OR (status='processing' AND lease_until<=strftime('%Y-%m-%d %H:%M:%f','now')) ORDER BY available_at,id LIMIT 1) RETURNING id, submission_id, status, attempt_count, available_at, lease_until, lease_version, created_at, updated_at, sent_at, finished_at, last_error_code, recipient_hash
`

func (q *Queries) ClaimRegistrationVerificationJob(ctx context.Context, leaseSeconds interface{}) (RegistrationVerificationOutbox, error) {
	row := q.db.QueryRowContext(ctx, claimRegistrationVerificationJob, leaseSeconds)
	var i RegistrationVerificationOutbox
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.LeaseVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.RecipientHash,
	)
	return i, err
}

const countRegistrationVerificationJobs = `-- name: CountRegistrationVerificationJobs :many
SELECT status,CAST(count(*) AS BIGINT) AS job_count FROM registration_verification_outbox GROUP BY status ORDER BY status
`

type CountRegistrationVerificationJobsRow struct {
	Status   string
	JobCount int64
}

func (q *Queries) CountRegistrationVerificationJobs(ctx context.Context) ([]CountRegistrationVerificationJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, countRegistrationVerificationJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRegistrationVerificationJobsRow
	for rows.Next() {
		var i CountRegistrationVerificationJobsRow
		if err := rows.Scan(&i.Status, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
