// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_applications.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const createRegistrationApplication = `-- name: CreateRegistrationApplication :one
INSERT INTO registration_applications(submission_id,request_key,season_id,membership_type_id,required_activity_id)
VALUES (?1,?2,?3,?4,?5) RETURNING required_activity_id, id, submission_id, request_key, season_id, membership_type_id, status, membership_id, last_error_code, created_at, updated_at, finalized_at
`

type CreateRegistrationApplicationParams struct {
	SubmissionID       int32
	RequestKey         []byte
	SeasonID           int32
	MembershipTypeID   int32
	RequiredActivityID int32
}

func (q *Queries) CreateRegistrationApplication(ctx context.Context, arg CreateRegistrationApplicationParams) (RegistrationApplication, error) {
	row := q.db.QueryRowContext(ctx, createRegistrationApplication,
		arg.SubmissionID,
		arg.RequestKey,
		arg.SeasonID,
		arg.MembershipTypeID,
		arg.RequiredActivityID,
	)
	var i RegistrationApplication
	err := row.Scan(
		&i.RequiredActivityID,
		&i.ID,
		&i.SubmissionID,
		&i.RequestKey,
		&i.SeasonID,
		&i.MembershipTypeID,
		&i.Status,
		&i.MembershipID,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const createRegistrationApplicationActivity = `-- name: CreateRegistrationApplicationActivity :exec
INSERT INTO registration_application_activities(application_id,activity_id) VALUES (?1,?2)
`

type CreateRegistrationApplicationActivityParams struct {
	ApplicationID int32
	ActivityID    int32
}

func (q *Queries) CreateRegistrationApplicationActivity(ctx context.Context, arg CreateRegistrationApplicationActivityParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationApplicationActivity, arg.ApplicationID, arg.ActivityID)
	return err
}

const createRegistrationApplicationConsent = `-- name: CreateRegistrationApplicationConsent :exec
INSERT INTO registration_application_consents(application_id,consent_definition_id,decision,presented_at) VALUES (?1,?2,?3,?4)
`

type CreateRegistrationApplicationConsentParams struct {
	ApplicationID       int32
	ConsentDefinitionID int32
	Decision            string
	PresentedAt         dbtypes.Timestamp
}

func (q *Queries) CreateRegistrationApplicationConsent(ctx context.Context, arg CreateRegistrationApplicationConsentParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationApplicationConsent,
		arg.ApplicationID,
		arg.ConsentDefinitionID,
		arg.Decision,
		arg.PresentedAt,
	)
	return err
}

const getRegistrationApplicationByRequest = `-- name: GetRegistrationApplicationByRequest :one
SELECT required_activity_id, id, submission_id, request_key, season_id, membership_type_id, status, membership_id, last_error_code, created_at, updated_at, finalized_at FROM registration_applications WHERE request_key=?1
`

func (q *Queries) GetRegistrationApplicationByRequest(ctx context.Context, requestKey []byte) (RegistrationApplication, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationApplicationByRequest, requestKey)
	var i RegistrationApplication
	err := row.Scan(
		&i.RequiredActivityID,
		&i.ID,
		&i.SubmissionID,
		&i.RequestKey,
		&i.SeasonID,
		&i.MembershipTypeID,
		&i.Status,
		&i.MembershipID,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getRegistrationApplicationDetails = `-- name: GetRegistrationApplicationDetails :one
SELECT a.required_activity_id, a.id, a.submission_id, a.request_key, a.season_id, a.membership_type_id, a.status, a.membership_id, a.last_error_code, a.created_at, a.updated_at, a.finalized_at,s.name AS season_name,t.name AS membership_type_name
FROM registration_applications a JOIN seasons s ON s.id=a.season_id JOIN membership_types t ON t.id=a.membership_type_id
WHERE a.submission_id=?1
`

type GetRegistrationApplicationDetailsRow struct {
	RequiredActivityID int32
	ID                 int32
	SubmissionID       int32
	RequestKey         []byte
	SeasonID           int32
	MembershipTypeID   int32
	Status             string
	MembershipID       sql.NullInt32
	LastErrorCode      sql.NullString
	CreatedAt          dbtypes.Timestamp
	UpdatedAt          dbtypes.Timestamp
	FinalizedAt        dbtypes.Timestamp
	SeasonName         string
	MembershipTypeName string
}

func (q *Queries) GetRegistrationApplicationDetails(ctx context.Context, submissionID int32) (GetRegistrationApplicationDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationApplicationDetails, submissionID)
	var i GetRegistrationApplicationDetailsRow
	err := row.Scan(
		&i.RequiredActivityID,
		&i.ID,
		&i.SubmissionID,
		&i.RequestKey,
		&i.SeasonID,
		&i.MembershipTypeID,
		&i.Status,
		&i.MembershipID,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
		&i.SeasonName,
		&i.MembershipTypeName,
	)
	return i, err
}

const getVerifiedRegistrationApplicationStatus = `-- name: GetVerifiedRegistrationApplicationStatus :one
SELECT a.status FROM registration_email_verifications v JOIN registration_applications a ON a.submission_id=v.submission_id
WHERE v.public_reference=?1 AND v.used_at IS NOT NULL
`

func (q *Queries) GetVerifiedRegistrationApplicationStatus(ctx context.Context, publicReference string) (string, error) {
	row := q.db.QueryRowContext(ctx, getVerifiedRegistrationApplicationStatus, publicReference)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listPresentedRegistrationConsents = `-- name: ListPresentedRegistrationConsents :many
SELECT id, code, version, title, description, is_active, created_at FROM consent_definitions WHERE id IN (/*SLICE:ids*/?) ORDER BY code,version
`

func (q *Queries) ListPresentedRegistrationConsents(ctx context.Context, ids []int32) ([]ConsentDefinition, error) {
	query := listPresentedRegistrationConsents
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentDefinition
	for rows.Next() {
		var i ConsentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationActivities = `-- name: ListRegistrationActivities :many
SELECT id, name, is_active, created_at FROM activities WHERE is_active ORDER BY name,id
`

func (q *Queries) ListRegistrationActivities(ctx context.Context) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listRegistrationActivities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationApplicationActivities = `-- name: ListRegistrationApplicationActivities :many
SELECT a.id, a.name, a.is_active, a.created_at FROM registration_application_activities r JOIN activities a ON a.id=r.activity_id WHERE r.application_id=?1 ORDER BY a.name,a.id
`

func (q *Queries) ListRegistrationApplicationActivities(ctx context.Context, applicationID int32) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listRegistrationApplicationActivities, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationApplicationConsents = `-- name: ListRegistrationApplicationConsents :many
SELECT r.application_id, r.consent_definition_id, r.decision, r.presented_at,d.code,d.version,d.title,d.description FROM registration_application_consents r
JOIN consent_definitions d ON d.id=r.consent_definition_id WHERE r.application_id=?1 ORDER BY d.code,d.version
`

type ListRegistrationApplicationConsentsRow struct {
	ApplicationID       int32
	ConsentDefinitionID int32
	Decision            string
	PresentedAt         dbtypes.Timestamp
	Code                string
	Version             int32
	Title               string
	Description         string
}

func (q *Queries) ListRegistrationApplicationConsents(ctx context.Context, applicationID int32) ([]ListRegistrationApplicationConsentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRegistrationApplicationConsents, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationApplicationConsentsRow
	for rows.Next() {
		var i ListRegistrationApplicationConsentsRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.ConsentDefinitionID,
			&i.Decision,
			&i.PresentedAt,
			&i.Code,
			&i.Version,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationMembershipTypes = `-- name: ListRegistrationMembershipTypes :many
SELECT id, name, is_active, created_at, amount_cents, currency, public_note FROM membership_types WHERE is_active ORDER BY name,id
`

func (q *Queries) ListRegistrationMembershipTypes(ctx context.Context) ([]MembershipType, error) {
	rows, err := q.db.QueryContext(ctx, listRegistrationMembershipTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MembershipType
	for rows.Next() {
		var i MembershipType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.AmountCents,
			&i.Currency,
			&i.PublicNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationSeasons = `-- name: ListRegistrationSeasons :many
SELECT id, name, starts_at, ends_at, is_active, created_at FROM seasons WHERE is_active ORDER BY starts_at DESC,id
`

func (q *Queries) ListRegistrationSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, listRegistrationSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRegistrationApplication = `-- name: LockRegistrationApplication :one
SELECT required_activity_id, id, submission_id, request_key, season_id, membership_type_id, status, membership_id, last_error_code, created_at, updated_at, finalized_at FROM registration_applications WHERE submission_id=?1
`

func (q *Queries) LockRegistrationApplication(ctx context.Context, submissionID int32) (RegistrationApplication, error) {
	row := q.db.QueryRowContext(ctx, lockRegistrationApplication, submissionID)
	var i RegistrationApplication
	err := row.Scan(
		&i.RequiredActivityID,
		&i.ID,
		&i.SubmissionID,
		&i.RequestKey,
		&i.SeasonID,
		&i.MembershipTypeID,
		&i.Status,
		&i.MembershipID,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const markRegistrationApplicationCreated = `-- name: MarkRegistrationApplicationCreated :exec
UPDATE registration_applications SET status='membership_created',membership_id=?1,finalized_at=strftime('%Y-%m-%d %H:%M:%f','now'),updated_at=strftime('%Y-%m-%d %H:%M:%f','now'),last_error_code=NULL WHERE id=?2
`

type MarkRegistrationApplicationCreatedParams struct {
	MembershipID sql.NullInt32
	ID           int32
}

func (q *Queries) MarkRegistrationApplicationCreated(ctx context.Context, arg MarkRegistrationApplicationCreatedParams) error {
	_, err := q.db.ExecContext(ctx, markRegistrationApplicationCreated, arg.MembershipID, arg.ID)
	return err
}

const markRegistrationApplicationReview = `-- name: MarkRegistrationApplicationReview :exec
UPDATE registration_applications SET status='needs_review',last_error_code=?1,updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?2
`

type MarkRegistrationApplicationReviewParams struct {
	LastErrorCode sql.NullString
	ID            int32
}

func (q *Queries) MarkRegistrationApplicationReview(ctx context.Context, arg MarkRegistrationApplicationReviewParams) error {
	_, err := q.db.ExecContext(ctx, markRegistrationApplicationReview, arg.LastErrorCode, arg.ID)
	return err
}
