// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package dbsqlc

import (
	"context"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles(user_id,role_id) VALUES ($1,$2)
ON CONFLICT (user_id,role_id) DO NOTHING
`

type AssignUserRoleParams struct {
	UserID int32
	RoleID int32
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name FROM roles WHERE name=$1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listAvailableRoles = `-- name: ListAvailableRoles :many
SELECT id, name FROM roles ORDER BY name
`

func (q *Queries) ListAvailableRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listAvailableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.name FROM roles r JOIN user_roles ur ON ur.role_id=r.id
WHERE ur.user_id=$1 ORDER BY r.name
`

func (q *Queries) ListUserRoles(ctx context.Context, userID int32) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserRole = `-- name: RevokeUserRole :exec
DELETE FROM user_roles WHERE user_id=$1 AND role_id=$2
`

type RevokeUserRoleParams struct {
	UserID int32
	RoleID int32
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error {
	_, err := q.db.Exec(ctx, revokeUserRole, arg.UserID, arg.RoleID)
	return err
}
