// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: self_service_account.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const consumeEmailChange = `-- name: ConsumeEmailChange :execrows
UPDATE user_email_change_requests SET used_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?1 AND used_at IS NULL AND invalidated_at IS NULL AND expires_at>strftime('%Y-%m-%d %H:%M:%f','now')
`

func (q *Queries) ConsumeEmailChange(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeEmailChange, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countRecentEmailChanges = `-- name: CountRecentEmailChanges :one
SELECT CAST(count(*) AS BIGINT) FROM user_email_change_requests WHERE user_id=?1 AND created_at>strftime('%Y-%m-%d %H:%M:%f','now','-1 hour')
`

func (q *Queries) CountRecentEmailChanges(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentEmailChanges, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAccountSecurityEvent = `-- name: CreateAccountSecurityEvent :exec
INSERT INTO account_security_events(user_id,person_id,event) VALUES(?1,?2,?3)
`

type CreateAccountSecurityEventParams struct {
	UserID   int32
	PersonID int32
	Event    string
}

func (q *Queries) CreateAccountSecurityEvent(ctx context.Context, arg CreateAccountSecurityEventParams) error {
	_, err := q.db.ExecContext(ctx, createAccountSecurityEvent, arg.UserID, arg.PersonID, arg.Event)
	return err
}

const createEmailChange = `-- name: CreateEmailChange :exec
INSERT INTO user_email_change_requests(user_id,person_id,new_email,new_email_normalized,new_email_hash,code_hash,expires_at)
VALUES(?1,?2,?3,?4,?5,?6,strftime('%Y-%m-%d %H:%M:%f','now',(?7 + 0.0) || ' seconds'))
`

type CreateEmailChangeParams struct {
	UserID             int32
	PersonID           int32
	NewEmail           string
	NewEmailNormalized string
	NewEmailHash       []byte
	CodeHash           []byte
	TtlSeconds         interface{}
}

func (q *Queries) CreateEmailChange(ctx context.Context, arg CreateEmailChangeParams) error {
	_, err := q.db.ExecContext(ctx, createEmailChange,
		arg.UserID,
		arg.PersonID,
		arg.NewEmail,
		arg.NewEmailNormalized,
		arg.NewEmailHash,
		arg.CodeHash,
		arg.TtlSeconds,
	)
	return err
}

const invalidateEmailChanges = `-- name: InvalidateEmailChanges :exec
UPDATE user_email_change_requests SET invalidated_at=strftime('%Y-%m-%d %H:%M:%f','now')
WHERE user_id=?1 AND used_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) InvalidateEmailChanges(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, invalidateEmailChanges, userID)
	return err
}

const lockActiveEmailChange = `-- name: LockActiveEmailChange :one
SELECT id,new_email,code_hash FROM user_email_change_requests
WHERE user_id=?1 AND person_id=?2 AND used_at IS NULL AND invalidated_at IS NULL
AND expires_at>strftime('%Y-%m-%d %H:%M:%f','now')
`

type LockActiveEmailChangeParams struct {
	UserID   int32
	PersonID int32
}

type LockActiveEmailChangeRow struct {
	ID       int32
	NewEmail string
	CodeHash []byte
}

func (q *Queries) LockActiveEmailChange(ctx context.Context, arg LockActiveEmailChangeParams) (LockActiveEmailChangeRow, error) {
	row := q.db.QueryRowContext(ctx, lockActiveEmailChange, arg.UserID, arg.PersonID)
	var i LockActiveEmailChangeRow
	err := row.Scan(&i.ID, &i.NewEmail, &i.CodeHash)
	return i, err
}

const lockSelfServiceAccount = `-- name: LockSelfServiceAccount :one
SELECT u.id,u.person_id,u.password_hash,p.email
FROM users u JOIN persons p ON p.id=u.person_id
WHERE u.id=?1 AND u.is_active AND u.activated_at IS NOT NULL
 AND u.password_hash IS NOT NULL AND p.archived_at IS NULL
`

type LockSelfServiceAccountRow struct {
	ID           int32
	PersonID     int32
	PasswordHash sql.NullString
	Email        sql.NullString
}

// All account mutations serialize on the session-selected User first.
func (q *Queries) LockSelfServiceAccount(ctx context.Context, id int32) (LockSelfServiceAccountRow, error) {
	row := q.db.QueryRowContext(ctx, lockSelfServiceAccount, id)
	var i LockSelfServiceAccountRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.PasswordHash,
		&i.Email,
	)
	return i, err
}

const updateSelfServiceContact = `-- name: UpdateSelfServiceContact :exec
UPDATE persons SET phone_number=?1,address=?2,updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?3 AND archived_at IS NULL
`

type UpdateSelfServiceContactParams struct {
	PhoneNumber sql.NullString
	Address     sql.NullString
	ID          int32
}

func (q *Queries) UpdateSelfServiceContact(ctx context.Context, arg UpdateSelfServiceContactParams) error {
	_, err := q.db.ExecContext(ctx, updateSelfServiceContact, arg.PhoneNumber, arg.Address, arg.ID)
	return err
}

const updateSelfServiceEmail = `-- name: UpdateSelfServiceEmail :exec
UPDATE persons SET email=?1,updated_at=strftime('%Y-%m-%d %H:%M:%f','now') WHERE id=?2 AND archived_at IS NULL
`

type UpdateSelfServiceEmailParams struct {
	Email sql.NullString
	ID    int32
}

func (q *Queries) UpdateSelfServiceEmail(ctx context.Context, arg UpdateSelfServiceEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateSelfServiceEmail, arg.Email, arg.ID)
	return err
}

const updateSelfServicePassword = `-- name: UpdateSelfServicePassword :exec
UPDATE users SET password_hash=?1 WHERE id=?2
`

type UpdateSelfServicePasswordParams struct {
	PasswordHash sql.NullString
	ID           int32
}

func (q *Queries) UpdateSelfServicePassword(ctx context.Context, arg UpdateSelfServicePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateSelfServicePassword, arg.PasswordHash, arg.ID)
	return err
}
