// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: self_service_account.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailChange = `-- name: ConsumeEmailChange :execrows
UPDATE user_email_change_requests SET used_at=clock_timestamp() WHERE id=$1 AND used_at IS NULL AND invalidated_at IS NULL AND expires_at>clock_timestamp()
`

func (q *Queries) ConsumeEmailChange(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEmailChange, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentEmailChanges = `-- name: CountRecentEmailChanges :one
SELECT count(*) FROM user_email_change_requests WHERE user_id=$1 AND created_at>clock_timestamp()-interval '1 hour'
`

func (q *Queries) CountRecentEmailChanges(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentEmailChanges, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountSecurityEvent = `-- name: CreateAccountSecurityEvent :exec
INSERT INTO account_security_events(user_id,person_id,event) VALUES($1,$2,$3)
`

type CreateAccountSecurityEventParams struct {
	UserID   int32
	PersonID int32
	Event    string
}

func (q *Queries) CreateAccountSecurityEvent(ctx context.Context, arg CreateAccountSecurityEventParams) error {
	_, err := q.db.Exec(ctx, createAccountSecurityEvent, arg.UserID, arg.PersonID, arg.Event)
	return err
}

const createEmailChange = `-- name: CreateEmailChange :exec
INSERT INTO user_email_change_requests(user_id,person_id,new_email,new_email_normalized,new_email_hash,code_hash,expires_at)
VALUES($1,$2,$3,$4,$5,$6,clock_timestamp()+make_interval(secs => $7::float8))
`

type CreateEmailChangeParams struct {
	UserID             int32
	PersonID           int32
	NewEmail           string
	NewEmailNormalized string
	NewEmailHash       []byte
	CodeHash           []byte
	TtlSeconds         float64
}

func (q *Queries) CreateEmailChange(ctx context.Context, arg CreateEmailChangeParams) error {
	_, err := q.db.Exec(ctx, createEmailChange,
		arg.UserID,
		arg.PersonID,
		arg.NewEmail,
		arg.NewEmailNormalized,
		arg.NewEmailHash,
		arg.CodeHash,
		arg.TtlSeconds,
	)
	return err
}

const invalidateEmailChanges = `-- name: InvalidateEmailChanges :exec
UPDATE user_email_change_requests SET invalidated_at=clock_timestamp()
WHERE user_id=$1 AND used_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) InvalidateEmailChanges(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, invalidateEmailChanges, userID)
	return err
}

const lockActiveEmailChange = `-- name: LockActiveEmailChange :one
SELECT id,new_email,code_hash FROM user_email_change_requests
WHERE user_id=$1 AND person_id=$2 AND used_at IS NULL AND invalidated_at IS NULL
AND expires_at>clock_timestamp() FOR UPDATE
`

type LockActiveEmailChangeParams struct {
	UserID   int32
	PersonID int32
}

type LockActiveEmailChangeRow struct {
	ID       int64
	NewEmail string
	CodeHash []byte
}

func (q *Queries) LockActiveEmailChange(ctx context.Context, arg LockActiveEmailChangeParams) (LockActiveEmailChangeRow, error) {
	row := q.db.QueryRow(ctx, lockActiveEmailChange, arg.UserID, arg.PersonID)
	var i LockActiveEmailChangeRow
	err := row.Scan(&i.ID, &i.NewEmail, &i.CodeHash)
	return i, err
}

const lockSelfServiceAccount = `-- name: LockSelfServiceAccount :one
SELECT u.id,u.person_id,u.password_hash,p.email
FROM users u JOIN persons p ON p.id=u.person_id
WHERE u.id=$1 AND u.is_active AND u.activated_at IS NOT NULL
 AND u.password_hash IS NOT NULL AND p.archived_at IS NULL FOR UPDATE OF u,p
`

type LockSelfServiceAccountRow struct {
	ID           int32
	PersonID     int32
	PasswordHash pgtype.Text
	Email        pgtype.Text
}

// All account mutations serialize on the session-selected User first.
func (q *Queries) LockSelfServiceAccount(ctx context.Context, id int32) (LockSelfServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, lockSelfServiceAccount, id)
	var i LockSelfServiceAccountRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.PasswordHash,
		&i.Email,
	)
	return i, err
}

const updateSelfServiceContact = `-- name: UpdateSelfServiceContact :exec
UPDATE persons SET phone_number=$2,address=$3,updated_at=clock_timestamp() WHERE id=$1 AND archived_at IS NULL
`

type UpdateSelfServiceContactParams struct {
	ID          int32
	PhoneNumber pgtype.Text
	Address     pgtype.Text
}

func (q *Queries) UpdateSelfServiceContact(ctx context.Context, arg UpdateSelfServiceContactParams) error {
	_, err := q.db.Exec(ctx, updateSelfServiceContact, arg.ID, arg.PhoneNumber, arg.Address)
	return err
}

const updateSelfServiceEmail = `-- name: UpdateSelfServiceEmail :exec
UPDATE persons SET email=$2,updated_at=clock_timestamp() WHERE id=$1 AND archived_at IS NULL
`

type UpdateSelfServiceEmailParams struct {
	ID    int32
	Email pgtype.Text
}

func (q *Queries) UpdateSelfServiceEmail(ctx context.Context, arg UpdateSelfServiceEmailParams) error {
	_, err := q.db.Exec(ctx, updateSelfServiceEmail, arg.ID, arg.Email)
	return err
}

const updateSelfServicePassword = `-- name: UpdateSelfServicePassword :exec
UPDATE users SET password_hash=$2 WHERE id=$1
`

type UpdateSelfServicePasswordParams struct {
	ID           int32
	PasswordHash pgtype.Text
}

func (q *Queries) UpdateSelfServicePassword(ctx context.Context, arg UpdateSelfServicePasswordParams) error {
	_, err := q.db.Exec(ctx, updateSelfServicePassword, arg.ID, arg.PasswordHash)
	return err
}
