// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_quota.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTrialQuotaLimit = `-- name: GetTrialQuotaLimit :one
SELECT max_trials_per_person_per_season FROM organizations WHERE is_active
`

func (q *Queries) GetTrialQuotaLimit(ctx context.Context) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getTrialQuotaLimit)
	var max_trials_per_person_per_season pgtype.Int4
	err := row.Scan(&max_trials_per_person_per_season)
	return max_trials_per_person_per_season, err
}

const listPersonTrialQuotaFacts = `-- name: ListPersonTrialQuotaFacts :many
SELECT t.id,t.status,
 CASE WHEN t.group_slot_id IS NOT NULL THEN ARRAY[gs.season_id]::integer[]
 ELSE ARRAY(SELECT s.id FROM seasons s WHERE t.trial_date BETWEEN s.starts_at AND s.ends_at ORDER BY s.id)::integer[] END AS season_ids
FROM trial_registrations t LEFT JOIN group_slots gs ON gs.id=t.group_slot_id
WHERE t.person_id=$1 ORDER BY t.id
`

type ListPersonTrialQuotaFactsRow struct {
	ID        int32
	Status    string
	SeasonIds []int32
}

func (q *Queries) ListPersonTrialQuotaFacts(ctx context.Context, personID int32) ([]ListPersonTrialQuotaFactsRow, error) {
	rows, err := q.db.Query(ctx, listPersonTrialQuotaFacts, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonTrialQuotaFactsRow
	for rows.Next() {
		var i ListPersonTrialQuotaFactsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.SeasonIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrialQuotaSeasons = `-- name: ListTrialQuotaSeasons :many
SELECT id,name,is_active FROM seasons ORDER BY starts_at DESC,id DESC
`

type ListTrialQuotaSeasonsRow struct {
	ID       int32
	Name     string
	IsActive bool
}

func (q *Queries) ListTrialQuotaSeasons(ctx context.Context) ([]ListTrialQuotaSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listTrialQuotaSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrialQuotaSeasonsRow
	for rows.Next() {
		var i ListTrialQuotaSeasonsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTrialQuotaPolicy = `-- name: LockTrialQuotaPolicy :one
SELECT max_trials_per_person_per_season FROM organizations WHERE is_active FOR SHARE
`

// Configuration also locks this row before changing seasons or slots.
func (q *Queries) LockTrialQuotaPolicy(ctx context.Context) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, lockTrialQuotaPolicy)
	var max_trials_per_person_per_season pgtype.Int4
	err := row.Scan(&max_trials_per_person_per_season)
	return max_trials_per_person_per_season, err
}

const resolveTrialQuotaSeason = `-- name: ResolveTrialQuotaSeason :many
SELECT s.id,s.name FROM seasons s
WHERE ($1::integer IS NOT NULL AND s.id=(SELECT gs.season_id FROM group_slots gs WHERE gs.id=$1))
 OR ($1::integer IS NULL AND $2::date BETWEEN s.starts_at AND s.ends_at)
ORDER BY s.starts_at DESC,s.id
`

type ResolveTrialQuotaSeasonParams struct {
	SlotID    pgtype.Int4
	TrialDate pgtype.Date
}

type ResolveTrialQuotaSeasonRow struct {
	ID   int32
	Name string
}

// Include inactive seasons: deactivation must not erase trial history.
func (q *Queries) ResolveTrialQuotaSeason(ctx context.Context, arg ResolveTrialQuotaSeasonParams) ([]ResolveTrialQuotaSeasonRow, error) {
	rows, err := q.db.Query(ctx, resolveTrialQuotaSeason, arg.SlotID, arg.TrialDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveTrialQuotaSeasonRow
	for rows.Next() {
		var i ResolveTrialQuotaSeasonRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
