// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_quota.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const getTrialQuotaLimit = `-- name: GetTrialQuotaLimit :one
SELECT max_trials_per_person_per_season FROM organizations WHERE is_active
`

func (q *Queries) GetTrialQuotaLimit(ctx context.Context) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getTrialQuotaLimit)
	var max_trials_per_person_per_season sql.NullInt32
	err := row.Scan(&max_trials_per_person_per_season)
	return max_trials_per_person_per_season, err
}

const listPersonTrialQuotaFacts = `-- name: ListPersonTrialQuotaFacts :many
SELECT t.id,t.status,
 CAST((SELECT json_group_array(s.id) FROM seasons s WHERE (t.group_slot_id IS NOT NULL AND s.id=gs.season_id) OR (t.group_slot_id IS NULL AND t.trial_date BETWEEN s.starts_at AND s.ends_at)) AS JSON_TEXT_IDS) AS season_ids
FROM trial_registrations t LEFT JOIN group_slots gs ON gs.id=t.group_slot_id
WHERE t.person_id=?1 ORDER BY t.id
`

type ListPersonTrialQuotaFactsRow struct {
	ID        int32
	Status    string
	SeasonIds dbtypes.IDs
}

func (q *Queries) ListPersonTrialQuotaFacts(ctx context.Context, personID int32) ([]ListPersonTrialQuotaFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonTrialQuotaFacts, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonTrialQuotaFactsRow
	for rows.Next() {
		var i ListPersonTrialQuotaFactsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.SeasonIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrialQuotaSeasons = `-- name: ListTrialQuotaSeasons :many
SELECT id,name,is_active FROM seasons ORDER BY starts_at DESC,id DESC
`

type ListTrialQuotaSeasonsRow struct {
	ID       int32
	Name     string
	IsActive bool
}

func (q *Queries) ListTrialQuotaSeasons(ctx context.Context) ([]ListTrialQuotaSeasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrialQuotaSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrialQuotaSeasonsRow
	for rows.Next() {
		var i ListTrialQuotaSeasonsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTrialQuotaPolicy = `-- name: LockTrialQuotaPolicy :one
SELECT max_trials_per_person_per_season FROM organizations WHERE is_active
`

// BEGIN IMMEDIATE excludes concurrent policy, season and slot changes.
func (q *Queries) LockTrialQuotaPolicy(ctx context.Context) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, lockTrialQuotaPolicy)
	var max_trials_per_person_per_season sql.NullInt32
	err := row.Scan(&max_trials_per_person_per_season)
	return max_trials_per_person_per_season, err
}

const resolveTrialQuotaSeason = `-- name: ResolveTrialQuotaSeason :many
SELECT s.id,s.name FROM seasons s
WHERE (?1 IS NOT NULL AND s.id=(SELECT gs.season_id FROM group_slots gs WHERE gs.id=?1))
 OR (?1 IS NULL AND (?2>=s.starts_at AND ?2<=s.ends_at))
ORDER BY s.starts_at DESC,s.id
`

type ResolveTrialQuotaSeasonParams struct {
	SlotID    interface{}
	TrialDate dbtypes.Date
}

type ResolveTrialQuotaSeasonRow struct {
	ID   int32
	Name string
}

// Include inactive seasons: deactivation must not erase trial history.
func (q *Queries) ResolveTrialQuotaSeason(ctx context.Context, arg ResolveTrialQuotaSeasonParams) ([]ResolveTrialQuotaSeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, resolveTrialQuotaSeason, arg.SlotID, arg.TrialDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveTrialQuotaSeasonRow
	for rows.Next() {
		var i ResolveTrialQuotaSeasonRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
