// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_registrations.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/grapinou/club-core/internal/database/dbtypes"
)

const createTrial = `-- name: CreateTrial :one
INSERT INTO trial_registrations (person_id, activity_id, group_id, group_slot_id, trial_date, status, notes)
VALUES (?1, ?2, ?3, ?4, ?5, 'registered', ?6) RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id, revision
`

type CreateTrialParams struct {
	PersonID    int32
	ActivityID  int32
	GroupID     sql.NullInt32
	GroupSlotID sql.NullInt32
	TrialDate   dbtypes.Date
	Notes       sql.NullString
}

// Scheduling writes are called through internal/trials.Service.
func (q *Queries) CreateTrial(ctx context.Context, arg CreateTrialParams) (TrialRegistration, error) {
	row := q.db.QueryRowContext(ctx, createTrial,
		arg.PersonID,
		arg.ActivityID,
		arg.GroupID,
		arg.GroupSlotID,
		arg.TrialDate,
		arg.Notes,
	)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
		&i.Revision,
	)
	return i, err
}

const getTrial = `-- name: GetTrial :one
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, COALESCE((SELECT l.name FROM locations l WHERE l.id=gs.location_id),gs.location) AS location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.id = ?1
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type GetTrialRow struct {
	TrialID      int32
	TrialDate    dbtypes.Date
	Status       string
	Notes        sql.NullString
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    dbtypes.Date
	PhoneNumber  sql.NullString
	ActivityID   int32
	ActivityName string
	GroupID      sql.NullInt32
	GroupName    sql.NullString
	GroupSlotID  sql.NullInt32
	Weekday      sql.NullInt16
	StartTime    dbtypes.Time
	EndTime      dbtypes.Time
	Location     sql.NullString
}

func (q *Queries) GetTrial(ctx context.Context, id int32) (GetTrialRow, error) {
	row := q.db.QueryRowContext(ctx, getTrial, id)
	var i GetTrialRow
	err := row.Scan(
		&i.TrialID,
		&i.TrialDate,
		&i.Status,
		&i.Notes,
		&i.PersonID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.ActivityID,
		&i.ActivityName,
		&i.GroupID,
		&i.GroupName,
		&i.GroupSlotID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
	)
	return i, err
}

const listPersonTrials = `-- name: ListPersonTrials :many
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, COALESCE((SELECT l.name FROM locations l WHERE l.id=gs.location_id),gs.location) AS location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.person_id = ?1
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type ListPersonTrialsRow struct {
	TrialID      int32
	TrialDate    dbtypes.Date
	Status       string
	Notes        sql.NullString
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    dbtypes.Date
	PhoneNumber  sql.NullString
	ActivityID   int32
	ActivityName string
	GroupID      sql.NullInt32
	GroupName    sql.NullString
	GroupSlotID  sql.NullInt32
	Weekday      sql.NullInt16
	StartTime    dbtypes.Time
	EndTime      dbtypes.Time
	Location     sql.NullString
}

func (q *Queries) ListPersonTrials(ctx context.Context, personID int32) ([]ListPersonTrialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonTrials, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonTrialsRow
	for rows.Next() {
		var i ListPersonTrialsRow
		if err := rows.Scan(
			&i.TrialID,
			&i.TrialDate,
			&i.Status,
			&i.Notes,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.ActivityID,
			&i.ActivityName,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlotID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrialsByDate = `-- name: ListTrialsByDate :many
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, COALESCE((SELECT l.name FROM locations l WHERE l.id=gs.location_id),gs.location) AS location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.trial_date = ?1
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type ListTrialsByDateRow struct {
	TrialID      int32
	TrialDate    dbtypes.Date
	Status       string
	Notes        sql.NullString
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    dbtypes.Date
	PhoneNumber  sql.NullString
	ActivityID   int32
	ActivityName string
	GroupID      sql.NullInt32
	GroupName    sql.NullString
	GroupSlotID  sql.NullInt32
	Weekday      sql.NullInt16
	StartTime    dbtypes.Time
	EndTime      dbtypes.Time
	Location     sql.NullString
}

func (q *Queries) ListTrialsByDate(ctx context.Context, trialDate dbtypes.Date) ([]ListTrialsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrialsByDate, trialDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrialsByDateRow
	for rows.Next() {
		var i ListTrialsByDateRow
		if err := rows.Scan(
			&i.TrialID,
			&i.TrialDate,
			&i.Status,
			&i.Notes,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.ActivityID,
			&i.ActivityName,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlotID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingTrials = `-- name: ListUpcomingTrials :many
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, COALESCE((SELECT l.name FROM locations l WHERE l.id=gs.location_id),gs.location) AS location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.trial_date >= ?1
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type ListUpcomingTrialsRow struct {
	TrialID      int32
	TrialDate    dbtypes.Date
	Status       string
	Notes        sql.NullString
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    dbtypes.Date
	PhoneNumber  sql.NullString
	ActivityID   int32
	ActivityName string
	GroupID      sql.NullInt32
	GroupName    sql.NullString
	GroupSlotID  sql.NullInt32
	Weekday      sql.NullInt16
	StartTime    dbtypes.Time
	EndTime      dbtypes.Time
	Location     sql.NullString
}

func (q *Queries) ListUpcomingTrials(ctx context.Context, fromDate dbtypes.Date) ([]ListUpcomingTrialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingTrials, fromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingTrialsRow
	for rows.Next() {
		var i ListUpcomingTrialsRow
		if err := rows.Scan(
			&i.TrialID,
			&i.TrialDate,
			&i.Status,
			&i.Notes,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.ActivityID,
			&i.ActivityName,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlotID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTrialActivity = `-- name: LockTrialActivity :one
SELECT is_active FROM activities WHERE id=?1
`

// Call inside BEGIN IMMEDIATE to keep activation/calendar valid until the write.
func (q *Queries) LockTrialActivity(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, lockTrialActivity, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const lockTrialGroup = `-- name: LockTrialGroup :one
SELECT activity_id, is_active FROM groups WHERE id=?1
`

type LockTrialGroupRow struct {
	ActivityID int32
	IsActive   bool
}

func (q *Queries) LockTrialGroup(ctx context.Context, id int32) (LockTrialGroupRow, error) {
	row := q.db.QueryRowContext(ctx, lockTrialGroup, id)
	var i LockTrialGroupRow
	err := row.Scan(&i.ActivityID, &i.IsActive)
	return i, err
}

const lockTrialSlot = `-- name: LockTrialSlot :one
SELECT gs.group_id, gs.is_active, CAST((((CAST(strftime('%w',?1) AS INTEGER)+6)%7+1) = gs.weekday
        AND ?1 >= gs.valid_from
        AND (gs.valid_until IS NULL OR ?1 <= gs.valid_until)
        AND (?1>=s.starts_at AND ?1<=s.ends_at)
        AND s.is_active) AS BOOLEAN) AS calendar_valid
FROM group_slots gs JOIN seasons s ON s.id=gs.season_id
WHERE gs.id=?2
`

type LockTrialSlotParams struct {
	TrialDate interface{}
	ID        int32
}

type LockTrialSlotRow struct {
	GroupID       int32
	IsActive      bool
	CalendarValid bool
}

func (q *Queries) LockTrialSlot(ctx context.Context, arg LockTrialSlotParams) (LockTrialSlotRow, error) {
	row := q.db.QueryRowContext(ctx, lockTrialSlot, arg.TrialDate, arg.ID)
	var i LockTrialSlotRow
	err := row.Scan(&i.GroupID, &i.IsActive, &i.CalendarValid)
	return i, err
}

const rescheduleTrial = `-- name: RescheduleTrial :one
UPDATE trial_registrations SET activity_id=?1, group_id=?2, group_slot_id=?3, trial_date=?4,revision=revision+1
WHERE id=?5 RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id, revision
`

type RescheduleTrialParams struct {
	ActivityID  int32
	GroupID     sql.NullInt32
	GroupSlotID sql.NullInt32
	TrialDate   dbtypes.Date
	ID          int32
}

func (q *Queries) RescheduleTrial(ctx context.Context, arg RescheduleTrialParams) (TrialRegistration, error) {
	row := q.db.QueryRowContext(ctx, rescheduleTrial,
		arg.ActivityID,
		arg.GroupID,
		arg.GroupSlotID,
		arg.TrialDate,
		arg.ID,
	)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
		&i.Revision,
	)
	return i, err
}

const updateTrialNotes = `-- name: UpdateTrialNotes :one
UPDATE trial_registrations SET notes=?1,revision=revision+1 WHERE id=?2 RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id, revision
`

type UpdateTrialNotesParams struct {
	Notes sql.NullString
	ID    int32
}

func (q *Queries) UpdateTrialNotes(ctx context.Context, arg UpdateTrialNotesParams) (TrialRegistration, error) {
	row := q.db.QueryRowContext(ctx, updateTrialNotes, arg.Notes, arg.ID)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
		&i.Revision,
	)
	return i, err
}

const updateTrialStatus = `-- name: UpdateTrialStatus :one
UPDATE trial_registrations SET status=?1,revision=revision+1 WHERE id=?2 RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id, revision
`

type UpdateTrialStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateTrialStatus(ctx context.Context, arg UpdateTrialStatusParams) (TrialRegistration, error) {
	row := q.db.QueryRowContext(ctx, updateTrialStatus, arg.Status, arg.ID)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
		&i.Revision,
	)
	return i, err
}
