// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_registrations.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrial = `-- name: CreateTrial :one
INSERT INTO trial_registrations (person_id, activity_id, group_id, group_slot_id, trial_date, status, notes)
VALUES ($1, $2, $3, $4, $5, 'registered', $6) RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id
`

type CreateTrialParams struct {
	PersonID    int32
	ActivityID  int32
	GroupID     pgtype.Int4
	GroupSlotID pgtype.Int4
	TrialDate   pgtype.Date
	Notes       pgtype.Text
}

// Scheduling writes are called through internal/trials.Service.
func (q *Queries) CreateTrial(ctx context.Context, arg CreateTrialParams) (TrialRegistration, error) {
	row := q.db.QueryRow(ctx, createTrial,
		arg.PersonID,
		arg.ActivityID,
		arg.GroupID,
		arg.GroupSlotID,
		arg.TrialDate,
		arg.Notes,
	)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
	)
	return i, err
}

const getTrial = `-- name: GetTrial :one
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, gs.location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.id = $1
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type GetTrialRow struct {
	TrialID      int32
	TrialDate    pgtype.Date
	Status       string
	Notes        pgtype.Text
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    pgtype.Date
	PhoneNumber  pgtype.Text
	ActivityID   int32
	ActivityName string
	GroupID      pgtype.Int4
	GroupName    pgtype.Text
	GroupSlotID  pgtype.Int4
	Weekday      pgtype.Int2
	StartTime    pgtype.Time
	EndTime      pgtype.Time
	Location     pgtype.Text
}

func (q *Queries) GetTrial(ctx context.Context, id int32) (GetTrialRow, error) {
	row := q.db.QueryRow(ctx, getTrial, id)
	var i GetTrialRow
	err := row.Scan(
		&i.TrialID,
		&i.TrialDate,
		&i.Status,
		&i.Notes,
		&i.PersonID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.ActivityID,
		&i.ActivityName,
		&i.GroupID,
		&i.GroupName,
		&i.GroupSlotID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
	)
	return i, err
}

const listPersonTrials = `-- name: ListPersonTrials :many
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, gs.location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.person_id = $1
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type ListPersonTrialsRow struct {
	TrialID      int32
	TrialDate    pgtype.Date
	Status       string
	Notes        pgtype.Text
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    pgtype.Date
	PhoneNumber  pgtype.Text
	ActivityID   int32
	ActivityName string
	GroupID      pgtype.Int4
	GroupName    pgtype.Text
	GroupSlotID  pgtype.Int4
	Weekday      pgtype.Int2
	StartTime    pgtype.Time
	EndTime      pgtype.Time
	Location     pgtype.Text
}

func (q *Queries) ListPersonTrials(ctx context.Context, personID int32) ([]ListPersonTrialsRow, error) {
	rows, err := q.db.Query(ctx, listPersonTrials, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonTrialsRow
	for rows.Next() {
		var i ListPersonTrialsRow
		if err := rows.Scan(
			&i.TrialID,
			&i.TrialDate,
			&i.Status,
			&i.Notes,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.ActivityID,
			&i.ActivityName,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlotID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrialsByDate = `-- name: ListTrialsByDate :many
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, gs.location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.trial_date = $1
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type ListTrialsByDateRow struct {
	TrialID      int32
	TrialDate    pgtype.Date
	Status       string
	Notes        pgtype.Text
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    pgtype.Date
	PhoneNumber  pgtype.Text
	ActivityID   int32
	ActivityName string
	GroupID      pgtype.Int4
	GroupName    pgtype.Text
	GroupSlotID  pgtype.Int4
	Weekday      pgtype.Int2
	StartTime    pgtype.Time
	EndTime      pgtype.Time
	Location     pgtype.Text
}

func (q *Queries) ListTrialsByDate(ctx context.Context, trialDate pgtype.Date) ([]ListTrialsByDateRow, error) {
	rows, err := q.db.Query(ctx, listTrialsByDate, trialDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrialsByDateRow
	for rows.Next() {
		var i ListTrialsByDateRow
		if err := rows.Scan(
			&i.TrialID,
			&i.TrialDate,
			&i.Status,
			&i.Notes,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.ActivityID,
			&i.ActivityName,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlotID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingTrials = `-- name: ListUpcomingTrials :many
SELECT t.id AS trial_id, t.trial_date, t.status, t.notes,
       p.id AS person_id, p.first_name, p.last_name, p.birth_date, p.phone_number,
       a.id AS activity_id, a.name AS activity_name,
       t.group_id, g.name AS group_name, t.group_slot_id,
       gs.weekday, gs.start_time, gs.end_time, gs.location
FROM trial_registrations t
JOIN persons p ON p.id = t.person_id
JOIN activities a ON a.id = t.activity_id
LEFT JOIN groups g ON g.id = t.group_id
LEFT JOIN group_slots gs ON gs.id = t.group_slot_id
WHERE t.trial_date >= $1::date
ORDER BY t.trial_date, gs.start_time NULLS LAST, p.last_name, p.first_name, t.id
`

type ListUpcomingTrialsRow struct {
	TrialID      int32
	TrialDate    pgtype.Date
	Status       string
	Notes        pgtype.Text
	PersonID     int32
	FirstName    string
	LastName     string
	BirthDate    pgtype.Date
	PhoneNumber  pgtype.Text
	ActivityID   int32
	ActivityName string
	GroupID      pgtype.Int4
	GroupName    pgtype.Text
	GroupSlotID  pgtype.Int4
	Weekday      pgtype.Int2
	StartTime    pgtype.Time
	EndTime      pgtype.Time
	Location     pgtype.Text
}

func (q *Queries) ListUpcomingTrials(ctx context.Context, fromDate pgtype.Date) ([]ListUpcomingTrialsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingTrials, fromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingTrialsRow
	for rows.Next() {
		var i ListUpcomingTrialsRow
		if err := rows.Scan(
			&i.TrialID,
			&i.TrialDate,
			&i.Status,
			&i.Notes,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.ActivityID,
			&i.ActivityName,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlotID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTrialActivity = `-- name: LockTrialActivity :one
SELECT is_active FROM activities WHERE id=$1 FOR SHARE
`

// Locks prevent activation/calendar changes between validation and write.
func (q *Queries) LockTrialActivity(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, lockTrialActivity, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const lockTrialGroup = `-- name: LockTrialGroup :one
SELECT activity_id, is_active FROM groups WHERE id=$1 FOR SHARE
`

type LockTrialGroupRow struct {
	ActivityID int32
	IsActive   bool
}

func (q *Queries) LockTrialGroup(ctx context.Context, id int32) (LockTrialGroupRow, error) {
	row := q.db.QueryRow(ctx, lockTrialGroup, id)
	var i LockTrialGroupRow
	err := row.Scan(&i.ActivityID, &i.IsActive)
	return i, err
}

const lockTrialSlot = `-- name: LockTrialSlot :one
SELECT gs.group_id, gs.is_active,
       (EXTRACT(ISODOW FROM $2::date) = gs.weekday
        AND $2::date >= gs.valid_from
        AND (gs.valid_until IS NULL OR $2::date <= gs.valid_until)
        AND $2::date BETWEEN s.starts_at AND s.ends_at)::boolean AS calendar_valid
FROM group_slots gs JOIN seasons s ON s.id=gs.season_id
WHERE gs.id=$1 FOR SHARE OF gs, s
`

type LockTrialSlotParams struct {
	ID        int32
	TrialDate pgtype.Date
}

type LockTrialSlotRow struct {
	GroupID       int32
	IsActive      bool
	CalendarValid bool
}

func (q *Queries) LockTrialSlot(ctx context.Context, arg LockTrialSlotParams) (LockTrialSlotRow, error) {
	row := q.db.QueryRow(ctx, lockTrialSlot, arg.ID, arg.TrialDate)
	var i LockTrialSlotRow
	err := row.Scan(&i.GroupID, &i.IsActive, &i.CalendarValid)
	return i, err
}

const rescheduleTrial = `-- name: RescheduleTrial :one
UPDATE trial_registrations SET activity_id=$2, group_id=$3, group_slot_id=$4, trial_date=$5
WHERE id=$1 RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id
`

type RescheduleTrialParams struct {
	ID          int32
	ActivityID  int32
	GroupID     pgtype.Int4
	GroupSlotID pgtype.Int4
	TrialDate   pgtype.Date
}

func (q *Queries) RescheduleTrial(ctx context.Context, arg RescheduleTrialParams) (TrialRegistration, error) {
	row := q.db.QueryRow(ctx, rescheduleTrial,
		arg.ID,
		arg.ActivityID,
		arg.GroupID,
		arg.GroupSlotID,
		arg.TrialDate,
	)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
	)
	return i, err
}

const updateTrialNotes = `-- name: UpdateTrialNotes :one
UPDATE trial_registrations SET notes=$2 WHERE id=$1 RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id
`

type UpdateTrialNotesParams struct {
	ID    int32
	Notes pgtype.Text
}

func (q *Queries) UpdateTrialNotes(ctx context.Context, arg UpdateTrialNotesParams) (TrialRegistration, error) {
	row := q.db.QueryRow(ctx, updateTrialNotes, arg.ID, arg.Notes)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
	)
	return i, err
}

const updateTrialStatus = `-- name: UpdateTrialStatus :one
UPDATE trial_registrations SET status=$2 WHERE id=$1 RETURNING id, person_id, activity_id, trial_date, status, created_at, notes, group_id, group_slot_id
`

type UpdateTrialStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateTrialStatus(ctx context.Context, arg UpdateTrialStatusParams) (TrialRegistration, error) {
	row := q.db.QueryRow(ctx, updateTrialStatus, arg.ID, arg.Status)
	var i TrialRegistration
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ActivityID,
		&i.TrialDate,
		&i.Status,
		&i.CreatedAt,
		&i.Notes,
		&i.GroupID,
		&i.GroupSlotID,
	)
	return i, err
}
